### ISSUE TITLE
Remove standardUserDefaults cruft from preferences .plist file

### ISSUE THREAD

**Issue by aaronkollasch** [davidwernhart/AlDente#1013]
**Describe the bug**
I like to back up the preference files for tools such as AlDente, and have found that `com.apphousekitchen.aldente-pro.plist` contains 186 items, most of which are not set by or relevant to AlDente. It appears to be a dump of all the NSUserDefaults [standardUserDefaults](https://stackoverflow.com/questions/27640984/how-to-view-complete-contents-of-nsuserdefaults) settings.

A few examples:
- `com.apple.trackpad.version` = 5
- `NSDocumentSaveNewDocumentsToCloud` = NO
- `WebAutomaticSpellingCorrectionEnabled` = NO
- `NSNavRecentPlaces` = [ 5 items ]
- `com.apple.sound.beep.volume` = 0.47292429208755
- `NSLinguisticDataAssetsRequestLastInterval` = 86400

Is it necessary to store this information? When backing up the .plist, I have to allow-list known AlDente preferences, which can exclude settings added in new versions of AlDente.

**Expected behavior**
`com.apphousekitchen.aldente-pro.plist` should only contain preferences related to AlDente.

**MacBook:**
 - MacBookPro18,1
 - macOS Ventura 13.4.1 (c)
 - AlDente Pro
 - AlDente 1.22.2

**Comment by MatthiasKerbl** [comment]
Hi @aaronkollasch,

That's a leftover from a previous version of AlDente. Try to delete the .plist file and set your settings again. Afterward, it should only contain the necessary items from AlDente.

Best,
Matthias

**Comment by aaronkollasch** [comment]
Hi @MatthiasKerbl,

That worked! Thanks for your help. Closing the issue.

Best,
Aaron
