### ISSUE TITLE
Big Sur 12.2.1

### ISSUE THREAD

**Issue by bobd992** [davidwernhart/AlDente#103]
When 12.2.1 big sur was installed, the charging limit from Al Dente was removed. I am scared to re-open al dente because the SMC may have changed in 12.2.1. Can anyone that's more brave than me confirm it works on 12.2.1 with an intel mac?

**Comment by zhouyifan0904** [comment]
I suppose you mean 11.2.1? Yes it works. And there is no need to be scared about changing the SMC as you can always reset it back to system defaults.
