### ISSUE TITLE
Update brew formula

### ISSUE THREAD

**Issue by flying-sausages** [davidwernhart/AlDente#106]
Currently 1.2 is released in brew. I'm not sure whether this is automated or not but it would be nice to change this to 2.0 so we can keep things up to date through this avenue.

https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/aldente.rb#L2

**Comment by vfl97** [comment]
Wish the app has an auto-updater too

**Comment by lpla** [comment]
Given the new format in the release tag and .zip naming, updating it in brew had to be done manually: https://github.com/Homebrew/homebrew-cask/pull/99908

**Comment by lpla** [comment]
Given that v2.0 and v2.1 are tagged as alpha and there are still issues regarding M1 support, I would say AlDente cask won't be updated until a stable version hits or latest alpha is considered stable enough by the users.
