### ISSUE TITLE
Repeatedly in Console Log - Service exited with abnormal code: 78

### ISSUE THREAD

**Issue by mwinestock** [davidwernhart/AlDente#11]
Running MacOS 10.15.5 on a 2015 13" MacBook Pro.  Al Dente reporting repeatedly, in the Console Log:

Jun  1 09:08:32 Family-MacBook-Pro com.apple.xpc.launchd[1] (com.davidwernhart.AlDente-LaunchAtLoginHelper[8302]): Service exited with abnormal code: 78
Jun  1 09:08:32 Family-MacBook-Pro com.apple.xpc.launchd[1] (com.davidwernhart.AlDente-LaunchAtLoginHelper): Service only ran for 4 seconds. Pushing respawn out by 6 seconds.

**Comment by 3zero2** [comment]
Looks like this is related to issue #5
