### ISSUE TITLE
Confirm working with MacBook Pro (13", 2018) Big Sur 11.2.1

### ISSUE THREAD

**Issue by Kumin-91** [davidwernhart/AlDente#110]
<img width="319" alt="스크린샷 2021-02-16 14 45 58" src="https://user-images.githubusercontent.com/74810689/108023554-19fe3f80-7066-11eb-9078-c3b76ba8e70d.png">

It works fine on my MacBook Pro 15,2!
Thank you for making such a great app.

**Comment by ferstar** [comment]
Works on my MacBook Pro 16,2 too, thx!
![image](https://user-images.githubusercontent.com/2854276/108338688-823d5480-7211-11eb-827a-72bb6be6e340.png)

**Comment by TheMazus** [comment]
Hi, glad to hear that the app is working and that you like it.
Greetings,
Matthias
