### ISSUE TITLE
Macbook Air M1 can't set Max Battery Charge

### ISSUE THREAD

**Issue by noahjansen** [davidwernhart/AlDente#112]
When trying to modify the 'Max Battery Charge' it always jumps back to 3%. Tried rebooting, reinstalling helper, restarting app, and checking/unchecking 'Use MacOS battery scale'. This is on Big Sur 11.2.1.

**Comment by noahjansen** [comment]
^This was on v2.1 btw

**Comment by davidwernhart** [comment]
Hey @noahjansen 
The "use macos battery scale" option is not available on the new 2.1 version. Are you sure you are using the right one?

**Comment by basedrhys** [comment]
I had a similar issue when I installed via homebrew - I uninstalled the homebrew version and manually downloaded the latest version from the [Releases](https://github.com/davidwernhart/AlDente/releases) page. Worked great.

**Comment by noahjansen** [comment]
You're both right, I was using v1.2 and misread it as v2.1 as I assumed homebrew would install the latest version. With v2.1 I can now change the slider. Thanks!
