### ISSUE TITLE
How Do You Set the Battery Discharge Percentage beta in 2.1 

### ISSUE THREAD

**Issue by AppleRobert** [davidwernhart/AlDente#115]
How do you set the battery percentage for the "Allow Discharge" beta option? All I see the tick box to enable the beta feature.

**Comment by LeshawnG** [comment]
I believe this setting applies when the battery percentage is above the set level, it will discharge to the set level. So if you have 70% and AlDente set at 50% with "Allow discharge" enabled, it will discharge and stay at 50%.

**Comment by AppleRobert** [comment]
> I believe this setting applies when the battery percentage is above the set level, it will discharge to the set level. So if you have 70% and AlDente set at 50% with "Allow discharge" enabled, it will discharge and stay at 50%.

Thank you for taking the time to reply, Leshawn.
