### ISSUE TITLE
Released AlDente v1.2 file broken

### ISSUE THREAD

**Issue by frowin** [davidwernhart/AlDente#12]
Thank you very much for adding b/w icon! Unfortunately, the new release file is broken. At least MacOS doesn't want to open it.

**Comment by davidwernhart** [comment]
Thank you @frowin ! I am aware of this problem and currently trying to fix it. Please stand by.

**Comment by davidwernhart** [comment]
I updated the release with a new dmg file that should work. Hope everything runs fine for you now!

Thank you and best regards,
David

**Comment by peterlewis** [comment]
Still experiencing this issue with DMG (SHA256 `3b70823226d514ba614c6b0d0ead7389d3c6fa8643701e8bac135498da81fec8`) that I downloaded just 30 seconds ago.
