### ISSUE TITLE
Checking Beta 2.1 on my MBP Intel - check smc -  no enable discharge 

### ISSUE THREAD

**Issue by tosbsas** [davidwernhart/AlDente#122]
when Allow to discharge I can enable smc key, but, enabling that "allow to discharge" disappears - what should I do?

What do you recomend for 2017 Intel mbp?

**Comment by TheMazus** [comment]
Hi tosbsas,
you can uncheck "Use classic SMC Key (Intel)" and still use AlDente with the feature "allow discharge". Keep in mind, when "Use classic SMC Key (Intel)" is unchecked, AlDente will only not work when your MacBook is turned off.

**Comment by tosbsas** [comment]
Ok. Are you saying that with the smc key disabled battery will charge when my mbp is off or on standby? 

What is the recommended setting for a non M1 devices ?

**Comment by aktivde** [comment]
I also don't really understand the new checkbox "Use classic SMC Key (Intel)". You may add an explanation to the readme?
