### ISSUE TITLE
Charge limiting doesn't work unless application is running.

### ISSUE THREAD

**Issue by Averiun** [davidwernhart/AlDente#125]
I don't know if this is the normal behaviour, but charge limiting doesn't work unless the application is running. 
My only problem with this is that the menu bar icon doesnt really look good nor does it fit with the stock macOS icons.

**Comment by jacksonchui** [comment]
You should use something like [Dozer](https://github.com/Mortennn/Dozer) to hide it then.

**Comment by TheMazus** [comment]
Hi Averiun,
are you on an Intel or Apple Silicon Macbook?

**Comment by Averiun** [comment]
Hi!
I have the M1 MacBook Pro

**Comment by TheMazus** [comment]
> Hi!
> I have the M1 MacBook Pro

For M1 MacBooks it is normal that AlDente has to keep running to limit charging. For now, you have to use other tools to hide the AlDente icon.

**Comment by Averiun** [comment]
> > Hi!
> > I have the M1 MacBook Pro
> 
> For M1 MacBooks it is normal that AlDente has to keep running to limit charging. For now, you have to use other tools to hide the AlDente icon.

Alrighty, thank you!
