### ISSUE TITLE
Bar icon showed up only. once

### ISSUE THREAD

**Issue by nocom** [davidwernhart/AlDente#128]
I have installed the app v.2 on 2016 MBP with the latest Big Sur update. The bar icon showed up only once and I also could set preferences (only max charge, no min charge showing). Since then I can run the app but nothing seems to happen. No idea what's hampering. Am running actual Cocktail once a week.

**Comment by TheMazus** [comment]
Hi @nocom,

you should give AlDente 2.1 - alpha a try. Maybe this release will fix your problem.

Best regards,
Matthias
