### ISSUE TITLE
Can someone explain this option

### ISSUE THREAD

**Issue by lixiao189** [davidwernhart/AlDente#129]
I'm a mac book pro 2020 (intel) user, 

![](https://i.loli.net/2021/02/21/LgHynr18hOFzwlM.png) 

So Do I need to click this option? Can some explain the function of it?

**Comment by TheMazus** [comment]
Hi lixiao189,
When you are on an Intel MacBook, you can choose between "normal" mode (which is activated by default) and "Use Classic SMC Key (Intel)" mode. When "Use Classic SMC Key (Intel)" mode is activated, you will lose the feature "Allow Discharge (Beta)". However, you gain the feature that AlDente will keep your battery at the desired percentage, even if your MacBook is turned off. On the other hand, when "Use Classic SMC Key (Intel)" mode is deactivated, you gain the feature "Allow Discharge (Beta)" but AlDente limits your charging only while your MacBook is running or on standby.

**Comment by lixiao189** [comment]
OK！Thank You, Sir!
