### ISSUE TITLE
v1.2 app damaged

### ISSUE THREAD

**Issue by Mr-iX** [davidwernhart/AlDente#13]
When I try to start the v1.2 app macOS says the app is damaged and cannot be started.
macOS 10.15.5
![Bildschirmfoto 2020-06-04 um 19 51 50](https://user-images.githubusercontent.com/25360303/83793467-dcef4a00-a69c-11ea-981f-4f41576880a3.png)

**Comment by davidwernhart** [comment]
Thank you! I am currently looking into this problem. I will update the release as soon as I find the solution.

**Comment by davidwernhart** [comment]
I updated the release. It did not work before because of a corrupted dmg-archive.
I hope it works fine now for you!

Best regards,
David
