### ISSUE TITLE
Icon not greyed out in menu

### ISSUE THREAD

**Issue by Itsmedwk** [davidwernhart/AlDente#1322]
**MacBook (please complete the following information):**
 - MacBook Model: MacBook Pro 14-inch 2021
 - macOS Version: Sequoia 15.0
 - AlDente Pro
 - AlDente Version: 1.28.2
 - External Monitor connected: Yes

**Describe the bug**
The AlDente symbol in the menu is not grayed out when the monitor is inactive.

**To Reproduce**
1. Click on second monitor.

**Expected Behavior**
It should be grayed out like the other icons.

**Screenshots and Screen Recordings**
![SCR-20240916-vka](https://github.com/user-attachments/assets/1d13e282-6629-422d-a907-143029715de3)

**Comment by MatthiasKerbl** [comment]
Hi @Itsmedwk,

Thank you for this bug report. We are aware of this issue and have tried to fix it already. Unfortunately, this is a bug of macOS Sequoia, and we have already filed a bug report at Apple since it is not only a problem of AlDente but most Menubar apps that use a different framework to also display more complex data in the Menubar.
We hope Apple will fix it soon and will communicate updates here.

Best,
Matthias

**Comment by andrewcrook** [comment]
Yes I have this issue on dual monitors where the screen not in focus the icon fails to dim like the others.

**Comment by cprcrack** [comment]
<img width="645" alt="Screenshot 2024-09-26 at 11 45 30" src="https://github.com/user-attachments/assets/795774ed-5f74-4734-bb9b-4a7219aeecf6">

Same issue, it's the only menu bar icon in my case that it's not greyed out on inactive screens, so it stands out quite a bit.

@MatthiasKerbl is there a link to the bug report you filed at Apple that we can track? Was there any update by Apple?

**Comment by cprcrack** [comment]
As a workaround, couldn't you use the "not different framework" that works correctly when the user just uses the regular default icon that most of us have?

**Comment by vcekron** [comment]
This issue was addressed in [1.28.5](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/releases/tag/1.28.5)! 🥳

**Comment by andrewcrook** [comment]
@Itsmedwk could you check and close?

**Comment by emanuelst** [comment]
<img width="120" height="29" alt="Image" src="https://github.com/user-attachments/assets/aa59c133-8977-4ff8-b316-e3d345ba4e5c" />

There might be a regression in macOS 27.0 Beta (26A5388g) / AlDente 1.38.1 and 1.39 beta 2: the AlDente menu-bar icon stands out on an unfocused monitor. Maybe worth investigating? Also possibly related: https://github.com/AppHouseKitchen/AlDente-Battery_Care_and_Monitoring/issues/1794
Thanks!
