### ISSUE TITLE
App compatibility with Mac OS Mojave

### ISSUE THREAD

**Issue by yiqiangjizhang** [davidwernhart/AlDente#139]
Hi! This app is what I was searching for years! And I finally saw it, however, I am using a Macbook Pro 2017 with Mojave and I don´t want to upgrade to Big Sur since there was a ton of problems. I wanted to ask if the developers will make a version compatible with Mojave or Catalina.

Thank you all! I will definitely buy the pro version if they make it compatible with Mojave!

**Comment by svintuss** [comment]
You could just download v1.2, it works under Catalina. 

However Mojave support would be nice too (pre-2013 systems won't go higher than 10.14).

**Comment by yiqiangjizhang** [comment]
I´ll just upgrade to Catalina then just for this App! Jajajaajja cause I love the idea!
