### ISSUE TITLE
2020 MacBook Pro 13" results

### ISSUE THREAD

**Issue by peterlewis** [davidwernhart/AlDente#14]
Just for your information, I've got a 2020 MacBook Pro 13" (A2251) and I've been using AlDente on it for the past day or so.

I've found that it appears to work as intended (obviously taking into account the disclaimer in your README) and, when setting the max charge to 50%, the device stops charging at 51%.

I'm unsure of whether this is enough 'testing' for you to consider adding it to the README, but I wanted to let you know my results!

**Comment by davidwernhart** [comment]
Hi @peterlewis!
Thank you for this information. I will add the new MacBook Pro to the readme.
Also, in the newest [release](https://github.com/davidwernhart/AlDente/releases), the max charge should now be the same as the one displayed in MacOS (at least in the common 80% range).

Best regards,
David
