### ISSUE TITLE
Just adjusted Al Dente to charge to 100% but no go

### ISSUE THREAD

**Issue by Limeybastid** [davidwernhart/AlDente#141]
I changed setting from 59% to 100%, unplugged and replugged power back, but it won't charge to 100% . Any ideas? I was attempting to quit app and its settings prior to upgrading to Big Sur 12.2.2 on the M1. cheers

EDIT after removing usb c and doing it the third time it engaged and is charging. no worries

**Comment by TheMazus** [comment]
Hi @Limeybastid,
I am glad it worked now. Sometimes it takes up to a couple of minutes for changes to take place.
