### ISSUE TITLE
Thank you for creating this! And feature request

### ISSUE THREAD

**Issue by danfoerster** [davidwernhart/AlDente#148]
First of all. Thank you for creating this little tool. I am running a Late 2013 15" Retina MacBook Pro and it runs fine.

I recently had to install a new battery into it which I like to keep healthy for as long as I can. Since my MacBook is plugged in most of the time, and the battery health feature is not available on older machines, this is a great addition and I look forward to any new versions of it to see what else you guys can introduce, feature-wise. Although it does what is is supposed to already.

I miss a few features that would be great to have.
- A 'Fully charge now' button.
- Scheduled charging (So the computer is charged to 100% the next morning if one wants a full charge)
- I also think the menu panel could be refined a little bit

I do have my max percentage set to 81% which according to the built-in monitor is 85%. But like you said, it's only somewhat accurate. But looking at the actual percentage (from coconut battery) which is more accurate, the 81% of AlDente is basically spot on with coconut battery showing 80,8%.
The reason for this, and you surely know this, macOS and all other OS by apple use a very defensive monitoring. Meaning, the value the stock menu bar icon show is never truly right. Just like, my Mac and iPhone and iPad will show 100% even though the percentage already is a lot lower. Usually at around 95% it will start to drop and then it gets closer and closer the lower the percentage drops. In order to make this accurate (as most users would probably prefer the AlDente value to be aligned with Apple's defensive value, you have to target the more inaccurate value, instead of the exact value (the actual percentage, for example coconut battery shows). I don't know if that is possible.

I included some pictures. Maybe its a little inspiration to you. Keep up the great work. God bless for making a tool to do this on my 'old' machine. Kind regards from Austria.

<img width="352" alt="Screen Shot 2021-02-28 at 15 06 51" src="https://user-images.githubusercontent.com/79795921/109421197-a13ca300-79d6-11eb-86f3-90b17f227fb7.png">

![pic1](https://user-images.githubusercontent.com/79795921/109424245-347bd580-79e3-11eb-9916-3752c0e6deca.jpg)

![pic2](https://user-images.githubusercontent.com/79795921/109424247-35146c00-79e3-11eb-81ae-0589c4fbfc5e.jpg)

**Comment by MatthiasKerbl** [comment]
Hallo @danfoerster,

ich wollte mich bei Dir für deine Hilfe hier im Github Forum bedanken und wollte dir anbieten, dass du ein AlDente Pro Beta Tester wirst. Leider habe ich dann gesehen, dass Du ein 2013er MacBook verwendest, welches von AlDente Pro leider nicht unterstützt wird. Hast du noch ein neueres MacBook und Interesse AlDente Pro Beta zu testen?

Freundliche Grüße,

Matthias
