### ISSUE TITLE
strange switch-on and shut-down on MBP retina 15-inch, mid 2014 (AlDente v2.0-alpha)

### ISSUE THREAD

**Issue by andreafurla** [davidwernhart/AlDente#153]
Hi there,
when switch-on my Mac, after login and when it finish to load all, the Mac goes into standby.
When shut-down it has an error, and restart itself immediately.

These behaviors happen at first time.
At second time all it's OK.

**Comment by TheMazus** [comment]
Hi @andreafurla,
you should install our latest version 2.1-alpha. Maybe this will solve your issues.
Best regards,
Matthias

**Comment by andreafurla** [comment]
Hi @TheMazus ,
Have I to uninstall v2.0? or simply download and install the last version?
Thank you

**Comment by TheMazus** [comment]
You can just install the new version.

**Comment by andreafurla** [comment]
Hi @TheMazus ,
yesterday evening I switched-off my MAC, and it rebooted by itself.
After this the system show me a box with many error codes.

Can I share them with you privately?

**Comment by TheMazus** [comment]
Sure you can send me the error codes.

**Comment by andreafurla** [comment]
Can you give me your email address?
