### ISSUE TITLE
Did not work on macOS 11.2.2 and MacBook Pro (13-inch, 2020, Two Thunderbolt 3 ports Intel CPU)  

### ISSUE THREAD

**Issue by 42vio** [davidwernhart/AlDente#155]
I have restarted the AlDente2.1 and the Mac. I tried many times but it didn't work.

**Comment by aktivde** [comment]
To completely reinstall worked in my case.

**Comment by Tioz90** [comment]
Same issue here.  How would we completely reinstall?  The script that was posted does not work with 11.2.2

**Comment by gordio** [comment]
@Tioz90  http://freemacsoft.net/appcleaner/ can help you.

**Comment by BigMcGuire** [comment]
Yeah I use app cleaner and I had to completely reinstall for it to work too - initially it didn't when I upgraded.

**Comment by MatthiasKerbl** [comment]
Hi @42vio,

does AlDente work again on your MacBook?
