### ISSUE TITLE
Allow discharge: External monitor doesn't work when MacBook is closed

### ISSUE THREAD

**Issue by aktivde** [davidwernhart/AlDente#157]
I just experienced an expectable bug: When having "allow discharge" enabled, an external monitor won't work when the Macbook is closed. Probably because the Macbook thinks not to be charged which generally prevents an external monitor to work if the Macbook is closed. 

No idea, if that's easy to fix or one needs to live with it. Just wanted to mention the issue.

**Comment by vividfog** [comment]
#114 

Known issue. The download page mentions this, but the app itself doesn't. I also filed this once.

**Comment by TheMazus** [comment]
Hi @aktivde,
as @vividfog already pointed out, this is a known problem and we are not sure if we can do anything about it.
We will definitely include a warning in the app in a future update.
