### ISSUE TITLE
[Question] How this works on M1?

### ISSUE THREAD

**Issue by Bambus89** [davidwernhart/AlDente#167]
Hello there,

How does this work on Apple M1 machines when they have no SMC?

**Comment by TheMazus** [comment]
Hi @Bambus89,
Apple Silicon MacBooks have an SMC too.

**Comment by Bambus89** [comment]
But is there a way to reset smc like on intel?

**Comment by TheMazus** [comment]
Yes, you just have to shut down the MacBook and close the lid for about 30 seconds.

**Comment by Bambus89** [comment]
Thanks... Great App BTW 😉

**Comment by TheMazus** [comment]
You're welcome and I'm glad you like it. :)
