### ISSUE TITLE
After quitting AlDente, it won't charge up to 100%

### ISSUE THREAD

**Issue by shinokada** [davidwernhart/AlDente#174]
After quitting AlDente, the percentage won't reach 100%.
Shouldn't it set to 100% when you quit it or uninstalling it?

**Comment by Archer785** [comment]
You have to set it to 100% manually before uninstalling

**Comment by TheMazus** [comment]
> After quitting AlDente, the percentage won't reach 100%.
> Shouldn't it set to 100% when you quit it or uninstalling it?

Hi @shinokada,
if you are in the "Use Classic SMC Key" mode, you should definitely set it to 100% before quitting AlDente.

Matthias

**Comment by TheMazus** [comment]
> After quitting AlDente, the percentage won't reach 100%.
> Shouldn't it set to 100% when you quit it or uninstalling it?

Do you still have this issue?
