### ISSUE TITLE
Al Dente is reported as malware by macOS 11.2.3

### ISSUE THREAD

**Issue by Averiun** [davidwernhart/AlDente#178]
<img width="1680" alt="Screenshot 2021-03-10 at  1 50 52" src="https://user-images.githubusercontent.com/36973620/110632566-10b94c00-81a8-11eb-9381-d7bf928a7fbc.png">

**Comment by qfettes** [comment]
Same here. I can no longer open the app.

**Comment by BigMcGuire** [comment]
On Macrumors we have some Silicon Mac users wondering how to reset the % now that they can't run AlDente anymore. No SMC reset like Intel Macs. Anyone know?

**Comment by srbNYC** [comment]
I checked "disable malware protection," but it still says I do not have permission to open the app. Afraid my battery will be stuck at 63%!

**Comment by hzozo** [comment]
Same here, I've just rebooted my MacBook this afternoon and faced the same thing. I've even overridden malware protection and removed the quarantine bit but that doesn't help.
I also share @BigMcGuire's concern, I'm just testing if my battery charges now to 100 or 73%.

**Comment by Matt-136** [comment]
I was able to charge the battery to 100% but now it stays at 100 all the time

**Comment by tomato990** [comment]
Same here. Big sur for macbook 2015.

**Comment by Matt-136** [comment]
Coconut Battery is showing the right percentage (96%) but in the menu bar it stays at 100%

**Comment by eltonooi** [comment]
Same here after restart my M1 Mac Air, Big Sur 11.2.1

**Comment by davidwernhart** [comment]
Hey guys! Sorry for the inconveniences.
This problem seems to occur because my developer certificate has expired today.
I will update a freshly signed version soon.
David

**Comment by srbNYC** [comment]
Relatively new to AlDente. Very impressed with your timely response and solve! Thank you!

**Comment by TheMazus** [comment]
Hi guys,

The freshly signed version of AlDente was just released.
https://github.com/davidwernhart/AlDente/releases

Best regards,
Matthias

**Comment by eltonooi** [comment]
> Hi guys,
> 
> The freshly signed version of AlDente was just released.
> https://github.com/davidwernhart/AlDente/releases
> 
> Best regards,
> Matthias

<img width="345" alt="image" src="https://user-images.githubusercontent.com/71483123/110686423-60d0f680-821a-11eb-96d9-8a5a51be0d4d.png">
Hi, the apps can run now but this is the new warning

**Comment by TheMazus** [comment]
> > Hi guys,
> > The freshly signed version of AlDente was just released.
> > https://github.com/davidwernhart/AlDente/releases
> > Best regards,
> > Matthias
> 
> <img alt="image" width="345" src="https://user-images.githubusercontent.com/71483123/110686423-60d0f680-821a-11eb-96d9-8a5a51be0d4d.png">
> 
> Hi, the apps can run now but this is the new warning

Hi @eltonooi,
this is due to the old helper, which was signed with the expired developer certificate.
You just have to install the new version which should delete the old helpers and install the new ones. However, sometimes this won't work and you have to delete the old helpers manually as described in the release notes.
