### ISSUE TITLE
Latest Big Sur issues 

### ISSUE THREAD

**Issue by Limeybastid** [davidwernhart/AlDente#182]
I’m not sure if it’s related to Al Dente but I did quit the app but alas not properly and update on my M1 failed just now. 
just to clarify , I used the slider to set battery to 100%, then quit app. Then closed lid of MacBook then opened lid.  Done this while update was downloading and not installing. 
![78AC5C33-1003-4F4C-84A2-576D7FB7F979](https://user-images.githubusercontent.com/79114686/110687673-c6879900-81ae-11eb-8de6-bd4cdc7c4905.jpeg)

**Comment by TheMazus** [comment]
Hi @Limeybastid,
I don't know either if AlDente has anything to do with your issue. However, if you want to deinstall AlDente completely you have to follow these steps: Set Max Battery Charge to 100% and wait 30 seconds, quit the app, delete the app file, turn off your MacBook and close the lid for at least 30 seconds, restart. Afterward, AlDente is completely removed and should not interfere with anything else.

**Comment by Limeybastid** [comment]
Thanks for the clarification. 
On the recovery screen, I simply restarted and it all worked. Meaning I didn't have to restore Big Sur all over. But upon boot up I was getting pop up about Al Dente which has been discussed here and resolved in the latest update .
Thanks.

**Comment by TheMazus** [comment]
I am glad you could solve your issue and the new AlDente is working fine. :)
