### ISSUE TITLE
New version needs to be running to take effect - clarification?

### ISSUE THREAD

**Issue by zhouyifan0904** [davidwernhart/AlDente#189]
In the previous version (as well as "classic SMC key" mode,) the app does what is said in README - we can write the number to SMC once, exit and never open the app again for it to continue to work. The new version requires that we keep AlDente running at all times if my observations are correct. Perhaps this distinction needs to be made clear in README?

**Comment by TheMazus** [comment]
Hi @zhouyifan0904,
when you use AlDente in "Use Classic SMC Key (Intel)", you can just set the desired battery percentage wait about 30 seconds, and close the app. In the "normal mode", however, AlDente needs to be running to work. I will update our README and clarify the differences.
