### ISSUE TITLE
Charge limit ineffective after Big Sur 11.2.3 update

### ISSUE THREAD

**Issue by maiksd** [davidwernhart/AlDente#190]
Hi, my MBP 15" 2018 is charging beyond the limit set in AlDente 2.1.2. Behaviour is somewhat inconsistent: if I set the limit again in AlDente, sometimes it stops charging, sometimes it continues nevertheless. Up to Big Sur 11.2.2 this didn't happen.

**Comment by TheMazus** [comment]
Hi @maiksd,
try quitting AlDente, restart your MacBook, and start AlDente again. This did it for most people.

**Comment by maiksd** [comment]
Did it, didn't fix it.

**Comment by TheMazus** [comment]
Have you tried the "Use Classic SMC Key (Intel)" feature?

**Comment by maiksd** [comment]
Trying that since 3 days ago, seems better!
