### ISSUE TITLE
Consider removing the popover animation?

### ISSUE THREAD

**Issue by sakesalverda** [davidwernhart/AlDente#192]
Hi, I noticed the AlDente popover uses an animation when opened. Perhaps it can be disabled to bring it more in line with other apps/the system. I believe this can be easily done by setting the popover animates property
And thanks for the project, really enjoying the app!!

**Comment by TheMazus** [comment]
Hi @sakesalverda,
I am glad you like our app. Maybe we will give the functionality to deactivate the animation.

Matthias

**Comment by MatthiasKerbl** [comment]
Hi @sakesalverda,

We just released a new version of AlDente in which we disabled the popover animation.
You can download the new version here: https://github.com/davidwernhart/AlDente/releases

Kind regards,
Matthias

**Comment by sakesalverda** [comment]
Hi @MatthiasKerbl thank you for keeping me up to date, appreciate that! And again, thank you for the awesome app! Still using it everyday

**Comment by MatthiasKerbl** [comment]
> Hi @MatthiasKerbl thank you for keeping me up to date, appreciate that! And again, thank you for the awesome app! Still using it everyday

I am glad you still like it. If you have more ideas let us know and if you have not heard about our Pro version yet, you can check it out on our website: https://apphousekitchen.com/
