### ISSUE TITLE
AlDente 2.1.2 Eats up Processing power and cause MacBook IR to run hot

### ISSUE THREAD

**Issue by SunDiego1** [davidwernhart/AlDente#196]
After installing and using AlDente 2.1.2, my 2020 MacBook Air's fan has been running quite a bit, after bringing up Activity Monitor, I notices AlDente was at the top of the list, I went back to AlDente 1.2 and found that fixed the issue.

**Comment by TheMazus** [comment]
Hi @SunDiego1,
we are aware of this issue and are working on it. A quick workaround would be to reopen the app. This resets the CPU load and it takes a couple of days to increase again.

Matthias
