### ISSUE TITLE
Asks for Admin Password  to install the helper program after each RESTART!! Can't install it.

### ISSUE THREAD

**Issue by artinalbert** [davidwernhart/AlDente#205]
11.2.3 Big Sur
2.1.2 AlDente

**Comment by MatthiasKerbl** [comment]
Hi @artinalbert,
please try the following steps:

1. Quit AlDente and delete the program file.
2. Go in Finder to Macintosh HD/Library/LaunchDaemons and delete “com.davidwernhart.Helper.plist”. 
3. Go to Macintosh HD/Library/PrivilegedHelperTools and delete “com.davidwernhart.Helper”.
4. Restart your MacBook.
5. Download and install AlDente again.
6. Restart your MacBook again.

Hope this helps,
Matthias

**Comment by aniuwoo** [comment]
> Hi @artinalbert,
> please try the following steps:
> 
>     1. Quit AlDente and delete the program file.
> 
>     2. Go in Finder to Macintosh HD/Library/LaunchDaemons and delete “com.davidwernhart.Helper.plist”.
> 
>     3. Go to Macintosh HD/Library/PrivilegedHelperTools and delete “com.davidwernhart.Helper”.
> 
>     4. Restart your MacBook.
> 
>     5. Download and install AlDente again.
> 
>     6. Restart your MacBook again.
> 
> 
> Hope this helps,
> Matthias

Follow the steps every time for several times, the problem is still there. No Helper V.12 found. 11.2.2 Big Sur, M1 MBP

**Comment by artinalbert** [comment]
I followed suit as well. Same issue persists.  

> Hi @artinalbert,
> please try the following steps:
> 
> 1. Quit AlDente and delete the program file.
> 2. Go in Finder to Macintosh HD/Library/LaunchDaemons and delete “com.davidwernhart.Helper.plist”.
> 3. Go to Macintosh HD/Library/PrivilegedHelperTools and delete “com.davidwernhart.Helper”.
> 4. Restart your MacBook.
> 5. Download and install AlDente again.
> 6. Restart your MacBook again.

**Comment by longalong** [comment]
I followed suit as well. Same issue persists.，No Helper V.12 found. 11.2.2 Big Sur, M1 MBP

**Comment by FT180222** [comment]
sudo launchctl load -w /Library/LaunchDaemons/com.davidwernhart.Helper.plist 终端输入这个完美解决。
![image](https://user-images.githubusercontent.com/82929552/116952209-ac54cd80-acbc-11eb-9dcc-7b2d3c747eca.png)

**Comment by martindon6** [comment]
I has the 2019 macbook pro intel version, I tried your method but I still cannot instal the helper V12.

<img width="459" alt="截屏2021-05-04 13 30 03" src="https://user-images.githubusercontent.com/50022840/116964235-9a375700-acdd-11eb-805f-eb402cd3ddcb.png">

**Comment by FT180222** [comment]
你试试把第二行打勾，我的是m1。

**Comment by eflylab** [comment]
sudo launchctl load -w /Library/LaunchDaemons/com.davidwernhart.Helper.plist

**Comment by FT180222** [comment]
电脑上的终端输入 命令

**Comment by MatthiasKerbl** [comment]
Hi everyone,

We just released a new version of AlDente which should solve the problems you encountered.
You can download the new version here: https://github.com/davidwernhart/AlDente/releases
Sorry, it took so long but I hope you like the new version.

Kind regards,

Matthias
