### ISSUE TITLE
Max Battery Charge resets to 3% automatically on Mac with M1

### ISSUE THREAD

**Issue by Kundan-K-Singh** [davidwernhart/AlDente#208]
Max battery charge resets itself to 3% automatically  as shown in video. However, the battery charges upto 100%. If I reinstall helper then I can change battery percentage. However, if laptop is restarted, it again starts getting reset at 3%. Even after reinstalling helper, although I can change the max battery percentage but it does not work and battery charges to 100%.
Overall it is not working at all on my macbook.

https://user-images.githubusercontent.com/14230004/111823081-85a82680-890a-11eb-8f0d-a8d8dbfa446d.mp4

Details:
Macbook Pro with M1 processor. 
OS version: 11.2.2

**Comment by MatthiasKerbl** [comment]
Hi @Kundan-K-Singh,
you downloaded an outdated version of AlDente.
You need to download the newest one.

**Comment by Kundan-K-Singh** [comment]
My bad. Closing the issue.
