### ISSUE TITLE
~Feature Request

### ISSUE THREAD

**Issue by Reload217** [davidwernhart/AlDente#210]
I would be very grateful if there would be an option to add support for the mojave system, as AlDente is very functional.

thank you in advance. Cheers :D

**Comment by MatthiasKerbl** [comment]
Hi @Reload217,
Unfortunately, AlDente is not compatible with Mojave because of the incompatibility of SwiftUI with Mojave :/. Therefore, you would have to update to Catalina to use AlDente.

Matthias

**Comment by Reload217** [comment]
I have a question does it work on Macbook Air 7.1 2011 models?

**Comment by MatthiasKerbl** [comment]
Unfortunately, the newest version of AlDente is not Supported on a 2011 MacBook Air. However, you could try AlDente 1.2. This older version of AlDente might work.
