### ISSUE TITLE
Allow discharge --> connection to Monitor is interrupted. 

### ISSUE THREAD

**Issue by eliah22** [davidwernhart/AlDente#218]
Hello first of all thanks for this wonderful tool. To my issue I connected my Macbook pro m1 to an LG monitor. When I click on allow discharge, the connection to the mac book pro m1 and the Monitor is disabled and it says No connection.  I use a usb c cable to connect.

**Comment by patryk-jason** [comment]
> Experimental option to automatically discharge to desired percentage when plugged in. (Does not work in clamshell mode!)

Is your Macbook opened or closed while it happens?

**Comment by eliah22** [comment]
Hey Patryk-Jason, thank you for the reply my Mac book is closed.

**Comment by MatthiasKerbl** [comment]
Hi @patryk-jason,
Allow Discharge is not supported while your MacBook is in clamshell mode. Hence, it's only a "Beta" feature. However, you can just deactivate Allow Discharge and use Aldente even in clamshell mode.

Matthias
