### ISSUE TITLE
High CPU usage / memory leak?

### ISSUE THREAD

**Issue by aleeraser** [davidwernhart/AlDente#225]
In the last 4-5 days I left my macbook constantly on for some time-intensive tests for a project (i.e. no idle/clamshell sleep).

I noticed already 3 times that after a while (can't tell exactly when) Aldente UI starts acting very slow and the CPU usage is high, too much much for a charge limiter application. All the times I had to quit and restart the app.

Here's a screenshot of Activity Monitor.

<img width="941" alt="aldente" src="https://user-images.githubusercontent.com/10846607/112756699-bb25d180-8fe6-11eb-894c-e2e3c7f147b9.png">

Here are my settings:

<img width="472" alt="aldente-settings" src="https://user-images.githubusercontent.com/10846607/112756754-e4466200-8fe6-11eb-8c2e-c21557a5b73e.png">

p.s. if the app is closed, does the limit keep working?

**Comment by MatthiasKerbl** [comment]
Hi @aleeraser,

this was a known bug of the older AlDente versions. Just install our newest version and this issue will be gone.

**Comment by aleeraser** [comment]
Thanks @MatthiasKerbl,
I didn't know there was a newer version!
Nice that the new version also has a check for updates.

Thanks
