### ISSUE TITLE
Using "able to discharge" behavior

### ISSUE THREAD

**Issue by tosbsas** [davidwernhart/AlDente#226]
Hi

I understood than when using allow discharge, if I turn the MBP completely off, battery will charge to 100% anyway.

But
During the day I get several "connect" "disconnect" sounds, and battery goes below 80% to be recharged to 80% (my threshold). Is that normal?

**Comment by danfoerster** [comment]
The allow discharge feature does one thing only. If your Mac is connected to power and the battery is higher than the value you set in AlDente, it will discharge to this value. I don't know how it works if the Mac is turned off. However if your Mac is running and you have the Optimized Battery Charging setting enabled in macOS settings, the two things might conflict with each other, meaning one might want to charge and the other discharges as soon as one recent is gained. I think you might have to turn of the Battery Managing feature in macOS Battery settings. Give it a try

**Comment by tosbsas** [comment]
The optimize battery feature is disabled. My guess is that the allow to discharge feature checks once in a while if the percentage threshold is reached and turns power on or off. But its happening more often here than on 2.1.2

**Comment by MatthiasKerbl** [comment]
> Hi
> 
> I understood than when using allow discharge, if I turn the MBP completely off, battery will charge to 100% anyway.
> 
> But
> During the day I get several "connect" "disconnect" sounds, and battery goes below 80% to be recharged to 80% (my threshold). Is that normal?

Hi @tosbsas,
this is currently the "normal" behavior of Allow Discharge. However, we are working on improving this in an future update.

**Comment by tosbsas** [comment]
ok, you referring to both of my observations, right?

**Comment by MatthiasKerbl** [comment]
> ok, you referring to both of my observations, right?

Yes

**Comment by tosbsas** [comment]
thanks :-))
