### ISSUE TITLE
13-inch 2020 4x TB ports Big Sur 11.2.3 on USB-C dock charging to full after a while

### ISSUE THREAD

**Issue by markouustalu** [davidwernhart/AlDente#228]
It works on my other older laptop flawlessly. But not in my newer laptop. I install it and set it to 60%. At home it manages to keep it nicely on 60%. I think closing the lid and letting it go to standby ruins it after a while. But it is manageable.

At my work i have USB-C Dock. I set it to 60%, it shows that it is working on battery. Music is playing all the time so no standby issues. After a while it is charging again and battery is full as shown on the image.
![Screenshot 2021-04-01 at 21 40 43](https://user-images.githubusercontent.com/49148843/113339425-1af7e180-9333-11eb-8e61-2ad3c6676194.png)

Tried restarts and re-installs, nothing seems to help.

How can i help to solve this?

**Comment by bruno-briner** [comment]
It was also happening with my MacBook Pro 13" late 2017 4 TB ports. I could only make it work reliably by selecting "Use Classic SMC Key (Intel)".

**Comment by MatthiasKerbl** [comment]
> It works on my other older laptop flawlessly. But not in my newer laptop. I install it and set it to 60%. At home it manages to keep it nicely on 60%. I think closing the lid and letting it go to standby ruins it after a while. But it is manageable.
> 
> At my work i have USB-C Dock. I set it to 60%, it shows that it is working on battery. Music is playing all the time so no standby issues. After a while it is charging again and battery is full as shown on the image.
> ![Screenshot 2021-04-01 at 21 40 43](https://user-images.githubusercontent.com/49148843/113339425-1af7e180-9333-11eb-8e61-2ad3c6676194.png)
> 
> Tried restarts and re-installs, nothing seems to help.
> 
> How can i help to solve this?

Hi @markouustalu,
have you tried it with "Allow Discharge" Disabled?

**Comment by markouustalu** [comment]
Removed Allow Discharge. Still charging.
![Screenshot 2021-04-06 at 13 31 25](https://user-images.githubusercontent.com/49148843/113698712-67e60a00-96dd-11eb-91ae-7e446a632444.png)
Tried Classic SMC key. Still Charging.
![Screenshot 2021-04-06 at 13 38 20](https://user-images.githubusercontent.com/49148843/113698794-7c2a0700-96dd-11eb-9654-2af250ffe19d.png)

**Comment by markouustalu** [comment]
after restarting the app i left the checkpoints checked as in my first post. It discharged my battery to about 90% and now it is charging again, no stand by's or lid closings in the mean time.

**Comment by markouustalu** [comment]
guys, after multiple app and mac restarts and using the Classic SMC key it seems to have stopped charging at the set level. It seems pretty fragile but it seems to be working. If there are no more questions then this issue can be closed. If still needed, i would be more than happy to provide some debugging info to make this cool app as solid as a rock.

**Comment by MatthiasKerbl** [comment]
Hi @markouustalu,

We just released a new version of AlDente which should make AlDente much more relyable.
You can download the new version here: https://github.com/davidwernhart/AlDente/releases

Kind regards,
Matthias
