### ISSUE TITLE
It is not working on MacBook Air M1

### ISSUE THREAD

**Issue by rharangozo** [davidwernhart/AlDente#236]
AlDente keeps asking my password to start helper but even after that, it does not work as expected. Sometimes, the slider jumps back to 0. If i reinstall helper, i can set the desired percentage but it just simply does not work. 
If I run it with Rosetta 2, it works fine!

Hardware: Apple MacBook Air M1
OS: 11.2.3 (20D91)
AlDente: Version 2.2

**Comment by Dhudong** [comment]
Same exact issue for me! How did you get to run it with Rosetta 2?

**Comment by rharangozo** [comment]
> Same exact issue for me! How did you get to run it with Rosetta 2?

Navigate to /Applications in Finder, right click on AlDente, select 'Get Info' and check 'Open using Rosetta'

**Comment by Dhudong** [comment]
> > Same exact issue for me! How did you get to run it with Rosetta 2?
> 
> Navigate to /Applications in Finder, right click on AlDente, select 'Get Info' and check 'Open using Rosetta'

Thanks man! Did that and it's working now. Hope this issue will be resolved soon. Thanks again.

**Comment by rharangozo** [comment]
Now i have a more experience with AlDente on MacBook Air M1. Even if i run it with rosetta, it silently stops working, probably the helper crashes. If i reinstall it, sometimes it starts working again. Sometimes, i need to reboot. Unfortunately, it's unreliable.

**Comment by AlfaMoski** [comment]
I am getting 
<img width="453" alt="Screenshot 2021-04-27 at 22 10 22" src="https://user-images.githubusercontent.com/14765428/116307232-5789f200-a7a6-11eb-9216-14e3a8f43a04.png">
 message “com.davidwernhart.Helper” will damage your computer."

**Comment by MatthiasKerbl** [comment]
Hi everyone,

We just released a new version of AlDente which should solve the problem you encountered.
You can download the new version here: https://github.com/davidwernhart/AlDente/releases
Sorry, it took so long but I hope you like the new version.

Kind regards,

Matthias
