### ISSUE TITLE
macOS Big Sur (11.2.2) flags Al Dente for damaging the computer.

### ISSUE THREAD

**Issue by perteraul** [davidwernhart/AlDente#237]
![2E11B4C4-CE3B-4B57-8DD1-CF561B870903](https://user-images.githubusercontent.com/7403338/113584081-21d46c00-9633-11eb-900a-5a8227a02641.jpeg)

Specs: 13" MacBook Pro (M1, base model)
It was running just fine until the 11.2.2 update.

**Comment by MatthiasKerbl** [comment]
Hi @perteraul,
this is due to an expired developer account. Just download the newest version of AlDente and this issue will be gone.

**Comment by perteraul** [comment]
Awesome, just did that and it went away. Thanks for the software!
