### ISSUE TITLE
Not working on my M1 MacBook Air

### ISSUE THREAD

**Issue by Dhudong** [davidwernhart/AlDente#238]
The  slider/set max. charge value keeps sliding back to zero. After reinstalling helper, it would let me set the max charge level but it will still charge up to 100%. I've tried restarting and all but still not working. I really like this app. Hope it gets fixed soon. I'm using the latest 2.2 version.

**Comment by rharangozo** [comment]
it has already been reported: https://github.com/davidwernhart/AlDente/issues/236

**Comment by Dhudong** [comment]
> it has already been reported: #236

Yeah I just saw the report. Thanks.
