### ISSUE TITLE
Charged past limit

### ISSUE THREAD

**Issue by exiva** [davidwernhart/AlDente#24]
I installed AlDente on my MacBook Pro (Retina, 13-inch, Early 2015) Running 10.15.5, Set the max to 80%, and discharged the battery to 50%. Plugged it in, and it charged back up to 100% despite the 80% limit. Do you need to reboot or something after the change is set? Is there a way to verify the new limit got set with a command or something?

Love the idea of the app, especially since the native Apple one is disabled on machines that would actually benefit from it. Hopefully can get this working. Thanks!

<img width="425" alt="Screen Shot 2020-06-19 at 2 56 11 PM" src="https://user-images.githubusercontent.com/56931/85171471-15fef100-b23d-11ea-8d2d-c26707c14ab1.png">
<img width="318" alt="Screen Shot 2020-06-19 at 2 56 19 PM" src="https://user-images.githubusercontent.com/56931/85171484-1c8d6880-b23d-11ea-8ccb-17a3802b2361.png">

**Comment by DevNulPavel** [comment]
Has charge limit value been saved after your macbook reboot?

**Comment by zackelia** [comment]
@exiva I have the exact same MacBook as you, so it should work. I couldn't find an easy way to read the max battery charge level from the terminal so I put together some swift code that you can quickly compile and run to verify. It uses the same SMC.swift from the helper tool appended with a few lines to read the BCLM value. I posted the code in a gist [here](https://gist.github.com/zackelia/c10222c9a79dc3228a1bd9cf067d4079).

```
$ swiftc read-bclm.swift
$ ./read-bclm 
77
```

**Comment by exiva** [comment]
@zackelia Hmm. That came back as 100, and any time I change the value in aldente it stays at 100. 🤔 Let me try a reboot and see what happens.

**Comment by DevNulPavel** [comment]
https://github.com/sicreative/BatteryStatusShow

Maybe this application will work and change BCLM value.

**Comment by exiva** [comment]
Ok, I rebooted and it reset back to 100 in aldente. Now changing it in aldente is being reflected in the check app @zackelia posted. I guess a reboot is required before it is able to modify the SMC params. Going to discharge my battery some and see what happens.

**Comment by exiva** [comment]
Rebooting after installing did the trick. Thanks again for the help.
