### ISSUE TITLE
USB-C monitor video signal issue

### ISSUE THREAD

**Issue by vegavnil** [davidwernhart/AlDente#244]
If I have 100% charge on my Mac and set the battery to "Allow Discharge" down to 70% and stay there through AlDente, my monitor doesn't seem to be able to show a video signal if my mac is sitting with the lid closed on my desk, maybe since it needs power to be drawn through the USB-C cable to be able to do so, I don't know, it works fine with "Allow Discharge" turned off. It's able to do so with "Allow Discharge" turned on if the laptop sits with the lid opened up on my desk though. Strange.

MacBook Pro M1 on a BenQ PD2710QC.

**Comment by MatthiasKerbl** [comment]
Hi @vegavnil,
as described in our README, clamshell mode is not supported by the feature "Allow Discharge" due to technical limitations. However, as you described you can either use your MacBook with the lid open and "Allow Discharge" enabled or with the lid closed and "Allow Discharge" disabled.
