### ISSUE TITLE
Helper file considered dangerous

### ISSUE THREAD

**Issue by nocom** [davidwernhart/AlDente#247]
MBP 2016 15" Big Sur
I. get a warning immediately after installing that the. helper file. can damage my comput
<img width="472" alt="Bildschirmfoto 2021-04-13 um 07 23 54" src="https://user-images.githubusercontent.com/9048305/114502378-fb629200-9c2b-11eb-941a-a07f475ff58b.png">

**Comment by iphoneio** [comment]
Same Here.
Apple say ""com.davidwernhart.Helper" will damage your computer.
Report malware to Apple to protect other users"😢
MacBook Pro (M1, 13-inch, 2020) macOS 11.2 Big Sur

![AlDente](https://user-images.githubusercontent.com/9293598/114505396-48198d80-9c6b-11eb-90f7-2709edbf8374.jpg)

**Comment by MatthiasKerbl** [comment]
> MBP 2016 15" Big Sur
> I. get a warning immediately after installing that the. helper file. can damage my comput
> <img alt="Bildschirmfoto 2021-04-13 um 07 23 54" width="472" src="https://user-images.githubusercontent.com/9048305/114502378-fb629200-9c2b-11eb-941a-a07f475ff58b.png">

Hi @nocom,
Which version of AlDente do you use?

**Comment by MatthiasKerbl** [comment]
> Same Here.
> Apple say ""com.davidwernhart.Helper" will damage your computer.
> Report malware to Apple to protect other users"😢
> MacBook Pro (M1, 13-inch, 2020) macOS 11.2 Big Sur
> 
> ![AlDente](https://user-images.githubusercontent.com/9293598/114505396-48198d80-9c6b-11eb-90f7-2709edbf8374.jpg)

Hi @iphoneio,
which version of AlDente do you use?

**Comment by nocom** [comment]
The free version since both other options are yellow and do not reactAm 13.04.21 um 09:16 schrieb Matthias Kerbl
                
            
            
                
                    Von: "Matthias Kerbl" ***@***.***>Datum: 13. April 2021An: "davidwernhart/AlDente" ***@***.***>Cc: "Mention" ***@***.***>,"nocom" ***@***.***>Betreff: Re: [davidwernhart/AlDente] Helper file considered dangerous (#247)
                
                

MBP 2016 15" Big Sur
I. get a warning immediately after installing that the. helper file. can damage my comput


Hi @nocom,
Which version of AlDente do you use?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/davidwernhart/AlDente/issues/247#issuecomment-818502585",
"url": "https://github.com/davidwernhart/AlDente/issues/247#issuecomment-818502585",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by MatthiasKerbl** [comment]
> The free version since both other options are yellow and do not reactAm 13.04.21 um 09:16 schrieb Matthias Kerbl Von: "Matthias Kerbl" ***@***.***>Datum: 13. April 2021An: "davidwernhart/AlDente" ***@***.***>Cc: "Mention" ***@***.***>,"nocom" ***@***.***>Betreff: Re: [davidwernhart/AlDente] Helper file considered dangerous (#247) MBP 2016 15" Big Sur I. get a warning immediately after installing that the. helper file. can damage my comput Hi @nocom, Which version of AlDente do you use? —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe. [ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "[#247 (comment)](https://github.com/davidwernhart/AlDente/issues/247#issuecomment-818502585)", "url": "[#247 (comment)](https://github.com/davidwernhart/AlDente/issues/247#issuecomment-818502585)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

Did you have any previous versions of AlDente installed?

**Comment by nocom** [comment]
Yes but when I updated my Cocktail app the same warning popped up and I deleted AIDente. Am 13.04.21 um 16:00 schrieb Matthias Kerbl
                
            
            
                
                    Von: "Matthias Kerbl" ***@***.***>Datum: 13. April 2021An: "davidwernhart/AlDente" ***@***.***>Cc: "Mention" ***@***.***>,"nocom" ***@***.***>Betreff: Re: [davidwernhart/AlDente] Helper file considered dangerous (#247)
                
                



The free version since both other options are yellow and do not reactAm 13.04.21 um 09:16 schrieb Matthias Kerbl Von: "Matthias Kerbl" @.>Datum: 13. April 2021An: "davidwernhart/AlDente" @.>Cc: "Mention" @.>,"nocom" @.>Betreff: Re: [davidwernhart/AlDente] Helper file considered dangerous (#247) MBP 2016 15" Big Sur I. get a warning immediately after installing that the. helper file. can damage my comput Hi @nocom, Which version of AlDente do you use? —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe. [ { @.": "http://schema.org", @.": "EmailMessage", "potentialAction": { @.": "ViewAction", "target": "#247 (comment)", "url": "#247 (comment)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { @.": "Organization", "name": "GitHub", "url": "https://github.com" } } ]



Did you have any previous versions of AlDente installed?



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/davidwernhart/AlDente/issues/247#issuecomment-818759551",

"url": "https://github.com/davidwernhart/AlDente/issues/247#issuecomment-818759551",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by MatthiasKerbl** [comment]
Hi,

try the following steps:

Quit and delete AlDente and go in Finder to Macintosh HD/Library/LaunchDaemons and delete “com.davidwernhart.Helper.plist”. Afterward, go to Macintosh HD/Library/PrivilegedHelperTools and delete “com.davidwernhart.Helper”. Restart your MacBook and download and install the newest version of AlDente again.

**Comment by mrsbpier** [comment]
<img width="453" alt="Schermata 2021-05-11 alle 09 24 48" src="https://user-images.githubusercontent.com/84006973/117776134-7fb03100-b23b-11eb-9204-aa104370683b.png">

Same here...latest version of AlDente and macOS.

**Comment by MatthiasKerbl** [comment]
Hey everyone,

we released a completely new version of AlDente yesterday which will fix the problems you encounter.
You can download the new version here: https://github.com/davidwernhart/AlDente/releases

Please uninstall the old version of AlDente before installing the new one.
