### ISSUE TITLE
M1 macbook air keyboard not working properly

### ISSUE THREAD

**Issue by m1mba** [davidwernhart/AlDente#251]
Hello! I just noticed after installing the helper that my a and d keys are not working. 
I don´t know if it´s related so I ask you guys.
I´ve already tried uninstalling, wiping the ssd and reinstalling OS from scratch. 
Still not working. I´ve also tried an external keyboard and it does work.
I would also revive and restore but I don´t have another macbook to do so.
Any ideas?
Thank you!

At the same time, I installed Rosetta2.
I have also tried disabling all keyboard shortcuts. Key is not stucked.

**Comment by m1mba** [comment]
At the same time I installed rosetta 2.

**Comment by m1mba** [comment]
I have also disabled all keyboard shorcuts

**Comment by MatthiasKerbl** [comment]
Hi @m1mba,

I am very sorry you have issues since you installed AlDente. However, I don't think AlDente has anything to do with your keys not working properly anymore. In my opinion, this could be a hardware issue.

**Comment by m1mba** [comment]
Hello Matthias, thank you for your answer. I´m starting to think it is indeed a hardware problem. I wish I could try restoring the firmware. I guess I´ll take it to the store.

**Comment by MatthiasKerbl** [comment]
I think we can close this issue for now, since it is probably not correlated with AlDente. However, if you find anything else, let us know.
