### ISSUE TITLE
Battery level exceeds the limit

### ISSUE THREAD

**Issue by keremsirin** [davidwernhart/AlDente#253]
I set max battery level to 80% and like for every 8-10 minutes battery level becomes 81% then it cuts energy and again turns 80% because of allowing discharge. Its exceeds the limit.

**Comment by MatthiasKerbl** [comment]
Hi @keremsirin,
do you have Apple's Optimised Battery Charging disabled?

**Comment by keremsirin** [comment]
Hi @MatthiasKerbl,
No I did not. Is it the problem?

**Comment by MatthiasKerbl** [comment]
Yes, this behavior is due to Optimised battery charging being still enabled. Therefore, we recommend disabling it in our README.
You should disable Optimise battery charging and try AlDetne again.

**Comment by keremsirin** [comment]
I'm sorry I did not see that. Thank you

**Comment by MatthiasKerbl** [comment]
> I'm sorry I did not see that. Thank you

No worries, you are welcome.
