### ISSUE TITLE
Crash report AlDente Pro beta

### ISSUE THREAD

**Issue by mikebore** [davidwernhart/AlDente#256]
I have just seen in Console that I had a crash a few days ago. I wasn't aware of it at the time.

Not sure of correct means of submitting it, or if you want it. 

Attaching it to this post anyway.

[AlDente-Pro_2021-04-14-235239_MBA16.crash.zip](https://github.com/davidwernhart/AlDente/files/6348765/AlDente-Pro_2021-04-14-235239_MBA16.crash.zip)

**Comment by MatthiasKerbl** [comment]
Hi @mikebore,

thanks for sharing, we will take a look at it.
