### ISSUE TITLE
Big Sur 11.2.3, app will not launch.

### ISSUE THREAD

**Issue by cspencer49519** [davidwernhart/AlDente#257]
I receive the error
: "You can’t open the application “AlDente_2.2_Notarized” because it may be damaged or incomplete."

2018 MBP w/ touchbar.

**Comment by MatthiasKerbl** [comment]
Hi @cspencer49519,

Did you have a previous version of AlDente installed?

**Comment by cspencer49519** [comment]
I did, I removed it before I upgraded to Big Sur. I'm having problems with my battery and I'm hoping that I may have neglected to set the capacity back to 100%, as instructed.

**Comment by cspencer49519** [comment]
What now happens is whenever my laptop is unplugged, once it reaches 70%, the screen turns off, and it logs me out, it won't turn back on until I plug it in. I have reset SMC and PRAM.

**Comment by cspencer49519** [comment]
I should also add battery status reads normal under macos, and I've used my battery very minimally, so I'm just trying to make sure it's nothing I've done before I bring it to the apple store.
