### ISSUE TITLE
MacBook Pro (15-inch, 2019) not working

### ISSUE THREAD

**Issue by jasonliaotw** [davidwernhart/AlDente#26]
I'm setting Max Charge to 80% , Still over 80% ...
If need more information, Please replay me, I will provide your need. Thanks.

**Comment by DevNulPavel** [comment]
@jasonliaotw Try to discharge your battery lower 80%, application limits only charging max value

**Comment by jasonliaotw** [comment]
I forgot to restart the computer, and it is now resolved. Thank you.
