### ISSUE TITLE
Pro: Cannot disable the calibration mode toggle, if enabled in Clamshell mode

### ISSUE THREAD

**Issue by vividfog** [davidwernhart/AlDente#263]
I've got an M1 Air running in clamshell mode. I clicked on the **Start Calibration** button.

**Observed behavior:** A dialog appears explaining that this mode can't be activated in clamshell mode. Clicking **OK** will make the dialog appear again, and again, and again. Calibration mode can't be turned off, even though it's not really on. Clicking **Quit** quickly after clicking **OK**, and then restarting the app, that's the workaround I used. Now the app works as usual.

**Expected behavior:** Clicking **OK** should turn Calibration Mode (button) off, and there should not be an infinite loop of dialogs explaining the situation.

![Screen Shot 2021-04-25 at 0 31 20](https://user-images.githubusercontent.com/75913791/115973446-af81e800-a55d-11eb-93c1-cff9bc1370ac.png)

**Comment by MatthiasKerbl** [comment]
Hi @vividfog,

thank you for reporting this issue. We are looking into this.

Kind regards,

Matthias

**Comment by MatthiasKerbl** [comment]
Hi @vividfog,

We have just released an update of AlDente Pro which fixed this issue.

Kind regards,

Matthias

**Comment by vividfog** [comment]
That was quick. I can verify that the issue is indeed gone after I updated the app.
