### ISSUE TITLE
Pro download should not be behind trackers

### ISSUE THREAD

**Issue by gbil** [davidwernhart/AlDente#265]
I paid for your app but the download link is behind trackers which I don't appreciate
specifically this part: https://click.pstmrk.it/ 

I was able to decode the tracking link from the email to the original one but it shouldn't be there to start with really

**Comment by MatthiasKerbl** [comment]
> I paid for your app but the download link is behind trackers which I don't appreciate
> specifically this part: https://click.pstmrk.it/
> 
> I was able to decode the tracking link from the email to the original one but it shouldn't be there to start with really

Hi @gbil,

We use a third-party company to handle our worldwide transactions and it looks like they use are using this tracker.
Unfortunately, we can't do anything about it.

I hope you understand!

Kind regards,

Matthias

**Comment by gbil** [comment]
not sure how this limits you from providing a direct link on your site

**Comment by MatthiasKerbl** [comment]
> not sure how this limits you from providing a direct link on your site

You are right, I have just provided a direct download link in our FAQs on our website.
