### ISSUE TITLE
Cycle count still increments

### ISSUE THREAD

**Issue by im-AMS** [davidwernhart/AlDente#268]
The charge cycle count increases randomly.

Here is wat i mean, I set my max at 80% and since I always need to keep my mac connected to display. The cycle count doesn't always increment, only sometimes it does.

Im running on M1 Mac Air Big Sur

**Comment by PDVJAM** [comment]
Same here.

**Comment by MatthiasKerbl** [comment]
Hi,

I don’t think the cycle count is reliable. It is more of an estimate. However, that’s more of a guess so I definitely have to look into this.
Thanks for the feedback and if you have new observations, let me know.
