### ISSUE TITLE
Sailing mode doesn't work

### ISSUE THREAD

**Issue by Nemo3006** [davidwernhart/AlDente#269]
Hey, I set my max chargelevel at 70%, sailing mode is activated with 5% but my MacBook Air doesn't sail. Is stays at 70% all the time that it is plugged in. What can I do, what can I test?

Greets, Daniel

**Comment by MatthiasKerbl** [comment]
> Hey, I set my max chargelevel at 70%, sailing mode is activated with 5% but my MacBook Air doesn't sail. Is stays at 70% all the time that it is plugged in. What can I do, what can I test?
> 
> Greets, Daniel

Hey Daniel,

Check out our blog article about the Sailing Mode: https://apphousekitchen.com/feature-explanation-sailing-mode/

Kind regards,

Matthias

**Comment by mikebore** [comment]
Thanks for the blog article. My experience is that the natural discharge is so slow that sailing does indeed appear not to be doing anything.

**Comment by MatthiasKerbl** [comment]
> Thanks for the blog article. My experience is that the natural discharge is so slow that sailing does indeed appear not to be doing anything.

That's also my experience. However, you can speed up the Sailing by using an underpowered power supply.
