### ISSUE TITLE
After I uninstalled AlDente , Battery is overcharging.

### ISSUE THREAD

**Issue by YekeD** [davidwernhart/AlDente#271]
I have 2020 MacBook Air M1, I uninstalled (It was set to %100) app and deleted helpers after that I restarted the pc but when I charge it ,even its %100 it says still charging. (On System Information) // Also when I plug the charging cable for a period of time it says "Battery is not charging" even though I deleted the app.

How can I solve this?

**Comment by MatthiasKerbl** [comment]
Hi @YekeD,

I am not sure if I understand your issue correctly but you are saying that when you charge your MacBook to 100% your MacBook says that it is still charging even if the state of charge is already 100%? Secondly, when you are not at 100% and you have plugged in your MacBook, it does not charge?

**Comment by YekeD** [comment]
Sorry for my English. The problem is after battery getting fully charged . And I  want to use Charging Adapter for laptop, On the Apple  menu and System Information/Power , it says charging, Basically overcharging.

**Comment by YekeD** [comment]
"Secondly, when you are not at 100% and you have plugged in your MacBook, it does not charge?" I don't have problem with that. Just the overcharging problem.

**Comment by YekeD** [comment]
<img width="673" alt="Screen Shot 2021-05-02 at 18 47 06" src="https://user-images.githubusercontent.com/83221685/116819026-e916ac80-ab76-11eb-91b3-f2f32923635b.png">


> Hi @YekeD,
> 
> I am not sure if I understand your issue correctly but you are saying that when you charge your MacBook to 100% your MacBook says that it is still charging even if the state of charge is already 100%? Secondly, when you are not at 100% and you have plugged in your MacBook, it does not charge?

<img width="673" alt="Screen Shot 2021-05-02 at 18 47 06" src="https://user-images.githubusercontent.com/83221685/116819074-11061000-ab77-11eb-838f-58ceef1c8382.png">

**Comment by MatthiasKerbl** [comment]
Hi @YekeD,

You don't need to worry about overcharging. Your MacBook has overcharging protection.
The reason why your battery still shows charging even if your state of charge is 100% is that it will rebalance your cells and calibrate your BMS.
