### ISSUE TITLE
Doesn't work with closed laptop using monitors... cycles Sleep State in that case.

### ISSUE THREAD

**Issue by royvella** [davidwernhart/AlDente#275]
So it goes...

**Comment by MatthiasKerbl** [comment]
> So it goes...

Hi @royvella,

as described in our readme, this is due to technical limitations. Just uncheck the feature "allow discharge" and it will work fine even with a closed lid.

Kind regards,

Matthias

**Comment by royvella** [comment]
Ok… will give it a try.  Thanks!

Roy
