### ISSUE TITLE
Al Dente Pro Calibration Mode 

### ISSUE THREAD

**Issue by MWKing777** [davidwernhart/AlDente#276]
Loving the pro version! Did my first calibration today using the calibration mode feature. But I noticed that once it reaches 100%, it stays in calibration mode, and does not automatically discharge to my previously set value(in this case 60%). Is it intended for me to manually turn off calibration mode after my Mac reaches 100%?

**Comment by MatthiasKerbl** [comment]
> Loving the pro version! Did my first calibration today using the calibration mode feature. But I noticed that once it reaches 100%, it stays in calibration mode, and does not automatically discharge to my previously set value(in this case 60%). Is it intended for me to manually turn off calibration mode after my Mac reaches 100%?

Hi @MWKing777,

Actually, the Calibration mode is programmed to stay at 100% for one hour to rebalance the cells and calibrate the BMS as well as possible. You just have to wait one hour and afterward, AlDente Pro will automatically discharge back to your charge limit. You can read more about the calibration mode on our blog: https://apphousekitchen.com/feature-explanation-calibration-mode-2/

Kind regards,

Matthias
