### ISSUE TITLE
Mac doesn't charging without AlDente! Even after uninstalled

### ISSUE THREAD

**Issue by adayush** [davidwernhart/AlDente#277]
My Mac (Air M1) doesn't charge without AlDente. I removed the app by setting the limit to 100% and then moved it to trash. It doesn't even charge now. Please help

**Comment by adayush** [comment]
Nvm, after system update everything works nicely. Though the reboot didn't work when I tried it.

**Comment by ThatXliner** [comment]
I'm experiencing this issue, on an Intel Mac. Please help? I removed the app after uninstalling the helper, set "Optimize battery charging" back on, and moved it to trash.

**Comment by MatthiasKerbl** [comment]
Hi @ThatXliner,

did you try an SMC reset? https://support.apple.com/en-us/HT201295

**Comment by ThatXliner** [comment]
Sorry about this, this was probably caused by something else. Using another port for charging worked perfectly. It probably just got dirty.
