### ISSUE TITLE
Cycle count increments

### ISSUE THREAD

**Issue by PDVJAM** [davidwernhart/AlDente#278]
M1, Big Sur.
I use AlDente Free and keep change at 88%. Sometimes, for example during OS update, the battery charges to its max and then boom - +1 battery circle. Isn't one circle must be bigger than draining-charging from 88 to 100%? Doesn't seem right.

**Comment by MatthiasKerbl** [comment]
> M1, Big Sur.
> I use AlDente Free and keep change at 88%. Sometimes, for example during OS update, the battery charges to its max and then boom - +1 battery circle. Isn't one circle must be bigger than draining-charging from 88 to 100%? Doesn't seem right.

Hi @PDVJAM,
one cycle should be the result of completely discharging and charging the battery one time. However, I don't think the cycle count is accurate.
