### ISSUE TITLE
Feature request :Clamshell support for M1 Macs ?

### ISSUE THREAD

**Issue by F3000** [davidwernhart/AlDente#280]
Is this something the Pro version can do ?

**Comment by MatthiasKerbl** [comment]
> Is this something the Pro version can do ?

Hi @F3000,
AlDente Pro only has one feature which doesn't work in clamshell mode and that's Dicharge. This is due to technical limitations and we have not found a workaround for this issue yet. However, the other features such as Charge Limiter, Heat Protection and Sailing Mode work fine even in Calamshell mode.

**Comment by F3000** [comment]
Thanks 😊 do you think that this could be added in a future update from Apple? 

And because of this the "calibration" Mode also don't Work in clamshell mode ?

**Comment by MatthiasKerbl** [comment]
> Thanks 😊 do you think that this could be added in a future update from Apple?
> 
> And because of this the "calibration" Mode also don't Work in clamshell mode ?

It's unlikely but possible.
You are right, the Calibration Mode does not work in clamshell mode as well.

**Comment by F3000** [comment]
@MatthiasKerbl  

i have seen that with latest version 1.07 that issue would be solved ? 

So all features of the pro version including calibration mode are working in clamshell mode ?

**Comment by MatthiasKerbl** [comment]
Hi @F3000,

A lot of development effort went into enabling these features but yes, Discharge and Calibration Mode work now even in Clamshell mode.

**Comment by F3000** [comment]
@MatthiasKerbl thabks . Works for my M1 Air 😊

do you know something about the time how slow the system will lose  % ?
