### ISSUE TITLE
Big Sur 11.3.1 seems to be invalid after the update. Is it just me. Every time you open it, you will be reminded to install the helper, but you are still charging

### ISSUE THREAD

**Issue by qiuniang6943** [davidwernhart/AlDente#282]
Big Sur 11.3.1 seems to be invalid after the update. Is it just me. Every time you open it, you will be reminded to install the helper, but you are still charging
Model MBA M1
![Uploading image.png…]()

**Comment by m12108** [comment]
I have the same problem

![image](https://user-images.githubusercontent.com/83855611/117527927-12658b80-b002-11eb-9338-178276b9289f.png)

**Comment by qiuniang6943** [comment]
> I have the same problem
> 
> ![image](https://user-images.githubusercontent.com/83855611/117527927-12658b80-b002-11eb-9338-178276b9289f.png)

My hint is the same as yours

**Comment by ichbinsss267** [comment]
I am facing the same bug in 11.4 since in v. 2.2 since ... 2-3 weeks? That's too long, can't use AlDente anymore.

**Comment by m12108** [comment]
> 我在 11.4 中面临同样的错误，因为在 v. 2.2 中，因为...... 2-3 周？太长了，不能再使用AlDente了。
My problem is solved
https://github.com/davidwernhart/AlDente/issues/283#issuecomment-841012993

**Comment by ichbinsss267** [comment]
Thank you, great! :)

**Comment by MatthiasKerbl** [comment]
Hi everyone,

We just released a new version of AlDente which should solve the problem you encountered.
You can download the new version here: https://github.com/davidwernhart/AlDente/releases
Please uninstall the old version of AlDente before installing the new one.

Sorry, it took so long but I hope you like the new version.

Kind regards,
Matthias
