### ISSUE TITLE
can't use. helper not found.i try 20times,and 2.1,its not work

### ISSUE THREAD

**Issue by ifan7** [davidwernhart/AlDente#283]

**Comment by eflylab** [comment]
![image](https://user-images.githubusercontent.com/1343670/118223484-f8212700-b4b3-11eb-9d0c-1ce5076a3a2d.png)

+1
reinstall cant work

**Comment by eflylab** [comment]
open terminal and run 
sudo launchctl load -w /Library/LaunchDaemons/com.davidwernhart.Helper.plist

**Comment by MatthiasKerbl** [comment]
Hi @ifan7,

We are aware of this bug and working on a fix.
When an update is ready, we will let you know.

**Comment by MatthiasKerbl** [comment]
Hi @ifan7 ,

We just released a new version of AlDente which should solve the problem you encountered.
You can download the new version here: https://github.com/davidwernhart/AlDente/releases
Please uninstall the old version of AlDente before installing the new one.

Sorry, it took so long but I hope you like the new version.

Kind regards,
Matthias
