### ISSUE TITLE
AlDente not starting after restarting computer (MBA M1).

### ISSUE THREAD

**Issue by henoire** [davidwernhart/AlDente#289]
Is this normal behaviour? Every time I log out and use a different user account or if I restart the computer I always have to manually start AlDente, otherwise my battery charges right to 100%. I have checked off "Launch at login" in the settings as well. I'm running version 2.2.

**Comment by davidwernhart** [comment]
Hey @henoire 

Launch at Login should start AlDente automatically after a restart when enabled.
However, this only works if the app is inside your Application folder.

Best regards,
David

**Comment by henoire** [comment]
Ahhhh! Thank you! Not sure why it wasn't there in the first place but It's working as it should now. Thanks!
