### ISSUE TITLE
charging level based on the time of day

### ISSUE THREAD

**Issue by git-anish** [davidwernhart/AlDente#29]
Hi,

I wanted to suggest an enhancement to a future version of AlDente

I think AlDente should have charge levels based on the time of day or something similar, as an example the charge level can be set to 50% during the evening/night. Then as the day is about to begin the charge can/should be set to 80% so it can be usable all day.

I think this would be a good compromise between usability and preserving battery health.

This suggestion is essentially mimicking the battery health feature on iOS 13/iPhones.

Thanks for creating the app!

**Comment by TheMazus** [comment]
Hey git-anish,

that's a great idea for a future feature update. 
Thanks for sharing and glad you like the app.

Best regards,

TheMazus
