### ISSUE TITLE
Is it safe when the charge light blink orange to green?

### ISSUE THREAD

**Issue by dyaskur** [davidwernhart/AlDente#290]
I just downloaded then restarted but still doesn't work, my MacBook Pro early 2015 still charging. Then I tried to check `Allow discharge` but it makes power source from battery and my charge light blinking every time

<img width="563" alt="Screen Shot 1442-10-03 at 11 31 08 DYAS" src="https://user-images.githubusercontent.com/9539970/118371188-a244a000-b5d5-11eb-986d-b13c997ebf6b.png">

and also why still charging even above max battery charge setting?
<img width="553" alt="Screen Shot 1442-10-03 at 11 34 26 DYAS" src="https://user-images.githubusercontent.com/9539970/118371281-1a12ca80-b5d6-11eb-9182-738dde2a68b7.png">

**Comment by dyaskur** [comment]
Sometimes after I plug out and plug in again the battery status full charge for abour 1-2 secon then charging again

**Comment by MatthiasKerbl** [comment]
Hi @dyaskur,

We just released a new version of AlDente which should solve the problem you encountered.
You can download the new version here: https://github.com/davidwernhart/AlDente/releases

Kind regards,
Matthias

**Comment by gahoo** [comment]
Version 1.22 has the same issue on MacBook Pro late 2013. In discharge mode, the led light keep blinking.

**Comment by ext452** [comment]
I had the same issue when I connected the second monitor and used it for a while via type-c. After switching to HDMI I realized led blinking on power connector. Restarting of laptop helped me - no light blinking now.
MBP M1 14'
AIDente Pro 1.22.2
