### ISSUE TITLE
Crashes Mac

### ISSUE THREAD

**Issue by mygregstuff** [davidwernhart/AlDente#299]
Crashes computer about 60 seconds after rebooting. SMC reset did not work.

Mac OS 11.3.1
MacBook Pro (15-inch, 2016)
2.9 GHz Quad-Core Intel Core i7

**Comment by MatthiasKerbl** [comment]
> Crashes computer about 60 seconds after rebooting. SMC reset did not work.
> 
> Mac OS 11.3.1
> MacBook Pro (15-inch, 2016)
> 2.9 GHz Quad-Core Intel Core i7

Hi @mygregstuff,

Did you try to uninstall AlDente?

**Comment by mygregstuff** [comment]
Yes. Aldente has been uninstalled.

**Comment by MatthiasKerbl** [comment]
Do you still encounter this problem?
Did you delete the helpers too?

**Comment by mygregstuff** [comment]
I have not re-encountered the issue after reinstalling the application.

**Comment by MatthiasKerbl** [comment]
> I have not re-encountered the issue after reinstalling the application.

Perfect, you can try our newest update AlDente 1.04 which is much more stable than the old versions.
