### ISSUE TITLE
Request: 10.13 High Sierra

### ISSUE THREAD

**Issue by Donothir** [davidwernhart/AlDente#30]
Older computers (around 2011) don't have a way to keep their (failing) battery optimal. If this program was made backward compatible to High Sierra, I (my MBP 2011) would be really happy.

**Comment by DevNulPavel** [comment]
@Donothir 
You can try my command line alternative, it probably should work. My script uses the same approach as AlDente
https://github.com/DevNulPavel/osx_battery_charge_limit

**Comment by al3x-huang** [comment]
Is there a reason why this app doesn't support 10.12? I don't suppose the SMC BCLM logic is different vs 10.15

**Comment by YvanQu** [comment]
if you haven't gotten this figured out yet, heres something a bit more user friendly https://github.com/godly-devotion/charge-limiter

**Comment by MatthiasKerbl** [comment]
Hi @DevNulPavel,

due to SwiftUI not being compatible with older macOS versions, AlDente is unfortunately not compatible with High Sierra.
