### ISSUE TITLE
What does the status label mean?

### ISSUE THREAD

**Issue by FedorKorolev** [davidwernhart/AlDente#300]
«Charge inhabit = false | Prevent Sleep = true | Inflow enabled = true» — what does it mean?

<img width="472" alt="Снимок экрана 2021-05-27 в 02 32 28" src="https://user-images.githubusercontent.com/26021643/119744425-b1a8d080-be94-11eb-87a1-20975f180dde.png">

**Comment by MatthiasKerbl** [comment]
Hi @FedorKorolev,

Charge inhibit: false -> charging is not inhibited
Charge inhibit: true -> charging is inhibited

Prevent Sleep: false -> MacBook is going to sleep as usual
Prevent Sleep: true -> AlDente prevents the MacBook from sleep until the charge limit is reached

Inflow enabled: false -> MacBook is not charging
Inflow enabled: true -> MacBook is charging
