### ISSUE TITLE
Aldente pro website blocked

### ISSUE THREAD

**Issue by sajeev2112** [davidwernhart/AlDente#303]
Hi,
I would like to purchase AlDente but the website is currently blocked by my ISP (virgin media in the UK.) I would like to get the opportunity to get ardent pro so is there any alternative way where I can also reliably get updates.

**Comment by hopkapi** [comment]
Have you tried [reporting it to VM](https://www.virginmedia.com/help/web-safe-troubleshooting)?

**Comment by mikebore** [comment]
I am with Virgin Media in UK and site is not blocked for me.

What browser? If Safari, try click and hold the reload symbol in the Safari address window, and select "load without content blockers" from the drop down.

**Comment by s4j33v** [comment]
I have tried it on different devices so I know it isn't a safari/chrome issue. It isn't a WebSafe issue or I would have seen the WebSafe pop up so I am not sure why this is an issue. I have realised this website works on a mobile data connection but I would like the website to work so I don't have any issues with future updates,

**Comment by MatthiasKerbl** [comment]
> I have tried it on different devices so I know it isn't a safari/chrome issue. It isn't a WebSafe issue or I would have seen the WebSafe pop up so I am not sure why this is an issue. I have realised this website works on a mobile data connection but I would like the website to work so I don't have any issues with future updates,

Do you think the problem might be your router/modem?
