### ISSUE TITLE
[M1] Resets to 0%

### ISSUE THREAD

**Issue by petrbela** [davidwernhart/AlDente#304]
I was using AlDente on my old Intel MBP and it seemed to work as it should. Now I've migrated to an M1 Air (doing a 1:1 clone using Migration Assistant). When I try to set a percentage, it always resets back to 0 after a second. Needless to say, it doesn't affect (stop) charging in any way.

Restarting nor uninstalling the app/helper didn't help, and as the M1 doesn't have a traditional SMC, I'm not sure what else I could check. FTR, before I did the migration, I briefly (for a few hours) tried AlDente on a fresh M1 system, and that seemed to work.

https://user-images.githubusercontent.com/668124/121040385-17d40400-c76f-11eb-893b-706b00e26d3a.mov

**Comment by showsky** [comment]
Hi petrbela

you can disable rosetta and try it

![image](https://user-images.githubusercontent.com/800001/123606953-017e0d00-d830-11eb-84fe-648b4bf2170c.png)

**Comment by petrbela** [comment]
That was a good pointer! I actually had to check "Open using Rosetta". Upon reopening, the helper was reinstalled, and the "Use classic SMC Key (Intel)" option showed up, which I unchecked, and now it's working as it should. Thanks!

<img width="389" alt="Screen Shot 2021-06-28 at 4 53 00 PM" src="https://user-images.githubusercontent.com/668124/123713288-4e161800-d831-11eb-89f1-5b1b6001751e.png">
