### ISSUE TITLE
Overheating issue on Al Dente Pro 1.04

### ISSUE THREAD

**Issue by Dhudong** [davidwernhart/AlDente#314]
<img width="146" alt="image" src="https://user-images.githubusercontent.com/82040077/122659239-98035c00-d1a8-11eb-9e9a-cdece2719911.png">
My M1 Macbook Air has been overheating like crazy since I've updated to version 1.04 of Al Dente Pro. Just now it reached 43.3 degrees celsius. It normally sits at 34 degrees. I don't have any heavy app open and it's practically idle. I'm disabling the Al Dente Pro for now.

**Comment by jacksoncooper** [comment]
Which system monitor are you using? I also have an M1 Air. I'd like to see if my machine is similarly affected.

**Comment by Dhudong** [comment]
I'm using the heat protection feature of the Al Dente Pro which also shows the current temperature of the system.

**Comment by vassudanagunta** [comment]
coconutBattery is a well regarded and popular tool for monitoring battery health. It includes temp.

**Comment by MatthiasKerbl** [comment]
> <img alt="image" width="146" src="https://user-images.githubusercontent.com/82040077/122659239-98035c00-d1a8-11eb-9e9a-cdece2719911.png">
> 
> My M1 Macbook Air has been overheating like crazy since I've updated to version 1.04 of Al Dente Pro. Just now it reached 43.3 degrees celsius. It normally sits at 34 degrees. I don't have any heavy app open and it's practically idle. I'm disabling the Al Dente Pro for now.

Hi @Dhudong,

depending on your ambient temperature, CPU load, and charging/discharging speed you battery can reach temperatures above 40 °C. That’s why we have implemented the feature Heat Protection. However, the CPU load of AlDente is negligible and therefore, AlDente does not really increase the temperature of your battery.

Do you still experience these high battery temperatures?

**Comment by CaesireKin** [comment]
I have the same issues, the version on my mac book pro 2018 15-inch i7 is AI Dente Pro 1.04.
My mac book sleeps every night. in usual, it's cold when it wake up every morning. but since a few days ago, something get different, some sensors temperature goes to 40 ℃ above.
I've enable the sailing mode sail to 74%, and enable the Stop charging when sleeping, Stop charging when powered off. I think this is not caused by the ambient temperature, cuz I get up every day before dawn, it's significantly higher than the ambient temperature

**Comment by MatthiasKerbl** [comment]
Hi @Dhudong @CaesireKin,

did you check the activity monitor if any process is using significant power and how much CPU AlDente Pro is using?

**Comment by CaesireKin** [comment]
Hi @MatthiasKerbl ,
Thank you for your instructions, I would like to reset my mac book airflows setting to the system default (that is what I used when I found that problem) , and take some time to collect my mac book sensors log. 
btw, is AI Dente Pro SMC configs effect fans control?

**Comment by MatthiasKerbl** [comment]
> Hi @MatthiasKerbl ,
> Thank you for your instructions, I would like to reset my mac book airflows setting to the system default (that is what I used when I found that problem) , and take some time to collect my mac book sensors log as well as the process cpu using.
> btw, is AI Dente Pro SMC configs effect fans control?

Hi,
AlDente Pro doesn't change the fan/airflow settings of your MacBook. Do you have another program which does?

**Comment by udoersam** [comment]
If I hvae Al Dente Pro installed on my mac, I can recognize that the temperature is higher than without the app. It seems that the processor don't throttle down the speed to reduce the temp. If I use my macbook pro (Intel i7) in the clamshell mode the computer is crashing down when the temperature is to high.

**Comment by MatthiasKerbl** [comment]
> If I hvae Al Dente Pro installed on my mac, I can recognize that the temperature is higher than without the app. It seems that the processor don't throttle down the speed to reduce the temp. If I use my macbook pro (Intel i7) in the clamshell mode the computer is crashing down when the temperature is to high.

Hi @udoersam,

Which MacBook model do you have?

**Comment by CaesireKin** [comment]
Hi @MatthiasKerbl 

I think I was posted a problem caused by my own. follow your instructions, I've checked my mac sensors log and cpu usage log, it's seems the temperature growing up every day at 6:00 AM, that is the notification time of my mac's calendar schedule, it wake up the mac book, and seems take a lot of time to run some other program.
Sorry about the issues, maybe it's a problem about system optimization, not caused by AI Dente Pro

**Comment by MatthiasKerbl** [comment]
> Hi @MatthiasKerbl
> 
> I think I was posted a problem caused by my own. follow your instructions, I've checked my mac sensors log and cpu usage log, it's seems the temperature growing up every day at 6:00 AM, that is the notification time of my mac's calendar schedule, it wake up the mac book, and seems take a lot of time to run some other program.
> Sorry about the issues, maybe it's a problem about system optimization, not caused by AI Dente Pro

Hi @CaesireKin,

Thanks for the update and I am glad that AlDente Pro is most likely not the reason for your heat issues.
