### ISSUE TITLE
Error when trying to update

### ISSUE THREAD

**Issue by suijkerwerk** [davidwernhart/AlDente#319]
Hi,

I love the no nonsense approach of AlDente. Unfortunately I get the following message when I hit the "check for updates button" from the menu bar:

"AlDente can’t be updated if it’s running from the location it was downloaded to."

AlDente was installed to my apps from the downloads folder. So the message shouldn't apply to me.
Any ideas how to solve this?

**Comment by MatthiasKerbl** [comment]
Hi @suijkerwerk,

I haven’t seen this message before.
Try to uninstall and reinstall AlDente.

**Comment by suijkerwerk** [comment]
Hi, I downloaded it again and moved the app directly to the apps folder. Now the message has gone!
