### ISSUE TITLE
Allow discharge not working correctly

### ISSUE THREAD

**Issue by daniloderosa** [davidwernhart/AlDente#321]
I have a problem with AlDente running on my Macbook Air 2018 (so, Intel). 

I usually set the slider to 80%, charge until it reaches that threshold, then change it to 40% and allow discharge mode. The problem is that every single time the Mac stops discharging at ~50/60%, without changing any setting. I've tried to re-install the helper, but it doesn't work. 

I know, I could just unplug the Mac and let it discharge to 40%, but the discharge mode is there for a reason, isn't it? :)

**Comment by MatthiasKerbl** [comment]
> I have a problem with AlDente running on my Macbook Air 2018 (so, Intel).
> 
> I usually set the slider to 80%, charge until it reaches that threshold, then change it to 40% and allow discharge mode. The problem is that every single time the Mac stops discharging at ~50/60%, without changing any setting. I've tried to re-install the helper, but it doesn't work.
> 
> I know, I could just unplug the Mac and let it discharge to 40%, but the discharge mode is there for a reason, isn't it? :)

Hi @daniloderosa,

the Allow Discharge feature is still in beta in our free version. Therefore, it doesn't always work properly. However, you should not cycle your battery between 40 and 80%. This will only increase the cycle count and result in a faster battery degradation compared to staying at 80%.
