### ISSUE TITLE
[FR] iOS & WatchOS support

### ISSUE THREAD

**Issue by giuliandenicola1** [davidwernhart/AlDente#324]
I would like to see if it's possible to create a iOS and/or WatchOS version that can do the same thing with my phone and watch.

**Comment by MatthiasKerbl** [comment]
Hi @giuliandenicola1,

I don’t think that’s possible due to iOS and WatchOS being closed systems compared to macOS.

**Comment by lich4** [comment]
Try this, for iOS
https://github.com/lich4/AlDente
