### ISSUE TITLE
Multiple crashes detected by Etre check

### ISSUE THREAD

**Issue by ritakusay** [davidwernhart/AlDente#325]
Does anyone know what causes [the crash](https://imgur.com/MAVQ6Ei)? The app itself seems to be working just fine. Just worry the crashes may cause power failure of some sort. Macbook pro M1.

**Comment by MatthiasKerbl** [comment]
Hi @ritakusay,

due to a bug in our Helper it crashes regularly. It's not dangerous at all and will be fixed with the next update.
