### ISSUE TITLE
After I uninstalled AIDente，macOS didn't stop charge battery even it‘s fully charged

### ISSUE THREAD

**Issue by msn1983aa** [davidwernhart/AlDente#33]
MacBook Pro 2015 early with macOS 10.15.6
After I uninstalled AIDente，macOS didn't stop charge battery even it‘s fully charged.(battery 100%，but the LED on magsafe plug always orange not green）

Did anyone can tell me how to uninstall AIDente in the correct way？

**Comment by celsoazevedo** [comment]
Have you tried reseting the SMC?

https://support.apple.com/en-us/HT201295

**Comment by gvillo** [comment]
same it's happening to me. I did SMC and nothing... how can we uninstall the helper?

**Comment by gvillo** [comment]
Look for `com.davidwernhart.Helper` and erase both files (located under `/Library/PrivilegedHelperTools` and `/Library/LaunchDaemons`) and that's it.

**Comment by Bables55** [comment]
I deleted those files and did an SMC reset but it doesn't improve.
Is there any other way?

**Comment by andregriffin** [comment]
I ran into this same issue and came across this thread. I solved it by reinstalling Al Dente, making sure the max battery limit was set to 100% in the app, then going through the uninstall/SMC reset. It seems that uninstalling and resetting the SMC does not completely happen if a charging limit under 100% was in effect before uninstalling the app.
