### ISSUE TITLE
Charge On Hold icon no longer working properly 

### ISSUE THREAD

**Issue by LeshawnG** [davidwernhart/AlDente#330]
I uninstalled and reinstalled AlDente today. and upon reinstalling, it no longer displays the charge on hold icon with the plug over the battery, like this.
<img width="720" alt="Screen Shot 2021-07-05 at 12 02 18 AM" src="https://user-images.githubusercontent.com/73793035/124416111-44eee480-dd24-11eb-95e4-45b4a6306e40.png">

When I plug in the charger now, it shows the battery always full at 100 and not the %charge it is held at like it did before.

<img width="836" alt="Screen Shot 2021-04-18 at 2 51 56 AM" src="https://user-images.githubusercontent.com/73793035/124416083-3274ab00-dd24-11eb-9369-8cc2766e643a.png">

I know this is minor but I really prefer seeing the charge on hold icon. Is there anyway to fix this? I prefer seeing the charge on hold icon because it is a lot more explanatory than the 100% charging icon I'm getting displayed now.

Also, how does AlDente display for you? Does it show 100% constantly when plugged in or does it show the percent with the charge on hold icon?

**Comment by MatthiasKerbl** [comment]
Hi @LeshawnG,

do you have AlDente Pro installed?

**Comment by LeshawnG** [comment]
@MatthiasKerbl 
I don't mean to create a false alarm but the "charge on hold icon" is back to working correctly now on AlDente Classic 2.2.

The issue first occurred upon installation of AlDente 1.04 and still persisted in AlDente Classic 2.2 upon reinstallation (1.04 was uninstalled prior to 2.2 reinstallation).
I also tried running older versions of Classic 2.0 and 2.1.2 where the issue persisted before reinstalling 2.2 again.

The issue persisted on 2.2 for a few hours yesterday after final reinstallation while my computer was in use. Today the icon is working normally.

I am not sure what caused the issue upon installation of 1.04 and I can't say what fixed it.

If anything persists in the future I will be sure to let you know. 
Thank you for the quick response!
