### ISSUE TITLE
[Feature Request] An option in the preferences to suppress the alert "AlDente is running in Intel Mode"

### ISSUE THREAD

**Issue by edentsai** [davidwernhart/AlDente#341]
Hopes the AlDente Pro can provide an option in the preferences 
to suppress the alert **"AlDente is running in Intel Model"**.

Here are my opinion as a frequent user of AlDente Pro.app:

- It will be great if the AlDente Pro can launch at login **IN SILENTLY** without pop-up any alert or windows for the frequent users.
- AlDente always pops up the alert when it launched is an interrupt for the frequent users.
- The alert "AlDente is running in Intel Mode" may need to show in the following situations:
    - When the user toggles the Intel Mode in the Preferences.
    - The first few times that AlDente automatically detects the mac is running Intel mode.
    - The first few days since AlDente was installed on macOS, AlDente be launched with the Intel Mode.

It will be more flexible if there has an option in the preferences to suppress the alert "AlDente is running in Intel Mode" for the frequent users.

thanks.

**Comment by MatthiasKerbl** [comment]
> Hopes the AlDente Pro can provide an option in the preferences to suppress the alert **"AlDente is running in Intel Model"**.
> 
> Here are my opinion as a frequent user of AlDente Pro.app:
> 
> * It will be great if the AlDente Pro can launch at login **IN SILENTLY** without pop-up any alert or windows for the frequent users.
> * AlDente always pops up the alert when it launched is an interrupt for the frequent users.
> * The alert "AlDente is running in Intel Mode" may need to show in the following situations:
>   
>   * When the user toggles the Intel Mode in the Preferences.
>   * The first few times that AlDente automatically detects the mac is running Intel mode.
>   * The first few days since AlDente was installed on macOS, AlDente be launched with the Intel Mode.
> 
> It will be more flexible if there has an option in the preferences to suppress the alert "AlDente is running in Intel Mode" for the frequent users.
> 
> thanks.

Hi @edentsai,

Our newest version of AlDente (1.09) will only show the popup "AlDente is running in Intel Model" once.
https://github.com/davidwernhart/AlDente/releases

Cheers,
Matthias

**Comment by edentsai** [comment]
Thank you 👍 👍 👍
