### ISSUE TITLE
Heat Protection not working (while in Calibration Mode atleast)

### ISSUE THREAD

**Issue by BFoerschner** [davidwernhart/AlDente#346]
I've turned on calibration mode and noticed my macbook air got unusually warm. When i checked the battery temp was already at 39.5 Celsius. Here's a Screenshot:
<img width="387" alt="Screenshot 2021-08-04 at 14 01 18" src="https://user-images.githubusercontent.com/1569796/128177541-2f377265-04f0-4f08-abd3-9aebecd43d1d.png">

**Comment by IvanVnucec** [comment]
@MatthiasKerbl There should be a note for that.

**Comment by MatthiasKerbl** [comment]
> @MatthiasKerbl There should be a note for that.

Good idea!
