### ISSUE TITLE
Battery indicator showed wrong battery state during and after charge [macOS Monterey beta 4]

### ISSUE THREAD

**Issue by lozhn** [davidwernhart/AlDente#349]
Yesterday at ≈18:00 (btw, what could be a source of such a step on the chart from below 50% to 100% at once) I left work and didn't open laptop till this morning. In the morning I plugged in the cable as usual and the mac showed "100% battery". Now, after the work I unplugged the laptop from the cable and on the screenshot you can see, that the mac was not charging the whole day, but in the status bar it showed the battery is full.

It seems I allowed discharge to much? 😆

![image](https://user-images.githubusercontent.com/1782287/129046104-8230eb0a-28a3-4006-b0e9-85045a102dee.png)

![image](https://user-images.githubusercontent.com/1782287/129046820-acda553d-6572-4b16-8212-63452af2500c.png)

**Comment by MatthiasKerbl** [comment]
Hi @lozhn,

Do you still encounter this issue?
Please install our newest version of AlDente: https://github.com/davidwernhart/AlDente/releases

**Comment by lozhn** [comment]
@MatthiasKerbl I can't tell, I quit aldente 🤷‍♂️
