### ISSUE TITLE
uninstall script

### ISSUE THREAD

**Issue by dr3mro** [davidwernhart/AlDente#35]
hello 
what is the proper uninstall method ?

**Comment by gvillo** [comment]
Remove the app and then look for `com.davidwernhart.Helper` and erase both files (located under `/Library/PrivilegedHelperTools` and `/Library/LaunchDaemons`) and that's it.

**Comment by timension** [comment]
What's about Apple Silicon Macs? As I understand it's not trivial to reset SMC on them. How can I restore all the values to the default?

**Comment by TheMazus** [comment]
Hi timension, to reset the SMC on an Apple Silicon Macbook you have to shut it down, close the lid and wait 30 seconds. Afterward, you can restart the MacBook and the SMC is reset.
