### ISSUE TITLE
Awaiting License information

### ISSUE THREAD

**Issue by rektologist76** [davidwernhart/AlDente#350]
Hi, does anyone know how long it takes to receive an email after you pay for AlDente Pro?  I may have had a typo in my email when I signed up to pay for the annual subscription.  The payment has cleared, but have not yet received the email. How can I contact someone at App House Kitchen? Thanks.

**Comment by MatthiasKerbl** [comment]
Hi @rektologist76,

Usually, you should receive the emails minutes after the purchase.
Please contact our support (support@apphousekitchen.com) with this issue.

Kind regards,

Matthias
