### ISSUE TITLE
无法唤醒

### ISSUE THREAD

**Issue by xiaoleigithub** [davidwernhart/AlDente#352]
macbook pro 2020 i5
bigsur 11.5.2
AlDente Classic 2.2

外接LG显示器+关闭盖子的macbook。

睡眠后无法唤醒（偶尔发生），需要强行关机，不知道这是否和AlDente兼容性有关。

**Comment by MatthiasKerbl** [comment]
Hi @xiaoleigithub,

Please try our newest version of AlDente.
You can download it here: https://github.com/davidwernhart/AlDente/releases
