### ISSUE TITLE
Battery percentage increasing when lid is closed

### ISSUE THREAD

**Issue by burnout-syndrome** [davidwernhart/AlDente#363]
I've been using AlDente Pro for about two weeks now. Since yesterday, spontaneously, the battery charge rises as soon as the lid is closed. As an example, I have set the maximum charge to 75%, close the MacBook, and the next time I open it, the charge is 84%. That was not the case in the past with AlDente ... I have already reinstalled the helper, I have also performed a restart and SMC reset.

MacBook Pro 13" 2017, latest Big Sur.

Edit: it's even charging when lid is opened, happened a few minutes ago. Maximum level was set to 75%, I used my MacBook, and now it's charged to 78%.

**Comment by MatthiasKerbl** [comment]
Hi @burnout-syndrome,

Which macOS and AlDente Pro version do you have?
Do you use have the feature "Stop charging when sleeping" activated?

**Comment by burnout-syndrome** [comment]
Hi Matthias, thank you for your answer. I am using Big Sur 11.5.2, and AlDente Pro 1.07 over the SetApp Flatrate. "Stop charging when sleeping" was not activated, isn't it dangerous for the battery, when charging stops, every time I close the lid? Should I activate it?

**Comment by MatthiasKerbl** [comment]
Stopping charging while your MacBook is in sleep is the same as stopping it while you use it.
If you want your MacBook to pause charging while it is in sleep, you should definitely activate "Stop charging when sleeping". Just keep in mind, that AlDente is not able to control the charging behavior while your MacBook is in sleep. Therefore, if your MacBook is charging to the desired charge limit, while it goes into sleep, it will stop charging earlier.

**Comment by burnout-syndrome** [comment]
Ah, okay. Thank you! I will give it a try.
