### ISSUE TITLE
Strange behavior of Discharge and Calibration functions in clamshell mode

### ISSUE THREAD

**Issue by teplynin** [davidwernhart/AlDente#366]
I am using AlDente Pro 1.07 on a Macbook Air M1 with an LG Ultrafine 4K external monitor and Magic Keyboard. OS Big Sur 11.5.2.

If I lock the computer and wait for the external monitor screen to turn off (~ 5 sec), the monitor stops turning on when I press the Magic Keyboard keys until the laptop lid is opened. The keyboard itself works, Caps Lock lights up.

If I close the program or turn off the Discharge mode, everything works correctly again: when the computer is locked, the monitor fell asleep, pressed any key - the monitor woke up. 

Reinstalling AlDente,  restarting the computer and reset power settings did not help.

**Comment by snarf55** [comment]
same problem here. MBA M1, Big Sur 11.5.2, Aldente pro 1.07

**Comment by teplynin** [comment]
UP.
Look like support is dead

**Comment by nuggie** [comment]
same issue here ... BenQ Monitor attached via Thunderbolt Dock over HDMI

**Comment by teplynin** [comment]
Well, problem still exists in MacOS Monterey with AlDente 1.09.  Wasted money for pro version.

**Comment by MatthiasKerbl** [comment]
Hi everyone,

We have just released a new version of AlDente (1.10). https://github.com/davidwernhart/AlDente/releases
This version should fix the issues you have experienced with AlDente.

If you still have problems with AlDente, please feel free to let us know.

Thank you for your patience!

Cheers,
Matthias
