### ISSUE TITLE
MacBook is not charging after AlDente was uninstalled

### ISSUE THREAD

**Issue by VladVanHellsing** [davidwernhart/AlDente#367]
Hey guys. I facing an issue after AlDente was uninstalled. It somehow "jammed" the charging process and MacOS thinking that there is no need to charge the machine. Please advice! Thank you!

**Example:** 
1. I charged the machine up to 100%
2. I uninstalled AlDente
3. I used MacBook without charge to low the battery down to 74%
4. I plugged in the charging cable

**My specs:**
Hardware: MBP 16 (2019)
OS: BigSur 11.5.2
AlDente ver - 1.07

**How I uninstall AlDente:**
- Open the app
- move the slider up to 100%
- uninstall helper from settings
- uninstall the app
- restart machine

Please see screenshots in the attachments.

Possible solutions:
- Install Aldente again
- Play with charging slider, untill Mac begins to charge again.

<img width="311" alt="Screenshot 2021-09-01 at 11 58 22" src="https://user-images.githubusercontent.com/67408942/131645370-cafd7927-7ab8-4030-91c4-705e6961cb32.png">

<img width="251" alt="Screenshot 2021-09-01 at 12 09 22" src="https://user-images.githubusercontent.com/67408942/131645373-5af71c9d-f1ad-427e-8ccb-f8134665cab2.png">

<img width="738" alt="Screenshot 2021-09-01 at 12 10 22" src="https://user-images.githubusercontent.com/67408942/131645376-d36a7fb1-9ed7-489c-9b06-f8a2369af33f.png">

**Comment by burnout-syndrome** [comment]
Did you perform a SMC reset after uninstall?

**Comment by VladVanHellsing** [comment]
> Did you perform a SMC reset after uninstall?

Hi! No, I did't. Will try.

**Comment by boafur** [comment]
Hello! I have experienced this issue, and after restarting the MacBook and performing an SMC reset multiple times, the problem does not seem to go away. The only way I am able to charge my MacBook is by installing AlDente again and messing with the slider until the MacBook charges.

I am using a MacBook Pro 2016 on macOS Monterey Beta 6 with AlDente version 1.07.

**Comment by VladVanHellsing** [comment]
I think the issue is still there for MBP 16.

I did another spin with AlDente (after resetting SMC, so AlDente should restore the "clean" SMC setting after been uninstalled) and faced the same results (and reset SMC again to let my Mac charge again).

**Comment by boafur** [comment]
It seems that you are able to allow your mac to charge again without AlDente by resetting the SMC, but I have tried resetting the SMC, PRAM, NVRAM, and many other combinations but to no avail.

**Comment by VladVanHellsing** [comment]
In this case, I can recommend reinstall macOS (to clear SMC and the rest of the system services) and wait until AlDente received full Monterey support after its release.

I can't say why the same machines with just different OS have a completely different reaction to a "hardware" SMC reset.

**Comment by unphased** [comment]
I'm experiencing an issue with my Apple Silicon 2021 Macbook Pro and although I use Al Dente, I believe it is unrelated to Al Dente. It is described here, and many others have the issue: https://www.reddit.com/r/mac/comments/uy84ge/16_m1_max_mbp_wont_charge_until_reboot/

I am installing the 12.5 beta now since the fix is confirmed to be in it. Just leaving this note here so others can follow the trail.
