### ISSUE TITLE
What is supposed to happen?

### ISSUE THREAD

**Issue by gbreeze64** [davidwernhart/AlDente#368]
Open the software on my 13" M1 MacBook Pro and nothing? No dialogs, no menubar icons, not a thing?  Weird.

**Comment by darelldd** [comment]
Yeah, same here. I got a warning that it'll be running in Intel mode so I won't have pro features. And then.... well, I seem to have NO features. I can't see a way to actually use the app. When I try to restart the app, it tells me nope! The app is already running. So, I give up. Where might it be hiding?  Late 2013 MBP

**Comment by MatthiasKerbl** [comment]
Hi @gbreeze64 and @darelldd,

When you open AlDente Free there should be this icon:

<img width="50" alt="icon" src="https://user-images.githubusercontent.com/33470003/133936226-1c84db4a-a1de-45b3-a3a5-23ae1fbac532.png">

in your menu. Click on it to change the charge limit.

Cheers,
Matthias

**Comment by darelldd** [comment]
Yes! There it is up at the top! 

This would be super info to include in the notes somewhere. For the life of me I couldn’t see WHERE it was running as a physical icon.


-= Darell =-
