### ISSUE TITLE
achat de l'application 

### ISSUE THREAD

**Issue by HAMZAOUI1972** [davidwernhart/AlDente#374]
Bonjour
je viens d'acheter l'application al dente 
mais je n'ai reçu aucun mail de confirmation de mon achat
mon nom est Monsieur Hamzaoui Abdelkader

**Comment by MatthiasKerbl** [comment]
Hi @HAMZAOUI1972,

I saw you already communicated with our premium support. Therefore I will close this issue.

Cheers,
Matthias
