### ISSUE TITLE
MacBook still charging while powered off

### ISSUE THREAD

**Issue by martin-braun** [davidwernhart/AlDente#376]
Hi, Pro user here. Thanks for this great software. 

I told Al Dente to avoid charging while sleeping or being powered off, but it seems to keep charging when powered off.

<img width="368" alt="Screen Shot 2021-09-12 at 01 59 45" src="https://user-images.githubusercontent.com/24259245/132966372-3c340142-0326-4b3e-abdb-f0c5bef98f6a.png">

<img width="589" alt="Screen Shot 2021-09-12 at 00 22 21" src="https://user-images.githubusercontent.com/24259245/132963022-26da278d-362f-456c-b835-59729546b10b.png">

Why it keeps charging when powered off, please? Sure I can disconnect when I power off, but this would be nice if it was working. :)

**Comment by IamCrypt0n** [comment]
I can confirm this behavior. Bought this PRO version just for this feature but it is not working on my M1 MacBook :(
![Bildschirmfoto 2021-09-17 um 08 18 03](https://user-images.githubusercontent.com/46143633/133734038-116a022f-f60a-44b3-bc85-53160d7fbbe2.png)

![Bildschirmfoto 2021-09-17 um 08 17 46](https://user-images.githubusercontent.com/46143633/133734312-57990f48-7b9b-46b3-bd51-da5336ac9d7e.png)

**Comment by joujek** [comment]
+1 for this feature - I'm PRO user

**Comment by MatthiasKerbl** [comment]
> Hi, Pro user here. Thanks for this great software.
> 
> I told Al Dente to avoid charging while sleeping or being powered off, but it seems to keep charging when powered off.
> 
> <img alt="Screen Shot 2021-09-12 at 01 59 45" width="368" src="https://user-images.githubusercontent.com/24259245/132966372-3c340142-0326-4b3e-abdb-f0c5bef98f6a.png">
> 
> <img alt="Screen Shot 2021-09-12 at 00 22 21" width="589" src="https://user-images.githubusercontent.com/24259245/132963022-26da278d-362f-456c-b835-59729546b10b.png">
> 
> Why it keeps charging when powered off, please? Sure I can disconnect when I power off, but this would be nice if it was working. :)

Hi @martin-braun,

could you describe in detail what happens when you turn off your MacBook?

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment]
> I can confirm this behavior. Bought this PRO version just for this feature but it is not working on my M1 MacBook :(
> 
> ![Bildschirmfoto 2021-09-17 um 08 25 44](https://user-images.githubusercontent.com/46143633/133734899-79f90316-0e6e-4a7f-bceb-7fbc694a7035.png)
> 
> ![Bildschirmfoto 2021-09-17 um 08 17 46](https://user-images.githubusercontent.com/46143633/133734312-57990f48-7b9b-46b3-bd51-da5336ac9d7e.png)

Hi @IamCrypt0n,

due to hardware changes of the M1 MacBooks, the feature "Stop charging while powered off" is not possible on Apple Silicon MacBooks. Hence, the feature is called "Stop charging when app is closed".

Cheers,
Matthias

**Comment by martin-braun** [comment]
Seems to work now, not sure why is that. If I experience it again, I will reopen a new issue after inspecting further.
