### ISSUE TITLE
MacBook Pro not charging past set limit after AlDente removed

### ISSUE THREAD

**Issue by davidekelly** [davidwernhart/AlDente#377]
Hi,
I tried the free version of AlDente on my 2014 15" MacBook Pro running macOS 11.5.2. AlDente ran in "Intel mode" and I set the charge limit to around 60%. After a few days I decided to discontinue using AlDente (because the MacBook Pro was taking a long time to wake from sleep - seemed to be AlDente-related), so I set the AlDente power limit back to 100%, waited a couple of minutes and then told AlDente to remove the Helper application, and then quit AlDente. Now my MacBook Pro still won't charge above 61%. Any suggestions as to how I can reset the charge limit back to 100%?

Thanks for everyone's help.

**Comment by koolman2** [comment]
Try resetting the SMC.

https://support.apple.com/en-us/HT201295
