### ISSUE TITLE
AlDente not working on M1 11.6?

### ISSUE THREAD

**Issue by scoopdreams** [davidwernhart/AlDente#385]
After upgrading to MacOS 11.6, AlDente seems to have stopped working.

Have tried reinstalling the helper, removing AlDente and reinstalling it entirely, etc. Nothing seems to work.

Could 11.6 have borked AlDente?

![About This Mac 2021-09-18 22-51-44](https://user-images.githubusercontent.com/7950731/133892925-dfbee988-773e-45b5-b28b-c584773df09b.jpg)

**Comment by nguye205** [comment]
mine is working fine except for sailing mode.

**Comment by scoopdreams** [comment]
> mine is working fine except for sailing mode.

Thanks, so this is on M1 Mac and you just disabled sailing mode for it to operate?

**Comment by nguye205** [comment]
> > mine is working fine except for sailing mode.
> 
> Thanks, so this is on M1 Mac and you just disabled sailing mode for it to operate?

Yes, it is on M1 mac. It does stop charging at the set limit but the sailing mode doesn't work. I set the charging limit to 70% and the sailing mode limit set to 35%. So in theory, it shouldn't charge until the battery go down to 35% but it still charges to 70% when the battery is above 35%.

**Comment by simotau** [comment]
Is it me, or the developers are not replying to the issues opened anymore?

**Comment by dragomirweb** [comment]
I can confirm, sailing mode not working and sometimes it charges over the limit 2% 5% 10%. Are the developers aware of this issues?

**Comment by MatthiasKerbl** [comment]
> > > mine is working fine except for sailing mode.
> > 
> > 
> > Thanks, so this is on M1 Mac and you just disabled sailing mode for it to operate?
> 
> Yes, it is on M1 mac. It does stop charging at the set limit but the sailing mode doesn't work. I set the charging limit to 70% and the sailing mode limit set to 35%. So in theory, it shouldn't charge until the battery go down to 35% but it still charges to 70% when the battery is above 35%.

Hi @nguye205,

You can read more about the functionality of the Sailing Mode in on our website: https://apphousekitchen.com/feature-explanation-sailing-mode/

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment]
> After upgrading to MacOS 11.6, AlDente seems to have stopped working.
> 
> Have tried reinstalling the helper, removing AlDente and reinstalling it entirely, etc. Nothing seems to work.
> 
> Could 11.6 have borked AlDente?
> 
> ![About This Mac 2021-09-18 22-51-44](https://user-images.githubusercontent.com/7950731/133892925-dfbee988-773e-45b5-b28b-c584773df09b.jpg)

Hi @scoopdreams,

Do you still experience this issue?
Have you tried restarting/reinstalling AlDente? Sometimes after bigger macOS updates this needs to be done.

Cheers,
Matthias

**Comment by scoopdreams** [comment]
Hi Mathias, tried reinstalling AlDente entirely again, and curiously it seems to have worked.

Will mark this issue as closed, thanks!
