### ISSUE TITLE
Similar App for iOS on your roadmap?

### ISSUE THREAD

**Issue by xploredesign** [davidwernhart/AlDente#386]
Seems the next logical step. In the works?
If so: How do I stay apprised of such a rollout?

**Comment by xploredesign** [comment]
BTW - LOVE AlDente! Great work

**Comment by MatthiasKerbl** [comment]
Hi @xploredesign,

I am glad you like our little app.
Unfortunately, due to iOS devices being much more locked down, it's not really possible to develop such an app.

Cheers,
Matthias

**Comment by lich4** [comment]
Try this, for iOS
https://github.com/lich4/AlDente
