### ISSUE TITLE
AlDente Pro from SetApp support options??

### ISSUE THREAD

**Issue by lboisset** [davidwernhart/AlDente#388]
I use AlDente Pro from SetApp so I didn't receive any mail with the support email address. What options do I have to get Pro support?

**Comment by MatthiasKerbl** [comment]
> I use AlDente Pro from SetApp so I didn't receive any mail with the support email address. What options do I have to get Pro support?

Hi @lboisset,

You can find the premium support email address at the end of the release notes in the Setapp-app.

Cheers,
Matthias
