### ISSUE TITLE
Battery Health Management

### ISSUE THREAD

**Issue by ohsamlee** [davidwernhart/AlDente#39]
Do you recommend that we turn off Apple's "Battery Health Management" feature while using your app, or does it not matter?

I just purchase a 2020 MacBook Pro 16in" and I found this feature is turned on by default.

Thank you!

**Comment by DevNulPavel** [comment]
I think it is recommended to disable, it will fix probable problems and conflicts between system logic and app

**Comment by mariomeissner** [comment]
Also interested in hearing more opinions.
@davidwernhart do you have any stance on this?

**Comment by TheMazus** [comment]
Hi guys,
some people noticed some inconveniences with Battery Health Management enabled. Therefore, we definitely recommend disabling it.
