### ISSUE TITLE
The new 16 m1 max MacBook pro

### ISSUE THREAD

**Issue by elihollander** [davidwernhart/AlDente#410]
Will you be supporting the new 16 m1 max MacBook pro (along with the updated operating system from Apple)?

BTW, I have been using AlDente Pro for a while now and I love it... It feels great to know that the battery is truly protected by the optimal charging strategy.

Thank you,

**Comment by ange335** [comment]
General Question: Should I disable the integrated macOS Battery management? (optimised charging to 80%) I´m using the new MacBook Pro 14" with M1 Pro processor! (got it yesterday, an incredible machine) 

**PS:** I browsed the web for years already to find your service, lol... **DO MORE ADVERTISING**, this is great and I would wish I found that here earlier... My MacBook Air with M1 Battery is at 89% now after 11 months because of being plugged in all the time... :/

**Comment by MatthiasKerbl** [comment]
> Hi @MatthiasKerbl
> 
> First of all thank you for making this app and responding promptly to the users! I was just wondering if I'm correct in understanding that the new 14" and 16" M1 Pro/Max MBPs are not yet officially supported, seeing that they are not on the "Is My MacBook Supported" list in the [FAQ](https://apphousekitchen.com/faq/)?
> 
> Many thanks!

Hi @jameszhan9592,

You are correct, the new 14" and 16" M1 Pro/Max MBPs are currently not supported.
However, we are in the process of testing AlDente on the new MacBooks and so far it looks good. If no bugs will arise until our testing is finished, we will definitely add support to the new MacBooks.

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment]
> General Question: Should I disable the integrated macOS Battery management? (optimised charging to 80%) I´m using the new MacBook Pro 14" with M1 Pro processor! (got it yesterday, an incredible machine)
> 
> **PS:** I browsed the web for years already to find your service, lol... **DO MORE ADVERTISING**, this is a more than useful tool and I would wish I found it earlier... My MacBook Air with M1 Battery is at 89% now after 11 months because of being plugged in all the time... :/
> 
> Greetings from Austria to Austria :)

Hi @ange335,

You should definitely deactivate the integrated macOS Battery management since it will interfere with AlDente.

I am glad you like our little app and we will definitely increase our marketing so more people can potentially increase their battery longevity.

Greetings to a fellow Austrian,
Matthias

**Comment by elihollander** [comment]
Just to let you know, I have the new M1 Pro Max with 64 GB ram. I have it now for about five days.

So far, AlDente is working perfectly, with no issues that I can see. I have restarted the computer several times, and AlDente kicked in as it should. I have not had a chance to see if the “sailing” feature works because the Pro Max is so energy efficient and the power supply so powerful that the charge level has only gone down 1% in three days of some intensive work.

If there are any specific things you would like me to test, I will be happy to do so.

Eli

_____________________________________________________________
Eli Hollander, Professor Emeritus 831.464.0616 (voice)
Film and Digital Media Department
University of California, Santa Cruz
Santa Cruz, CA 95064
***@***.***
http://film.ucsc.edu/

_____________________________________________________________

**Comment by MatthiasKerbl** [comment]
Hi everyone,

I have good news for you:

The new MacBook Pro (16-inch, M1 Pro/Max, 2021) and MacBook Pro (14-inch, M1 Pro/Max, 2021) are now officially fully supported by AlDente.

Cheers,
Matthias

**Comment by dstyp** [comment]
I'm having multiple issues now after a few days of using my new machine.

1. Al Dente doesn't start when machine boots. I tried reinstalling etc. This is the biggest issue.
2. The menu is still an issue. It's of course due to the notch and Apple's api. I've had to reorganize the icons in the bar to have aldente show up as I'm running istat etc. A good workaround for apps would be to offer a way to trigger the ui without a visible menu icon I guess?
3. Weird reinstall loop when downloading the pro version. I downloaded the dmg of the latest build from github and it seems to become the pro version and recall my credentials. However, when using the download link in the original purchase email it downloads the first al dente pro version and then it gets stuck in a weird loop

**Comment by MatthiasKerbl** [comment]
> I'm having multiple issues now after a few days of using my new machine. Not sure if I should write here or type up a new issue.
> 
> 1. Al Dente doesn't start when machine boots. I tried reinstalling etc. This is the biggest issue.
> 2. The menu is still an issue. It's of course due to the notch and Apple's api. I've had to reorganize the icons in the bar to have aldente show up as I'm running istat etc. A good workaround for apps would be to offer a way to trigger the ui without a visible menu icon I guess?
> 3. Weird reinstall loop when downloading the pro version. I downloaded the dmg of the latest build from github and it seems to become the pro version and recall my credentials which is great but I didn't know (the pro binary also originally had another name in the apps folder). However, when using the download link in the original purchase email it downloads the first al dente pro version and then it gets stuck in a weird loop

Hi @dstyp,

I am sorry that you experience some issues with AlDente.

1. We have not experienced this issue at all. Please share more information about this. Does it happen every time or just sometimes? Was it like that from the beginning? Did you try to deactivate/activate launch at login for a while?
2. It is kind of annoying that Apple chose to do it like that, hopefully, they will change it with an update. We are thinking of implementing the option of showing AlDente in the Dock as well.
3. We updated all download links by now. Therefore, this issue should not occur anymore.

Cheers,
Matthias

**Comment by dstyp** [comment]
> > I'm having multiple issues now after a few days of using my new machine. Not sure if I should write here or type up a new issue.
> > 
> > 1. Al Dente doesn't start when machine boots. I tried reinstalling etc. This is the biggest issue.
> > 2. The menu is still an issue. It's of course due to the notch and Apple's api. I've had to reorganize the icons in the bar to have aldente show up as I'm running istat etc. A good workaround for apps would be to offer a way to trigger the ui without a visible menu icon I guess?
> > 3. Weird reinstall loop when downloading the pro version. I downloaded the dmg of the latest build from github and it seems to become the pro version and recall my credentials which is great but I didn't know (the pro binary also originally had another name in the apps folder). However, when using the download link in the original purchase email it downloads the first al dente pro version and then it gets stuck in a weird loop
> 
> Hi @dstyp,
> 
> I am sorry that you experience some issues with AlDente.
> 
>     1. We have not experienced this issue at all. Please share more information about this. Does it happen every time or just sometimes? Was it like that from the beginning? Did you try to deactivate/activate launch at login for a while?
> 
>     2. It is kind of annoying that Apple chose to do it like that, hopefully, they will change it with an update. We are thinking of implementing the option of showing AlDente in the Dock as well.
> 
>     3. We updated all download links by now. Therefore, this issue should not occur anymore.
> 
> 
> Cheers, Matthias

Hello @MatthiasKerbl ,

Thanks for the reply and engaging. And thanks for making such an awesome app!

1. Ok, weird. I will try some more. I haven't restarted too much but will look in to it when I have the possibility.
2. Dock would be awesome! Hopefully Apple enhances the menu bar to include some kind of smart collapsing/expansion thing as well
3. 👍

**Comment by MatthiasKerbl** [comment]
> > > I'm having multiple issues now after a few days of using my new machine. Not sure if I should write here or type up a new issue.
> > > 
> > > 1. Al Dente doesn't start when machine boots. I tried reinstalling etc. This is the biggest issue.
> > > 2. The menu is still an issue. It's of course due to the notch and Apple's api. I've had to reorganize the icons in the bar to have aldente show up as I'm running istat etc. A good workaround for apps would be to offer a way to trigger the ui without a visible menu icon I guess?
> > > 3. Weird reinstall loop when downloading the pro version. I downloaded the dmg of the latest build from github and it seems to become the pro version and recall my credentials which is great but I didn't know (the pro binary also originally had another name in the apps folder). However, when using the download link in the original purchase email it downloads the first al dente pro version and then it gets stuck in a weird loop
> > 
> > 
> > Hi @dstyp,
> > I am sorry that you experience some issues with AlDente.
> > ```
> > 1. We have not experienced this issue at all. Please share more information about this. Does it happen every time or just sometimes? Was it like that from the beginning? Did you try to deactivate/activate launch at login for a while?
> > 
> > 2. It is kind of annoying that Apple chose to do it like that, hopefully, they will change it with an update. We are thinking of implementing the option of showing AlDente in the Dock as well.
> > 
> > 3. We updated all download links by now. Therefore, this issue should not occur anymore.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Cheers, Matthias
> 
> Hello @MatthiasKerbl ,
> 
> Thanks for the reply and engaging. And thanks for making such an awesome app!
> 
> 1. Ok, weird. I will try some more. I haven't restarted too much but will look in to it when I have the possibility.
> 2. Dock would be awesome! Hopefully Apple enhances the menu bar to include some kind of smart collapsing/expansion thing as well
> 3. 👍

Thank you for your positive feedback and I am glad you enjoy our little tool.

1. We could actually find a bug that resulted in launch at login not working properly for some users. A fix for this will be released in the next update.

Cheers,
Matthias
