### ISSUE TITLE
Updater shows blank paper icon.

### ISSUE THREAD

**Issue by dbz2k** [davidwernhart/AlDente#416]
<img width="259" alt="Screen Shot 2021-10-24 at 1 06 40 PM" src="https://user-images.githubusercontent.com/1914952/138604863-e4710bcf-ce63-4c7c-b02b-e770e2f1c8c7.png">

**Comment by MatthiasKerbl** [comment]
Hi @dbz2k,

we just released AlDente 1.12 which has a fix for the bug you mentioned.
You can download the newest version here (https://github.com/davidwernhart/AlDente/releases) or just update your current version.

Cheers,
Matthias
