### ISSUE TITLE
Doesn't appear in the menu bar

### ISSUE THREAD

**Issue by PavelZeger** [davidwernhart/AlDente#419]
Hi.
After installation of the macOs 12 Monterrey and reinstallation of the Al Dente, the program doesn't appear in the menu bar, I cannot open it to reconfigure etc.

**Comment by MatthiasKerbl** [comment]
Hi @PavelZeger,

Do you still have this issue with AlDente?

Cheers,
Matthias

**Comment by PavelZeger** [comment]
@MatthiasKerbl Currently no.
