### ISSUE TITLE
How does Sailing Mode work?

### ISSUE THREAD

**Issue by PearApple151** [davidwernhart/AlDente#421]
So I read this other page that explained sailing mode, and thought maybe it was for me, until I got to example 2.

What I want is for the ability to set an upper limit and a lower limit. I want to set the upper limit to 75% and the lower limit to 50%. no matter how many times I plug and unplug my laptop, I want the computer to run on AC power until it drops below 50%. when it finally drops below 50%, I would like it to then charge to 75%. if I unplug my computer to use in the other room,  if it's charge drops to 65%, when I plug it back in, I want it to stay at 65%. then the next day when I unplug it again, if it drops to 52%, I want it to stay at 52% when I plug it back in. and then finally when it drops below 50% it can recharge to 75%. 

Sailing mode looked like the option I wanted, but then at the bottom of the page it says something like when you unplug the computer and plug it back in, it will charge to 75% before it consider whether it is already above that lower limit.

For now I'm adjusting the limit between 50% and 75% manually, but if Sailing mode works the way I think it does, could an option like this be added?

**Comment by PearApple151** [comment]
> Hi @PearApple151,
> 
> Which version of AlDente do you use? The newest version of AlDente (1.08) has the updated version of the Sailing Mode, which "survives" being unplugged.
> 
> Cheers, Matthias

Really? I just installed it. so if I purchase it, and I activate sailing mode, it won't charge to the upper limit until it reaches the lower limit even if I unplug it for an hour?

**Comment by MatthiasKerbl** [comment]
> > Hi @PearApple151,
> > Which version of AlDente do you use? The newest version of AlDente (1.08) has the updated version of the Sailing Mode, which "survives" being unplugged.
> > Cheers, Matthias
> 
> Really? I just installed it. so if I purchase it, and I activate sailing mode, it won't charge to the upper limit until it reaches the lower limit even if I unplug it for an hour?

If it does not reach the lower limit or lower while it is unplugged, it will not charge to the upper limit when you plug it in.

**Comment by PearApple151** [comment]
> > > Hi @PearApple151,
> > > Which version of AlDente do you use? The newest version of AlDente (1.08) has the updated version of the Sailing Mode, which "survives" being unplugged.
> > > Cheers, Matthias
> > 
> > 
> > Really? I just installed it. so if I purchase it, and I activate sailing mode, it won't charge to the upper limit until it reaches the lower limit even if I unplug it for an hour?
> 
> If it does not reach the lower limit or lower while it is unplugged, it will not charge to the upper limit when you plug it in.

awesome. so I won't have to keep manually changing it from 75 to 50 and back again. I'm ready to give my money. thanks!

**Comment by PearApple151** [comment]
> > > Hi @PearApple151,
> > > Which version of AlDente do you use? The newest version of AlDente (1.08) has the updated version of the Sailing Mode, which "survives" being unplugged.
> > > Cheers, Matthias
> > 
> > 
> > Really? I just installed it. so if I purchase it, and I activate sailing mode, it won't charge to the upper limit until it reaches the lower limit even if I unplug it for an hour?
> 
> If it does not reach the lower limit or lower while it is unplugged, it will not charge to the upper limit when you plug it in.

awe man. It caps the difference at 20%??? why? I want to do 50 - 75. or 45- 75. haha

**Comment by MatthiasKerbl** [comment]
> > > > Hi @PearApple151,
> > > > Which version of AlDente do you use? The newest version of AlDente (1.08) has the updated version of the Sailing Mode, which "survives" being unplugged.
> > > > Cheers, Matthias
> > > 
> > > 
> > > Really? I just installed it. so if I purchase it, and I activate sailing mode, it won't charge to the upper limit until it reaches the lower limit even if I unplug it for an hour?
> > 
> > 
> > If it does not reach the lower limit or lower while it is unplugged, it will not charge to the upper limit when you plug it in.
> 
> awesome. so I won't have to keep manually changing it from 75 to 50 and back again. I'm ready to give my money. thanks!

Thanks a lot!

**Comment by MatthiasKerbl** [comment]
> > > > Hi @PearApple151,
> > > > Which version of AlDente do you use? The newest version of AlDente (1.08) has the updated version of the Sailing Mode, which "survives" being unplugged.
> > > > Cheers, Matthias
> > > 
> > > 
> > > Really? I just installed it. so if I purchase it, and I activate sailing mode, it won't charge to the upper limit until it reaches the lower limit even if I unplug it for an hour?
> > 
> > 
> > If it does not reach the lower limit or lower while it is unplugged, it will not charge to the upper limit when you plug it in.
> 
> awe man. It caps the difference at 20%??? why? I want to do 50 - 75. or 45- 75. haha

We could definitely increase it again. We will think about it.

Cheers,
Matthias
