### ISSUE TITLE
MBP 2017 Intel - Several bugs in 1.08 and Monterey

### ISSUE THREAD

**Issue by tosbsas** [davidwernhart/AlDente#424]
Hi there

I do see behavior of Al DentePro 1.08 in Monterey I didn't see in 1.07 and BigSur

1. Battery is set to max 80% but I get always mor than 80, floating is set to 5%
2. After using topUp machine charged to 100% instead of 80% it was set to

Please fix

**Comment by MatthiasKerbl** [comment]
> Hi there
> 
> I do see behavior of Al DentePro 1.08 in Monterey I didn't see in 1.07 and BigSur
> 
> 1. Battery is set to max 80% but I get always mor than 80, floating is set to 5%
> 2. After using topUp machine charged to 100% instead of 80% it was set to
> 
> Please fix

Hi @tosbsas,

1. I am currently not experiencing any problems in this regard with my MBP 2016 Intel. In which situations exactly does your MacBook charge above the Charge Limit?
2. That’s definitely a bug. Thanks for pointing it out, we will fix it with the next update!

Cheers,
Matthias

**Comment by tosbsas** [comment]
1. hm, I do See values higher than 78 with 78 set as limit. Normal use

2. good to know that its really a bug - hoping for the fix
