### ISSUE TITLE
Will be 100% charged after two days of standby

### ISSUE THREAD

**Issue by wyfang** [davidwernhart/AlDente#427]
I keep my laptop in the office and if I don't work on Saturday and Sunday, I turn on my computer every Monday and it will be filled to 100%
![image](https://user-images.githubusercontent.com/17900420/139608689-8411f049-3c4f-4301-b487-35440d18fc84.png)
![image](https://user-images.githubusercontent.com/17900420/139608702-24d9359b-eba1-4e4c-8f93-c8fe06d190ff.png)
![image](https://user-images.githubusercontent.com/17900420/139608719-843c9f08-323b-42e1-8741-9862f2d83313.png)

**Comment by MatthiasKerbl** [comment]
Hi @wyfang,

Which MacBook model do you have?

Cheers,
Matthias

**Comment by wyfang** [comment]
> Hi @wyfang,
> 
> Which MacBook model do you have?
> 
> Cheers, Matthias

macbook pro 2016
![image](https://user-images.githubusercontent.com/17900420/139651239-1371d97d-1ec7-4988-8baf-755029f36a2b.png)

**Comment by wyfang** [comment]
![image](https://user-images.githubusercontent.com/17900420/139651370-2f9907c8-dc2b-4e23-95bf-22fefb74f7e4.png)
It looks like I need to reset the click to 55%.

**Comment by MatthiasKerbl** [comment]
The problem is that your MacBook is in sleep or powered off during the weekend and AlDente can't control the charging behavior while your MacBook is in sleep or powered off.
You should activate the features "Stop charging when sleeping" and "Stop charging when powered off". With those features activated, AlDente will stop charging right before your MacBook goes into sleep or before it gets powered off. Therefore, your MacBook will stay at the charge level it had right before it went into sleep or before it got powered off.

Cheers,
Matthias

**Comment by wyfang** [comment]
> The problem is that your MacBook is in sleep or powered off during the weekend and AlDente can't control the charging behavior while your MacBook is in sleep or powered off. You should activate the features "Stop charging when sleeping" and "Stop charging when powered off". With those features activated, AlDente will stop charging right before your MacBook goes into sleep or before it gets powered off. Therefore, your MacBook will stay at the charge level it had right before it went into sleep or before it got powered off.
> 
> Cheers, Matthias

I tried activating "stop charging when sleeping" and "stop charging when switching off" and a day has passed and the battery still has 2% left. I have absolutely no idea what to do. When I switch it on, the battery becomes 2% after one day, when I switch it off, it becomes 100% after two days.
![截屏2021-11-03 上午9 05 33](https://user-images.githubusercontent.com/17900420/139983334-921b9498-b26a-4366-be6a-be2b0922af47.png)
![截屏2021-11-03 上午9 05 16](https://user-images.githubusercontent.com/17900420/139983368-9a7e9050-4884-443e-b14a-cda02696c98d.png)
![截屏2021-11-03 上午9 13 48](https://user-images.githubusercontent.com/17900420/139983634-0ab3f847-2a35-4453-9593-12f3bda71974.png)

**Comment by MatthiasKerbl** [comment]
Hi @wyfang,

AlDente will not charge your MacBook when it is in sleep or powered off. Instead, it will just hold the current charge limit when the features "Stop charging when sleeping" and "Stop charging when powered off" are activated.

Please read our detailed explanation about those two features on our blog:

- https://apphousekitchen.com/feature-explanation-stop-charging-when-powered-off-app-closed/
- https://apphousekitchen.com/feature-explanation-stop-charging-when-sleeping/

Cheers,
Matthias
