### ISSUE TITLE
Right Click on App Logo sets Percentege to 100% (Bug or Feature?)

### ISSUE THREAD

**Issue by the-please-is-mine** [davidwernhart/AlDente#428]
Hi Community & AlDente Team,

When I do a right click on the AlDente menu item in the bar where the clock is, it then moves/sets the percentage regulator up to 100%.
Is this on purpose or did I discover a bug? :-) 

Greetings and keep up the good work!

---
AlDente Pro 1.08
macOS Monterey 12.0.1

**Comment by MatthiasKerbl** [comment]
> Hi Community & AlDente Team,
> 
> When I do a right click on the AlDente menu item in the bar where the clock is, it then moves/sets the percentage regulator up to 100%. Is this on purpose or did I discover a bug? :-)
> 
> Greetings and keep up the good work!
> 
> AlDente Pro 1.08 macOS Monterey 12.0.1

Hi @the-please-is-mine,

This is actually a feature called "Shortcuts". :)
A right-click on the AlDente icon alternates between setting the charge limit to 100% and pausing at the current SoC.

Cheer,
Matthias
