### ISSUE TITLE
Sailing mode difference could not be set to greater than 20

### ISSUE THREAD

**Issue by sanddudu** [davidwernhart/AlDente#433]
Device: MacBook Pro 14 2021
OS: macOS Monterey 12.0.1
Version: AlDente Pro 1.08

https://user-images.githubusercontent.com/1650692/140042926-ac8ea143-7ba5-4bc2-9480-23771bcf31e3.mov

**Comment by MatthiasKerbl** [comment]
Hi @sanddudu,

We will increase the range with the next update.

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @sanddudu,

We have just released version 1.09 of AlDente which allows you to increase the Sailing Mode range as much as you want.

Cheers,
Matthias
