### ISSUE TITLE
Charges Past Specified Level

### ISSUE THREAD

**Issue by abeldemoz** [davidwernhart/AlDente#439]
I have a 13-inch 2020 MacBook Pro. When I use the 61W power adapter, everything is fine. When I use a 96W power adapter, it charges past the limit I specified. I set the limit to 80% when connected to the 96W adapter and it charged to 91%.

**Comment by MatthiasKerbl** [comment]
Hi @abeldemoz,

Are you certain that you get different behavior with different power adapters? Or could it be that your MacBook went into sleep or got powered off while you used it?
Since AlDente's capabilities of controlling charging while your MacBook is in sleep or powered off is highly limited.
You can read more about this topic on our blog:

- https://apphousekitchen.com/feature-explanation-stop-charging-when-sleeping/
- https://apphousekitchen.com/feature-explanation-stop-charging-when-powered-off-app-closed/

I have always different charging adapters with different charging powers in use and have never experienced issues with AlDente while using different charging adapters.

Cheers,
Matthias

**Comment by abeldemoz** [comment]
This behaviour occurs even when the MacBook Pro is awake and in use. The 61W doesn’t charge past the charging limit, whereas the 96W frequently charges past the charging limit.

**Comment by MatthiasKerbl** [comment]
> This behaviour occurs even when the MacBook Pro is awake and in use. The 61W doesn’t charge past the charging limit, whereas the 96W frequently charges past the charging limit.

Do you have an Intel or Apple Silicon M1 MacBook?

**Comment by abeldemoz** [comment]
Intel MacBook Pro 13" 2020 i5 2.0GHz 4-core 16GB RAM 512GB SSD

**Comment by MatthiasKerbl** [comment]
Hi @abeldemoz,

Unfortunately, I am currently not able to reproduce this issue. I have tried it on multiple Intel-based MacBooks with various power adapters and charging past the charge limit never occurred.
Do you have any recommendations on how I can reproduce this bug?

**Comment by tosbsas** [comment]
I do See the Same but Not this far up. Set to 80 y get 81 or 82 After  several days being connected. 

Its set to 80 Max. Didnt See That be for Monterey 

Intel mbp 2017. 

Only thing I do is hibernate or a restart. I thought it might be the restart but anyway it should go down to 80, Right?

**Comment by abeldemoz** [comment]
> Hi @abeldemoz,
> 
> Unfortunately, I am currently not able to reproduce this issue. I have tried it on multiple Intel-based MacBooks with various power adapters and charging past the charge limit never occurred. Do you have any recommendations on how I can reproduce this bug?

I'm not sure how to reproduce it by using a power adapter. I also experience this issue on occasion when using the MacBook Pro in clamshell mode when connected to a monitor via USB-C. The monitor charges the MBP via the USB-C cable. I see it go past the specified limit while I'm using it – the computer is not asleep.

**Comment by MatthiasKerbl** [comment]
> > Hi @abeldemoz,
> > Unfortunately, I am currently not able to reproduce this issue. I have tried it on multiple Intel-based MacBooks with various power adapters and charging past the charge limit never occurred. Do you have any recommendations on how I can reproduce this bug?
> 
> I'm not sure how to reproduce it by using a power adapter. I also experience this issue on occasion when using the MacBook Pro in clamshell mode when connected to a monitor via USB-C. The monitor charges the MBP via the USB-C cable. I see it go past the specified limit while I'm using it – the computer is not asleep. I'm not sure if this will help, but maybe the bug could be a result of different wattages from different power supplies. I'm using AlDente-Pro.

Do you have the feature Heat Protection activated? We found a bug in the current version which results in charging above the charge limit for some users if Heat Protection is activated. If you had Heat Protection enabled, you could try it again with Heat Protection disabled.

**Comment by tosbsas** [comment]
Will try

**Comment by tosbsas** [comment]
I did turn off heat protection, mbp charged to 80% (limit being set by Ardente) and after a while its 81 :-((

**Comment by abeldemoz** [comment]
> > > Hi @abeldemoz,
> 
> > > Unfortunately, I am currently not able to reproduce this issue. I have tried it on multiple Intel-based MacBooks with various power adapters and charging past the charge limit never occurred. Do you have any recommendations on how I can reproduce this bug?
> 
> > 
> 
> > I'm not sure how to reproduce it by using a power adapter. I also experience this issue on occasion when using the MacBook Pro in clamshell mode when connected to a monitor via USB-C. The monitor charges the MBP via the USB-C cable. I see it go past the specified limit while I'm using it – the computer is not asleep. I'm not sure if this will help, but maybe the bug could be a result of different wattages from different power supplies. I'm using AlDente-Pro.
> 
> 
> 
> Do you have the feature Heat Protection activated? We found a bug in the current version which results in charging above the charge limit for some users if Heat Protection is activated. If you had Heat Protection enabled, you could try it again with Heat Protection disabled.

Yes I have heat protection enabled all of the time. Do you have a timeline for fixing this bug?

**Comment by MatthiasKerbl** [comment]
> > Do you have the feature Heat Protection activated? We found a bug in the current version which results in charging above the charge limit for some users if Heat Protection is activated. If you had Heat Protection enabled, you could try it again with Heat Protection disabled.
> 
> Yes, I have Heat Protection enabled all of the time. Do you have a timeline for fixing this bug?

We are currently testing a beta version of AlDente which already has the Heat Protection fix implemented. If everything is going well, we will release it soon.

**Comment by MatthiasKerbl** [comment]
> > Do you have the feature Heat Protection activated? We found a bug in the current version which results in charging above the charge limit for some users if Heat Protection is activated. If you had Heat Protection enabled, you could try it again with Heat Protection disabled.
> 
> Yes, I have Heat Protection enabled all of the time. Do you have a timeline for fixing this bug?

Hi @abeldemoz,

We have just released the new version of AlDente (1.10). https://github.com/davidwernhart/AlDente/releases/
It has a fix for the Heat Protection bug and please try this version, it might have fixed your issue regarding charging past the Charge Limit with high power chargers.

Cheers,
Matthias

**Comment by jameszhan9592** [comment]
Hi @MatthiasKerbl ,

I'm on 1.10, but the battery still always gets charged 1 or 2 percent past the specified percentage. Sometimes the charging would even pause at 2% **below** the specified percentage.

Any idea what caused this and how to resolve it?

Best,
James

**Comment by tosbsas** [comment]
Same here

**Comment by MatthiasKerbl** [comment]
> Hi @MatthiasKerbl ,
> 
> I'm on 1.10, but the battery still always gets charged 1 or 2 percent past the specified percentage. Sometimes the charging would even pause at 2% **below** the specified percentage.
> 
> Any idea what caused this and how to resolve it?
> 
> Using an M1 Max MBP, macOS 12.0.1.
> 
> Best, James

Hi @jameszhan9592,

I would say, 1,2,3% is in the margin of error since the battery percentage is not the most accurate number in macOS.

Cheers,
Matthias

**Comment by tosbsas** [comment]
It definitivly is. But it was more exacto in earlier versiona 




______________________________
Ruben Gutknecht
Lima, Perú  🇵🇪 
Cel: +51-99349-1515
Voice/Fax: 49 (0) 721-151-379204
http://telegram.me/tosbsas
paypal.me/RubenGutknecht
***@***.***

**Comment by reednaaxeelaa** [comment]
Mine continues charging past the specified threshold.
<img width="512" alt="screenshot" src="https://user-images.githubusercontent.com/58189177/142992307-4342be11-bb97-41c3-a6a2-7d806dbc938e.png">
Coconut battery shows the MacBook currently charging at ~28W, which is the charging rate at when it is close to full.

Sometimes it turns on and sometimes it turns off. I am not sure what triggers it. Over time, it gradually charges fully up. This is while the computer is awake.
I have tried reinstalling the helper application.



Macbook 2021 14 M1 pro.

**Comment by MatthiasKerbl** [comment]
> Mine continues charging past the specified threshold. <img alt="screenshot" width="512" src="https://user-images.githubusercontent.com/58189177/142992307-4342be11-bb97-41c3-a6a2-7d806dbc938e.png"> Coconut battery shows the MacBook currently charging at ~28W, which is the charging rate at when it is close to full.
> 
> Sometimes it turns on and sometimes it turns off. I am not sure what triggers it. Over time, it gradually charges fully up. This is while the computer is awake. I have tried reinstalling the helper application.
> 
> Macbook 2021 14" M1 pro.

Hi @reednaaxeelaa,

Do you have "Optimized battery charging" in the macOS preferences disabled?

Cheers,
Matthias

**Comment by reednaaxeelaa** [comment]
>
> Hi @reednaaxeelaa,
> 
> Do you have "Optimized battery charging" in the macOS preferences disabled?
> 
> Cheers, Matthias

I do not.

**Comment by MatthiasKerbl** [comment]
> > Hi @reednaaxeelaa,
> > Do you have "Optimized battery charging" in the macOS preferences disabled?
> > Cheers, Matthias
> 
> I do not.

In order for AlDente to work, you have to disable this setting.

**Comment by reednaaxeelaa** [comment]
Ohh, I am sorry. I misread what you wrote. I do not have the setting enabled.

**Comment by MatthiasKerbl** [comment]
> Ohh, I am sorry. I misread what you wrote. I do not have the setting enabled.

Did you try a full reinstall of AlDente?

**Comment by MatthiasKerbl** [comment]
> I have a 13-inch 2020 MacBook Pro. When I use the 61W power adapter, everything is fine. When I use a 96W power adapter, it charges past the limit I specified. I set the limit to 80% when connected to the 96W adapter and it charged to 91%.

Hi @abeldemoz,

Do you still experience this issue with our newest version?
