### ISSUE TITLE
Battery getting hot 

### ISSUE THREAD

**Issue by hashsi99** [davidwernhart/AlDente#440]
Used AlDente on an intel Mac and never had a problem (classic). 

Just downloaded and started using on a m1 MacBook Pro. Set limit to 77% and it works as it should. However my battery temp (and laptop) are getting warmer then Ever before. I uninstalled and temps are back to normal.  

Is this normal??  I checked the CPU usage with aldente installed and nothing stood out. I was using 1.08 when the overheating started. 

Thanks

**Comment by MatthiasKerbl** [comment]
Hi @hashsi99,

AlDente should definitely not cause heat issues with your MacBook because it uses less than 1% of CPU resources.
You could try installing our latest version 1.09, maybe it will fix your issue.

Cheers,
Matthias

**Comment by hashsi99** [comment]
I’ll give it a try. Thanks for the quick response. 

The pro does have some battery protection though correct?

**Comment by MatthiasKerbl** [comment]
> The pro does have some battery protection though correct?

What exactly do you mean?

**Comment by hashsi99** [comment]
https://apphousekitchen.com/feature-explanation-heat-protection/

**Comment by MatthiasKerbl** [comment]
> https://apphousekitchen.com/feature-explanation-heat-protection/

Yes, AlDente Pro has the Heat Protection feature which will pause charging when the temperature of the battery is too hot.

**Comment by MatthiasKerbl** [comment]
Hi @hashsi99,

Do you still encounter any heat related issues with AlDente?

Otherwise, I would close this issue.

Cheers,
Matthias

**Comment by hashsi99** [comment]
you can close it out, I've yet to purchase the pro yet.  But I will soon.  Thanks for the help!
