### ISSUE TITLE
[Feature Request]Would it be possible to have maximum charge % respond to an external app?

### ISSUE THREAD

**Issue by DamonHD** [davidwernhart/AlDente#444]
Hi,

It would be very useful to have AlDente periodically poll for a specified external file (or URL), and if it exists and contains a single integer between (say) 20 and 100 use that as the charge limit.

That would let me auto-adjust adjust my MacBook Air to play better with my off-grid system, and also with the grid (eg using a lower max charge level when the grid is dirty).

See:
    http://www.earth.org.uk/Hey-Siri-Help-Flatten-The-Duck.html
    http://www.earth.org.uk/_gridCarbonIntensityGB.html

I am in the UK and run the live intensity calculator in the second link.  I could provide a simple URL for the above scheme that other GB grid users with AlDente could poll every few minutes.

Rgds

Damon

PS See also #445 .

**Comment by MatthiasKerbl** [comment]
Hi @DamonHD,

This looks very interesting as well. We will also discuss it and I will come back to you.

Cheers,
Matthias

**Comment by DamonHD** [comment]
See https://twitter.com/andysc/status/1554378086459785217
