### ISSUE TITLE
macbook pro 2015, intel mode, charge past limit by ~7

### ISSUE THREAD

**Issue by tutejszy** [davidwernhart/AlDente#448]
As in the title, I have MB pro 15 mid 2015. Big Sur on the board. Seems that Al Dente is always adding around 7 to the requested charge limit. It is, when I set charge limit to 80 it charges to 87. If I set it to 73 it charges to 80.

Interesting detail: After I set charge limit to 80 and updated to new version it showed charge limit 87. But when I changed it to desired 80 it was stlill charging to 87. I believe right after update it somehow show correct value.

This behavior was also seen on MB pro 2013.

I am willing to help debug the issue.

**Comment by MatthiasKerbl** [comment]
> As in the title, I have MB pro 15 mid 2015. Big Sur on the board. Seems that Al Dente is always adding around 7 to the requested charge limit. It is, when I set charge limit to 80 it charges to 87. If I set it to 73 it charges to 80.
> 
> Interesting detail: After I set charge limit to 80 and updated to new version it showed charge limit 87. But when I changed it to desired 80 it was stlill charging to 87. I believe right after update it somehow show correct value.
> 
> This behavior was also seen on MB pro 2013.
> 
> I am willing to help debug the issue.

Hi @tutejszy,

Due to the Intel Mode using the "real" battery scale and not the one macOS is showing you, the charge limit will always be off a little bit.
You can read more about the Intel Mode in our blog here: https://apphousekitchen.com/feature-explanation-intel-mode/

Cheers,
Matthias
