### ISSUE TITLE
Wrong email used to buy Pro version

### ISSUE THREAD

**Issue by ruslantrachuk** [davidwernhart/AlDente#449]
Hi guys,
It's funny, but I entered the wrong email in my purchase. And just want to clarify how to obtain my license  ;-). Since I have not received a payment confirmation email, I don't have email I should use to contact your premium support

**Comment by MatthiasKerbl** [comment]
> Hi guys, It's funny, but I entered the wrong email in my purchase. And just want to clarify how to obtain my license ;-). Since I have not received a payment confirmation email, I don't have email I should use to contact your premium support

Hi @ruslantrachuk,

Please send us a short email to news@apphousekitchen.com with the wrong email address you used and we will resend the confirmation emails to the correct email address.

Cheers,
Matthias
