### ISSUE TITLE
need to switch off Automatic Graphics Switching while using AlDente

### ISSUE THREAD

**Issue by ale-dd** [davidwernhart/AlDente#452]
I am hitting an issue when running AlDente and staying away from my laptop for some time. Upon returning, the graphics acceleration is all messed up and I see tiles of windows from the background in front of what is supposed to be in the foreground. Resetting the SMC didn't seem to help, but switching off Automatic Graphics Switching seems to solve the problem. I can't prove with 100% certainty it's got to do with something related to the AlDente installation, but I had never had this issue before.

I'm on AlDente Pro 1.09, on Big Sur 11.6.1, running on a 16" mac book pro (2019) with Core i9 and the AMD Radeon Pro 5300M 4GB.

The settings I have enabled are:
- sailing mode
- heat protection

The settings I have disabled are:
- stop charging when sleeping
- stop charging when powered off
- intel mode 

I can provide the debug file, if it helps.
Thank you!

**Comment by MatthiasKerbl** [comment]
Hi @ale-dd,

Did you look into this further and have any new findings if it is related to AlDente?

Cheers,
Matthias
