### ISSUE TITLE
Haven't receive license email

### ISSUE THREAD

**Issue by williamjin1992** [davidwernhart/AlDente#454]
Hi, I made the purchase of AlDente Pro several hours ago, and the credit card notification showed that the the deal is done. But I haven't receive any emails yet (I have check the junk mail box too), I'm wondering what's wrong with my order?

**Comment by MatthiasKerbl** [comment]
> Hi, I made the purchase of AlDente Pro several hours ago, and the credit card notification showed that the the deal is done. But I haven't receive any emails yet (I have check the junk mail box too), I'm wondering what's wrong with my order?

Hi @williamjin1992,

I can check your purchase, which email address did you use to buy AlDente Pro?

Cheers,
Matthias
