### ISSUE TITLE
Wrong battery limit with 2017 Macbook, Big Sur

### ISSUE THREAD

**Issue by arnstein99** [davidwernhart/AlDente#46]
I have a 13-inch Macbook (not Pro) from 2017. Upgraded to Big Sur yesterday. I discovered AlDente today and I tried it out. It installed without a hitch, but it does not limit battery charging. With my battery at 68%, I configured AlDente to max out at 50%. The machine's battery is now at 74%.

Update: my machine's battery level has been at 74% all day. Therefore, AlDente is having a beneficial effect. The issue then is that the level should be stuck at 50%.

Is there anything I can do to help the developer troubleshoot this? Some log file maybe?

**Comment by shreefentsar** [comment]
try to drain the battery to 45% then it will be limited to 50%
