### ISSUE TITLE
[Bug] PreventSystemSleep Assertions despite disabled Sleep-Charge Features

### ISSUE THREAD

**Issue by sieren** [davidwernhart/AlDente#460]
AlDente seems to prevent system sleep in the most recent version by setting some assertions. This usually takes effect after some time.

Non-Pro version, pretty vanilla configuration. M1 Pro Macbook.

Workaround for now was to downgrade to 1.09

<img width="474" alt="Screenshot 2021-11-16 at 18 53 08" src="https://user-images.githubusercontent.com/5174440/142039231-26467533-f54c-430b-875d-9ec719b99486.png">

```
2021-11-16 18:52:09 +0100
Assertion status system-wide:
   BackgroundTask                 0
   ApplePushServiceTask           0
   UserIsActive                   1
   PreventUserIdleDisplaySleep    1
   PreventSystemSleep             1
   ExternalMedia                  1
   PreventUserIdleSystemSleep     1
   NetworkClientActive            0
Listed by owning process:
   pid 322(powerd): [0x000104bb0001a75c] 01:26:35 PreventUserIdleSystemSleep named: "Powerd - Prevent sleep while display is on"
   pid 322(powerd): [0x0000359500089a24] 19:25:42 ExternalMedia named: "com.apple.powermanagement.externalmediamounted"
   pid 49267(com.apphousekitchen.aldente-pro): [0x000113f700058744] 00:21:34 PreventUserIdleDisplaySleep named: "AlDente-Pro"
   pid 49267(com.apphousekitchen.aldente-pro): [0x000113f700078745] 00:21:34 PreventSystemSleep named: "AlDente-Pro"
```

**Comment by MatthiasKerbl** [comment]
Hi @sieren,

We have just released a new version of AlDente (1.14) which should fix the issues you experienced.
If you still encounter any of the issues after updating, please report back.

Download AlDente 1.14 here (https://github.com/davidwernhart/AlDente/releases) or update within the app.

Thank you for your patience.

Cheers,
Matthias
