### ISSUE TITLE
Make "Disable Sleep Until Charge Limit" work when using top up.

### ISSUE THREAD

**Issue by dbz2k** [davidwernhart/AlDente#467]
I don't know if I am doing something wrong, but the Disable Sleep Until Charge Limit won't keep charging when I use the top up option.

**Comment by MatthiasKerbl** [comment]
Hi @dbz2k,

Thanks for pointing it out, I think it is a bug. We will fix it with the next update.

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @dbz2k,

We just released a new update of AlDente which has a fix for this bug.

Cheers,
Matthias
