### ISSUE TITLE
Prevent AlDente from showing settings when mac starts?

### ISSUE THREAD

**Issue by mjbaldwin** [davidwernhart/AlDente#469]
Love AlDente!

But recently I've been noticing that every time I restart my Mac (M1 Air, Monterey), it shows its popup as if I'd clicked on it, although I hadn't:

![image](https://user-images.githubusercontent.com/160959/142704794-e3a959cb-2250-4541-b824-981597418cd9.png)

(I hide the menubar icon using [Hidden Bar](https://apps.apple.com/us/app/hidden-bar/id1452453066?mt=12) which is why the popup doesn't appear linked to the icon.)

It's slightly annoying to have to click to dismiss it every time I start my Mac, and I don't remember this having always been the case. Is this behavior by design? And if so, is there a way to disable it? I know it's running, I don't need to be reminded every time I restart...

To be clear, I want AlDente to start when my Mac starts and have its icon in the menubar... I just don't want the additional popup to appear.

Thanks!

**Comment by vincentpun** [comment]
It's a new feature that can't be turned off, it looks like... I'd appreciate it if there was a way to!

**Comment by MatthiasKerbl** [comment]
Hi @mjbaldwin,

Due to some people having trouble finding the controls of AlDente we now show the Charge Limiter settings every time AlDente restarts. However, we understand that it is not necessary for everyone that’s why we will implement a setting to turn it off with the next update.

Cheers,
Matthias

**Comment by mjbaldwin** [comment]
Thanks so much @MatthiasKerbl that's great to hear! And thanks again for the awesome app.

**Comment by ammarfatani** [comment]
> Love AlDente!
> 
> But recently I've been noticing that every time I restart my Mac (M1 Air, Monterey), it shows its popup as if I'd clicked on it, although I hadn't:
> 
> ![image](https://user-images.githubusercontent.com/160959/142704794-e3a959cb-2250-4541-b824-981597418cd9.png)
> 
> (I hide the menubar icon using [Hidden Bar](https://apps.apple.com/us/app/hidden-bar/id1452453066?mt=12) which is why the popup doesn't appear linked to the icon.)
> 
> It's slightly annoying to have to click to dismiss it every time I start my Mac, and I don't remember this having always been the case. Is this behavior by design? And if so, is there a way to disable it? I know it's running, I don't need to be reminded every time I restart...
> 
> To be clear, I want AlDente to start when my Mac starts and have its icon in the menubar... I just don't want the additional popup to appear.
> 
> Thanks!

I agree. After a couple of times, it becomes annoying. Also, for some reason when it does show up it always be in the very far left of the screen underneath the Apple logo.

**Comment by MatthiasKerbl** [comment]
Hi everyone,

We just released a new version of AlDente which allows you to disable the automatic popup at launch.

Cheers,
Matthias
