### ISSUE TITLE
blacked out icon in status bar 2020 base model Mac Pro 2 thunderbolt

### ISSUE THREAD

**Issue by hashsi99** [davidwernhart/AlDente#47]
Hello, 

Trying to install this, but I'm getting a black logo in status bar.  Does this mean that this is not working?

If not, what's the proper way to uninstall?  First Mac....

thanks 
<img width="1440" alt="Screen Shot 2020-11-14 at 10 58 23 AM" src="https://user-images.githubusercontent.com/74464830/99152596-52a60b80-2668-11eb-96bd-51ad154a1286.png">

**Comment by dtoniolo** [comment]
Hi @hashsi99, no need to worry: that's the default icon, there's nothing wrong. The original logo was colourful, but some users began complaining and the developer chose to go with black.

It should be working fine. Try to set a percentage (e.g. 80%) and see if changing stops at that level. Please note that in order for it to work you need to start _below_ the desired state of charge.

**Comment by TheMazus** [comment]
> Hello,
> 
> Trying to install this, but I'm getting a black logo in status bar. Does this mean that this is not working?
> 
> If not, what's the proper way to uninstall? First Mac....
> 
> thanks
> <img alt="Screen Shot 2020-11-14 at 10 58 23 AM" width="1440" src="https://user-images.githubusercontent.com/74464830/99152596-52a60b80-2668-11eb-96bd-51ad154a1286.png">

Hi @hashsi99,
do you still experience this problem with the new version AlDente 2.1-alpha?
