### ISSUE TITLE
Tried to purchase Al Dente Pro with credit card but declined

### ISSUE THREAD

**Issue by linettechua** [davidwernhart/AlDente#473]
Hi, I tried purchasing the Al Dente Pro using two different credit cards and both have been declined ... I'm not sure what the problem is. Thank you!

**Comment by MatthiasKerbl** [comment]
Hi @linettechua,

I am sorry you are having trouble with our Payment Provider Paddle. You can either try to buy AlDente with another payment method (Paypal, Apple Pay, Google Pay) or write the Paddle Support at help@paddle.com about your issue.

Cheers,
Matthias
