### ISSUE TITLE
Purchase failed and haven't receive the refund.

### ISSUE THREAD

**Issue by williamjin1992** [davidwernhart/AlDente#478]
Hi:
	I purchased two times in this month, but the first payment is not successfully capture by your system, then I made another payment as you suggested and it is successful. But two weeks now I haven’t receive the refund by my bank now. Can you help me find out what’s happening?
![image](https://user-images.githubusercontent.com/29701725/143664504-fce8a02d-ae3e-4a64-8251-851d9f0c6515.png)

**Comment by MatthiasKerbl** [comment]
Hi @williamjin1992,

I am sorry for the inconvenience.
Since all our payments get processed through our payment provider Paddle you have to report your issue to the Paddle support.
I can see you were already in contact with Paddle, please write them again about the refund.

Cheers,
Matthias
