### ISSUE TITLE
Not limiting charge macOS Monterey

### ISSUE THREAD

**Issue by beatsmusic1972** [davidwernhart/AlDente#481]
I am on macOS Monterey 12.0.1 official release, and the battery charges past the limit on my (open) m1 MacBook Pro in Al Dente free version. Worked fine in macOS big sur. Any solutions?

**Comment by MatthiasKerbl** [comment]
Hi @beatsmusic1972,

AlDente can get a little bit confused after bigger macOS updates. Check if you have "Optimized battery charging" deactivated in macOS preferences. If it is deactivated, try to reinstall AlDente completely. For uninstallation, use this guide: https://apphousekitchen.com/how-to-uninstall-aldente-pro/

Cheers,
Matthias
