### ISSUE TITLE
Hide the Pop Up

### ISSUE THREAD

**Issue by iam3ddy** [davidwernhart/AlDente#486]
<img width="424" alt="Screenshot 2021-12-03 at 6 05 02 AM" src="https://user-images.githubusercontent.com/21017389/144511553-f63f9d22-ec3b-41d3-8018-440e465198c7.png">

pls add features to hide this pop up upon launch for pro version.

**Comment by MatthiasKerbl** [comment]
Hi @iam3ddy,

We will include this option with the next update soon.

Since there is already an issue open about this (#469), I will close this one.

Cheers,
Matthias
