### ISSUE TITLE
Inconsistent dmg download link for 1.10

### ISSUE THREAD

**Issue by noranraskin** [davidwernhart/AlDente#490]
The download link for the latest build is:  
https://github.com/davidwernhart/AlDente/releases/download/1.10/AlDente1.1.dmg

It's 1.10 for the version but 1.1 for the dmg.
Just a small inconsistency but it breaks the homebrew cask

**Comment by MatthiasKerbl** [comment]
Hi @noranraskin,

Thanks for pointing it out, we will look into this.

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment]
Got fixed now!

Cheers,
Matthias
