### ISSUE TITLE
AlDente Free : Discharge button missing

### ISSUE THREAD

**Issue by rramchar** [davidwernhart/AlDente#492]
At some point the Discharge button in the UI disappeared.
After that my 2018 MBP doesn't stay at 80% and charges to 100%

**Comment by MatthiasKerbl** [comment]
Hi @rramchar,

Do you have the Intel Mode activated?

Cheers,
Matthias

**Comment by rramchar** [comment]
Yes I do.

**Comment by rramchar** [comment]
Attached pictures
![intel-mode](https://user-images.githubusercontent.com/45997492/144913279-39a6ec8a-e6d2-4ebd-9d31-7d51331eee7f.png)
![missing-button](https://user-images.githubusercontent.com/45997492/144913280-d096b34c-eee3-4b3b-8a38-8657e6ed8956.png)

**Comment by simulatxd** [comment]
hi, btw iI have same issue, I should turn off intel mode to make appear discharge button.

<img width="665" alt="Screen Shot 2021-12-08 at 09 54 00" src="https://user-images.githubusercontent.com/94058502/145140289-283757ae-1b00-4df7-a32a-26bcbea72075.png">

**Comment by rramchar** [comment]
@simulatxd does the Discharge button immediately show up when you disable "Intel mode"?

**Comment by rramchar** [comment]
Had someone point out to me this FAQ entry

https://apphousekitchen.com/feature-explanation-intel-mode/

Intel mode doesn't mean "for Intel MacBooks" as I incorrectly assumed.  Disabling "Intel Mode" makes the discharge button visible and the MacBook is currently discharging. 

Closing this issue.
