### ISSUE TITLE
Limit charge not honored if Mac is shut down and plugged in

### ISSUE THREAD

**Issue by Helloben231** [davidwernhart/AlDente#494]
For example, if the limit charge is set to 50% while to the computer is on and plugged in, it is honored. If mac is shutdown, but still plugged in, it will continue charging past 50%. This has been happening on Mac Monterey.

**Comment by MatthiasKerbl** [comment]
Hi @Helloben231,

We have explanations about this behaviour of AlDente on our website:
https://apphousekitchen.com/feature-explanation-stop-charging-when-powered-off-app-closed/

Cheers,
Matthias
