### ISSUE TITLE
Works flawlessly on MB Pro 13" Early 2015 @ OSX Big Sur. Thx!

### ISSUE THREAD

**Issue by togiberlin** [davidwernhart/AlDente#50]
...requires a restart to take effect.

Many thanks for your effort!

Feel free to add my spec to the README 👍

**Comment by hashsi99** [comment]
Using a light theme is your status icon blacked out?

**Comment by togiberlin** [comment]
@hashsi99 nope. I'm on MacOS X Big Sur. Worked on Catalina flawlessly as well.

**Comment by hashsi99** [comment]
![30EAD7D9-5B00-4C5D-9940-B1534BA9F221](https://user-images.githubusercontent.com/74464830/99313917-f1c43200-2825-11eb-9c31-266d57de7bad.png)

**Comment by budiselic** [comment]
Hi, unfortunately is not working for me on MBP 13 2019 @ Big Sur. Installed app, installed helper, restarted my mac but still charging :(
