### ISSUE TITLE
verification of Pro subscription fails, error message states there is no internet connection

### ISSUE THREAD

**Issue by PCDube** [davidwernhart/AlDente#500]
![image](https://user-images.githubusercontent.com/96061149/145818755-4b85d51f-bd08-4baf-b8c0-3b1bcfe40dc1.jpeg)
[](url)
![Screen Shot 2021-12-13 at 8 13 14 AM](https://user-images.githubusercontent.com/96061149/145819056-994967fa-c90e-437a-8e02-f9c8a2ca2ba0.jpg)

Hello.  I'm having an issue with Aldente not being able to verify my Pro license.  I get this message, even when I am connected to the internet.  This just started today.  I have restarted several times.  I have quit and restarted Aldente several times also.

Peter

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**MacBook (please complete the following information):**
 - MacBook model (https://support.apple.com/en-us/HT201608)
 - macOS version (https://support.apple.com/en-us/HT201260)
 - AlDente Pro or AlDente Free?
 - AlDente Version?
 - List of all enabled/disabled settings in AlDente:

**Additional context**

**Comment by PCDube** [comment]
Forgot to add details!
![image](https://user-images.githubusercontent.com/96061149/145819323-d377450e-6a67-434a-882a-bac02737fc73.jpeg)

![image](https://user-images.githubusercontent.com/96061149/145819436-4264bd80-1de2-4765-82de-8a6796df3a99.jpeg)

**Comment by MatthiasKerbl** [comment]
Hi @PCDube,

Thank you for reporting this issue we are currently investigating it.

A quick workaround should be as follows:

1. Go into Settings/General Settings
2. Click on "Manage License"
3. A popup window should open, click on "Deactivate License"
4. Click on "Activate License" and enter your email address and license code again

Everything should work fine again.

Cheers,
Matthias

**Comment by PCDube** [comment]
Matthias,
the work around worked great!   Thanks!!!

**Comment by MatthiasKerbl** [comment]
Hi @PCDube ,

We have just released AlDente 1.15 which fixed the issue you mentioned.
You can just do the update in AlDente or download the newest version here: https://github.com/davidwernhart/AlDente/releases

Cheers,
Matthias

**Comment by PCDube** [comment]
Thanks!  Downloaded, Installed and ReLaunched!
