### ISSUE TITLE
No more option to remove icon from dock?

### ISSUE THREAD

**Issue by brypwn** [davidwernhart/AlDente#501]
**Describe the bug**
Al Dente free no longer has the ability to remove the icon from the dock

**To Reproduce**
This behaviour can be observed on Al Dente 1.11

**Expected behavior**
Should be able to remove icon from dock?

**MacBook (please complete the following information):**
- M1 Macbook Air 2020, macOS Monterey 
- AlDente Free

**Comment by markouustalu** [comment]
Aldente used to be only up there beside the clock, now it is also in dock. There is no option to remove it. Closing from dock closes it down completely.
![image](https://user-images.githubusercontent.com/49148843/146160968-37fe8587-4704-43e9-8d72-83b25638cf5a.png)

**Comment by MatthiasKerbl** [comment]
> Aldente used to be only up there beside the clock, now it is also in dock. There is no option to remove it. Closing from dock closes it down completely. ![image](https://user-images.githubusercontent.com/49148843/146160968-37fe8587-4704-43e9-8d72-83b25638cf5a.png)

Hi @markouustalu,

You can disable the dock icon in Settings/Appearance/Other "Show Dock Icon" disabled.

Cheers,
Matthias

**Comment by markouustalu** [comment]
yes, indeed you can, and it works as needed. i guess the seven options on that page were too much for me to read and i didn't make it to the last one. Thank you again.

**Comment by simon-forman** [comment]
It's grayed out and non interactable

**Comment by MatthiasKerbl** [comment]
Hi @simon-forman,

the setting to deactivate the dock icon is also available in the free version here:
<img width="544" alt="Settings" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/33470003/a2599542-fa36-446c-9e0e-310ac1de7517">

Best,
Matthias

**Comment by Mshkss** [comment]
didnt work
