### ISSUE TITLE
Incorrect RU translation in the Sailing Mode section

### ISSUE THREAD

**Issue by dimasch** [davidwernhart/AlDente#503]
**Describe the bug**
Incorrect RU translation in the Sailing Mode section.

**To Reproduce**
1. Go to 'Settings'
2. Click on tab 'Наcтройки заряда'
3. Scroll down to 'Парусный режим'
4. See incorrect translation `Пывёт до`

**Expected behavior**
`Плывёт до`

**Screenshots**
<img width="433" alt=" 2021-12-20 в 11 34 19" src="https://user-images.githubusercontent.com/414067/146732105-bb39291c-3783-49b4-85dd-e87d03eb1088.png">

**MacBook (please complete the following information):**
 - MacBook Pro 14" M1 Pro (https://support.apple.com/kb/SP854?locale=en_US)
 - macOS Monterey 12.0.1
 - AlDente Pro
 - AlDente Version 1.11

**Additional context**
Used the RU locale

**Comment by MatthiasKerbl** [comment]
Hi @dimasch,

Thank you for reporting this mistake. We will fix it with the next update.

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @dimasch,

we just released AlDente 1.12 which has a fix for the mistake you mentioned.
You can download the newest version here (https://github.com/davidwernhart/AlDente/releases) or just update your current version.

Cheers,
Matthias

**Comment by dimasch** [comment]
@MatthiasKerbl  I really appreciate it.

**Comment by dimasch** [comment]
@MatthiasKerbl Missing space after words:
<img width="427" alt=" 2021-12-20 в 19 29 54" src="https://user-images.githubusercontent.com/414067/146792186-0f6dbaf2-9ba6-49d0-b4b6-a1518838a187.png">

**Comment by MatthiasKerbl** [comment]
> @MatthiasKerbl Missing space after words: <img alt=" 2021-12-20 в 19 29 54" width="427" src="https://user-images.githubusercontent.com/414067/146792186-0f6dbaf2-9ba6-49d0-b4b6-a1518838a187.png">

Oh no haha
Will be fixed with the next release.
