### ISSUE TITLE
Potential menubar icon high CPU usage bug

### ISSUE THREAD

**Issue by nermur** [davidwernhart/AlDente#505]
**Describe the bug**
Displaying a Menubar Icon has much higher CPU usage than without. Another side effect is Al Dente can never go into the background with the Menubar Icon displayed.

**Screenshots**
<img width="1792" alt="Screen Shot 2021-12-21 at 14 48 56" src="https://user-images.githubusercontent.com/29991266/147008239-52d89dc6-ed89-4470-8b42-e3fa632b5862.png">

**MacBook**
- Model: Air 2020 M1 (512GB storage, 8 GPU cores)
- macOS version: 12.1
- AlDente Pro, version 1.12

**Comment by MatthiasKerbl** [comment]
Hi @nermur,

Do you mean the menubar icon or the dock icon?

**Comment by MatthiasKerbl** [comment]
Hi @nermur,

Do you still encounter this problem with our newest version 1.14?
