### ISSUE TITLE
Can't install app on M1 macOS 12.1. Always ask to install helper.

### ISSUE THREAD

**Issue by sitnikovdev** [davidwernhart/AlDente#506]
**Describe the bug**
After first lunch app require install helper. After it installed, app not full started and show install helper again. And repeat after trying to do so.

**To Reproduce**
1. Lunch app
2. Show popap "AlDente-Pro is trying to install a new helper tool". Enter password and click "Install Helper" button.
3. Click app icon in toolbar. 
4. Open popup message dialog window with two buttons: "Install Helper" and "Quit".
5. When click on button "Install Helper" - nothing is happen.

**Expected behavior**
The app is full start and work.

**Screenshots**

https://user-images.githubusercontent.com/60083023/147130400-96595408-a796-4d88-8aea-80181db5aab5.mov

<img width="583" alt="Screenshot 2021-12-22 at 19 42 40" src="https://user-images.githubusercontent.com/60083023/147130478-e5d30e02-6876-45a1-9fbb-be0af7761173.png">

**MacBook (please complete the following information):**
 -  MacBook Pro (13-inch, M1, 2020)
 - macOS version 12.1 (21C52)
 - AlDente Pro 
 - AlDente last version

**Comment by sitnikovdev** [comment]
The problem was in old version of AlDente Pro. Install new version and it work.

**Comment by derekhongg** [comment]
Where did you find the newest version of Aldente Pro?

**Comment by MatthiasKerbl** [comment]
> Where did you find the newest version of Aldente Pro?

Hi @derekhongg,

you can find the newest version here: https://github.com/davidwernhart/AlDente/releases

Cheers,
Matthias

**Comment by sitnikovdev** [comment]
Hi,
I wrote in support and they give me new link. Try this one in attachment.
