### ISSUE TITLE
Keep getting message to remove old helper

### ISSUE THREAD

**Issue by mcartagenah** [davidwernhart/AlDente#509]
**Describe the bug**
I updated the app to the latest version and I get a message asking to remove the old helper, I removed it and it keeps appearing and can't do anything else.

**Screenshots**
<img width="383" alt="Screen Shot 2021-12-23 at 14 20 23" src="https://user-images.githubusercontent.com/10224074/147273546-caebe0b2-2fb8-4d1a-834b-c229bc28befb.png">

**MacBook (please complete the following information):**
 - MacBook Pro (16-inch, 2019)
 - Version 12.1 (21C52)
 - AlDente Pro
 - AlDente 1.12

**Comment by fusuyfusuy** [comment]
can confirm, having the same problem. 

M1 Macbook Air
Monterey 12.1
Aldente 1.12

**Comment by MatthiasKerbl** [comment]
Hi @mcartagenah and @fusuyfusuy,

Please follow the instructions for uninstalling the AlDente manually on this blog post: https://apphousekitchen.com/how-to-uninstall-aldente-pro/

Afterward, install the newest version of AlDente again.
This time, you should get the error message.

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @mcartagenah,

I will close this issue for now. If you still have this issue, please let us know.

Cheers,
Matthias

**Comment by ysomad** [comment]
Same problem.
