### ISSUE TITLE
You can’t open the application “AlDente.app” because it may be damaged or incomplete.

### ISSUE THREAD

**Issue by iansinnott** [davidwernhart/AlDente#51]
Hey sorry if this is covering old territory. I saw #15 which seems to be the same issue, but it appears it's resurfaced. When I double click the app in Finder I get:

> You can’t open the application “AlDente.app” because it may be damaged or incomplete.

![2020-11-19 at 9 35 PM](https://user-images.githubusercontent.com/3154865/99673163-5fcf5a00-2aaf-11eb-91d3-cd0cc23625f0.png)

I'm running Catalina on the new-ish 16" macbook. Downloaded from the releases page today (2020-11-19).

**Comment by kodifiera99** [comment]
Simple fix, for all apps that have this issue.

- Open Terminal
- Change directory to wherever its located - lets say downloads
- `cd ~/Downloads`
- `xattr -cr AlDente.app`
