### ISSUE TITLE
Hide Dock Icon

### ISSUE THREAD

**Issue by jotheta** [davidwernhart/AlDente#517]
I love the app, however the app doesn't work for me when quitted.
Hence, I would love to be able to hide the dock item or that the app remains working when quitted.

**Comment by MatthiasKerbl** [comment]
Hi @jotheta,

AlDente needs to be running for the charge limit to work.

You can disable the dock icon in Settings/Appearance/Other/Show Dock Icon.

Cheers,
Matthias
