### ISSUE TITLE
It does not charge anymore

### ISSUE THREAD

**Issue by jeffonmac** [davidwernhart/AlDente#518]
**Describe the bug**
no charging after fully decharged. 

**Expected behavior**

After my 15 inch MacBook Pro has been fully discharged. Having enabled disables the charging action when the Mac is turned off or in standby. It does not charge anymore. Do you have a solution?

**Screenshots**
![image](https://user-images.githubusercontent.com/23297266/147565142-75dd0e1e-21f3-42c2-bb92-811f0feea1d2.jpg)

**MacBook (please complete the following information):**
 - MacBook model (https://support.apple.com/en-us/HT201608)
 - macOS version (https://support.apple.com/en-us/HT201260)
 - MacBook Pro 15 inch 
 - AlDente Pro 
 - AlDente Version : AlDente 1.12
 - List of all enabled/disabled settings in AlDente:

Enabled disables the charging action when the Mac is turned off or in standby.

**Comment by MatthiasKerbl** [comment]
Hi @jeffonmac,

Usually, this is due to your MacBook discharging into the battery reserve. Therefore, if you plug in your MacBook again it will very cautiously and slowly start charging again until it is in a normal SoC again. Thus it takes longer until it reboots.
Did your MacBooks reboot after a while again?

**Comment by PearApple151** [comment]
> **Describe the bug** no charging after fully decharged.
> 
> **Expected behavior**
> 
> After my 15 inch MacBook Pro has been fully discharged. Having enabled disables the charging action when the Mac is turned off or in standby. It does not charge anymore. Do you have a solution?
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/23297266/147565142-75dd0e1e-21f3-42c2-bb92-811f0feea1d2.jpg)
> 
> **MacBook (please complete the following information):**
> 
> * MacBook model (https://support.apple.com/en-us/HT201608)
> * macOS version (https://support.apple.com/en-us/HT201260)
> * MacBook Pro 15 inch
> * AlDente Pro
> * AlDente Version : AlDente 1.12
> * List of all enabled/disabled settings in AlDente:
> 
> Enabled disables the charging action when the Mac is turned off or in standby.

hey did your Mac start working again?

**Comment by jeffonmac** [comment]
Yes it’s good thank you !
