### ISSUE TITLE
Options to check/uncheck inside Battery Settings on Big Sur?

### ISSUE THREAD

**Issue by joshuarobs** [davidwernhart/AlDente#53]
Do we uncheck both `Optimised battery charging` and `Battery Health... > Manage battery longevity` while having Aldente run at the same time?

**Comment by JasSingh685** [comment]
I leave mine on. I don't think it will cause any issue. I believe macOS will lower the charge level over time, as the battery ages, whereas AIDente you limit the charge level manually before macOS does anything.

**Comment by joshuarobs** [comment]
@JasSingh685 Which one do you leave on? Both?

**Comment by JasSingh685** [comment]
> @JasSingh685 Which one do you leave on? Both?

Yeah I keep it on default which is both set to on, seems to be ok and still charges to 100% when I need it to.

**Comment by joshuarobs** [comment]
@JasSingh685 
I'm confused. It charges to 100%, but isn't the point of AlDente to set the limit to anything below that, e.g. 50%, 60%, 70%, 80%?

I wish there was more information on this app, its so confusing and vague and its hard to make the right decision

**Comment by JasSingh685** [comment]
No sorry my mistake, I meant to say that I can set the app to charge the battery to 100% if I **need** to, but normally I set it to around 75%, so yes you can set to whatever you like!

**Comment by joshuarobs** [comment]
Thanks for the clarification
