### ISSUE TITLE
Crash while Calibrating

### ISSUE THREAD

**Issue by The70sWoodsman** [davidwernhart/AlDente#533]
**Describe the bug**
The app quite unexpectedly, generating an Apple error report whilst it running a "calibration" (it was either in the final 1hr hold or had just finished and want discharging).

**To Reproduce**
It's not possible to define how to recreate the problem as no user action was taken, it just quit unexpectedly and generated an error report.

**Expected behavior**
The app only quits when a user action to quit is executed.

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**MacBook (please complete the following information):**
Please see the full report for most of this.
Pro Settings (true):
- Open on launch
- Sail
- Heat protection
- stop charging when powered off
- battery icon
- % icon

**Additional context**
Apple error report:
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               AlDente [621]
Path:                  /Applications/AlDente.app/Contents/MacOS/AlDente
Identifier:            com.apphousekitchen.aldente-pro
Version:               1.12 (19)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-01-05 16:03:26.7932 +0000
OS Version:            macOS 12.1 (21C52)
Report Version:        12
Bridge OS Version:     6.1 (19P647)
Anonymous UUID:        1A2A8BCF-28E7-EB0A-2DBC-1AF779B44DBC

Sleep/Wake UUID:       B84BC010-E7A6-4169-8B75-F30C006D9D2E

Time Awake Since Boot: 22000 seconds
Time Since Wake:       3603 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 4 Illegal instruction: 4
Terminating Process:   exc handler [621]

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   AlDente                       	       0x1007b7252 0x100780000 + 225874
1   AlDente                       	       0x1007a4a07 0x100780000 + 150023
2   AlDente                       	       0x1007b22be 0x100780000 + 205502
3   AlDente                       	       0x1007af002 0x100780000 + 192514
4   AlDente                       	       0x100782d85 0x100780000 + 11653
5   AlDente                       	       0x1007c27e4 0x100780000 + 272356
6   Foundation                    	    0x7ff8163866c0 __NSFireTimer + 67
7   CoreFoundation                	    0x7ff8154f884f __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
8   CoreFoundation                	    0x7ff8154f833e __CFRunLoopDoTimer + 927
9   CoreFoundation                	    0x7ff8154f7e9d __CFRunLoopDoTimers + 307
10  CoreFoundation                	    0x7ff8154de45f __CFRunLoopRun + 1985
11  CoreFoundation                	    0x7ff8154dd5dd CFRunLoopRunSpecific + 563
12  HIToolbox                     	    0x7ff81e1104f1 RunCurrentEventLoopInMode + 292
13  HIToolbox                     	    0x7ff81e110247 ReceiveNextEventCommon + 587
14  HIToolbox                     	    0x7ff81e10ffe5 _BlockUntilNextEventMatchingListInModeWithFilter + 70
15  AppKit                        	    0x7ff817f0cb4c _DPSNextEvent + 886
16  AppKit                        	    0x7ff817f0b1b8 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1411
17  AppKit                        	    0x7ff817efd5a9 -[NSApplication run] + 586
18  AppKit                        	    0x7ff817ed1447 NSApplicationMain + 816
19  AlDente                       	       0x10078793c 0x100780000 + 31036
20  dyld                          	       0x10f13f4fe start + 462

Thread 1:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	    0x7ff8153dbaba mach_msg_trap + 10
1   libsystem_kernel.dylib        	    0x7ff8153dbe2b mach_msg + 59
2   CoreFoundation                	    0x7ff8154dfaf2 __CFRunLoopServiceMachPort + 319
3   CoreFoundation                	    0x7ff8154de1cb __CFRunLoopRun + 1325
4   CoreFoundation                	    0x7ff8154dd5dd CFRunLoopRunSpecific + 563
5   AppKit                        	    0x7ff81807ad98 _NSEventThread + 132
6   libsystem_pthread.dylib       	    0x7ff8154184f4 _pthread_start + 125
7   libsystem_pthread.dylib       	    0x7ff81541400f thread_start + 15

Thread 2:: com.apple.NSURLConnectionLoader
0   libsystem_kernel.dylib        	    0x7ff8153dbaba mach_msg_trap + 10
1   libsystem_kernel.dylib        	    0x7ff8153dbe2b mach_msg + 59
2   CoreFoundation                	    0x7ff8154dfaf2 __CFRunLoopServiceMachPort + 319
3   CoreFoundation                	    0x7ff8154de1cb __CFRunLoopRun + 1325
4   CoreFoundation                	    0x7ff8154dd5dd CFRunLoopRunSpecific + 563
5   CFNetwork                     	    0x7ff81a0d758e 0x7ff819e88000 + 2422158
6   Foundation                    	    0x7ff81633d2c9 __NSThread__start__ + 1025
7   libsystem_pthread.dylib       	    0x7ff8154184f4 _pthread_start + 125
8   libsystem_pthread.dylib       	    0x7ff81541400f thread_start + 15

Thread 3:
0   libsystem_pthread.dylib       	    0x7ff815413fec start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	    0x7ff815413fec start_wqthread + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x000000010082b1d0  rbx: 0xe100000000000000  rcx: 0x0000600000b1c280  rdx: 0x00000000f2e0c04d
  rdi: 0xe100000000000000  rsi: 0x0000600003d89300  rbp: 0x00007ff7bf77d020  rsp: 0x00007ff7bf77cf70
   r8: 0x0000000000001300   r9: 0x0000000000000040  r10: 0x00000000000007fb  r11: 0x0000000000000100
  r12: 0xe100000000000000  r13: 0xef6e776f645f656c  r14: 0x0000600001a006f8  r15: 0x0000600003d89300
  rip: 0x00000001007b7252  rfl: 0x0000000000010202  cr2: 0x0000000109439000
  
Logical CPU:     6
Error Code:      0x00000000 
Trap Number:     6

Thread 0 instruction stream:
  00 e9 95 f9 ff ff 49 8b-3e 48 8d 45 d0 e8 bc 12  ......I.>H.E....
  02 00 f3 0f 10 45 d0 0f-2e 45 a8 4c 8b 7d c0 4c  .....E...E.L.}.L
  8b 6d c8 49 bc 11 00 00-00 00 00 00 d0 0f 87 9a  .m.I............
  f1 ff ff 48 8b 3b 48 8d-45 d0 e8 8f 12 02 00 80  ...H.;H.E.......
  7d d0 00 0f 85 38 ec ff-ff e9 7f f1 ff ff 0f 0b  }....8..........
  0f 0b 0f 0b 0f 0b 0f 0b-0f 0b 0f 0b 0f 0b 0f 0b  ................
 [0f]0b 0f 0b 0f 0b 0f 0b-0f 0b 0f 0b 0f 0b 0f 0b  ................	<==
  0f 0b 0f 0b 0f 0b 0f 0b-0f 0b 0f 0b 0f 0b 0f 0b  ................
  0f 0b 0f 0b 66 2e 0f 1f-84 00 00 00 00 00 41 56  ....f.........AV
  53 50 48 8b 07 48 85 c0-75 1b 49 89 d6 48 89 fb  SPH..H..u.I..H..
  bf ff 00 00 00 ff d6 4c-89 f7 48 89 c6 e8 48 11  .......L..H...H.
  04 00 48 89 03 48 83 c4-08 5b 41 5e c3 90 48 8d  ..H..H...[A^..H.

Binary Images:
       0x100780000 -        0x100817fff com.apphousekitchen.aldente-pro (1.12) <71e21814-0fe5-3158-829f-a523fe462835> /Applications/AlDente.app/Contents/MacOS/AlDente
    0x7ff8162e5000 -     0x7ff81669ffff com.apple.Foundation (6.9) <4f895069-27e3-3087-a30e-515f5fc9f493> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7ff81545f000 -     0x7ff815961fff com.apple.CoreFoundation (6.9) <eab0e216-2a9e-31ce-9164-fdf3ebcf7bd3> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7ff81e0de000 -     0x7ff81e3d5fff com.apple.HIToolbox (2.1.1) <535dbc28-4d26-3609-86bb-5c40227b648c> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
    0x7ff817ece000 -     0x7ff818d5cfff com.apple.AppKit (6.9) <d23b9681-3764-3298-a716-fbb511dd5a7c> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x10f13a000 -        0x10f1a5fff dyld (*) <cef5a27a-d50b-3020-af03-1734b19bc8c5> /usr/lib/dyld
    0x7ff8153db000 -     0x7ff815411fff libsystem_kernel.dylib (*) <5aa1e5be-b5b8-3a02-9885-a8c99e0ca378> /usr/lib/system/libsystem_kernel.dylib
    0x7ff815412000 -     0x7ff81541dfff libsystem_pthread.dylib (*) <6c7561b4-4b92-3f45-921e-abe669299844> /usr/lib/system/libsystem_pthread.dylib
    0x7ff819e88000 -     0x7ff81a31efff com.apple.CFNetwork (1327.0.4) <daf237f6-3feb-3773-9751-f8576ea26acb> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.1G resident=0K(0%) swapped_out_or_unallocated=1.1G(100%)
Writable regions: Total=631.8M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=631.8M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework              2560K       20 
Activity Tracing                   256K        1 
CG backing stores                  720K        4 
CG image                           476K       32 
CG raster data                     224K        3 
ColorSync                          244K       29 
CoreAnimation                     1240K      128 
CoreGraphics                        16K        3 
CoreUI image data                 2240K       30 
Foundation                          40K        2 
IOKit                             7940K        1 
Image IO                           100K        1 
Kernel Alloc Once                    8K        1 
MALLOC                           230.9M       80 
MALLOC guard page                   48K       12 
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
SQLite page cache                  192K        3 
STACK GUARD                       56.0M        5 
Stack                             10.0M        5 
VM_ALLOCATE                       1120K       21 
__DATA                            29.7M      507 
__DATA_CONST                      29.3M      338 
__DATA_DIRTY                      1645K      208 
__FONT_DATA                          4K        1 
__LINKEDIT                       642.1M       14 
__OBJC_RO                         81.8M        1 
__OBJC_RW                         3136K        2 
__TEXT                           484.3M      527 
__UNICODE                          588K        1 
dyld private memory               1024K        1 
libnetwork                         640K       16 
mapped file                      395.5M       47 
shared memory                      776K       17 
===========                     =======  ======= 
TOTAL                              2.3G     2062 
TOTAL, minus reserved VM space     1.9G     2062 

-----------
Full Report
-----------

{"app_name":"AlDente","timestamp":"2022-01-05 16:03:36.00 +0000","app_version":"1.12","slice_uuid":"71e21814-0fe5-3158-829f-a523fe462835","build_version":"19","platform":1,"bundleID":"com.apphousekitchen.aldente-pro","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.1 (21C52)","incident_id":"44FF3890-AF30-4DFD-BA93-E214CECC57AA","name":"AlDente"}
{
  "uptime" : 22000,
  "procLaunch" : "2022-01-05 09:35:03.2909 +0000",
  "procRole" : "Background",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro15,2",
  "procStartAbsTime" : 28606444827,
  "coalitionID" : 744,
  "osVersion" : {
    "train" : "macOS 12.1",
    "build" : "21C52",
    "releaseType" : "User"
  },
  "captureTime" : "2022-01-05 16:03:26.7932 +0000",
  "incident" : "44FF3890-AF30-4DFD-BA93-E214CECC57AA",
  "bug_type" : "309",
  "pid" : 621,
  "procExitAbsTime" : 22001316939305,
  "cpuType" : "X86-64",
  "procName" : "AlDente",
  "procPath" : "\/Applications\/AlDente.app\/Contents\/MacOS\/AlDente",
  "bundleInfo" : {"CFBundleShortVersionString":"1.12","CFBundleVersion":"19","CFBundleIdentifier":"com.apphousekitchen.aldente-pro"},
  "storeInfo" : {"deviceIdentifierForVendor":"973D98B7-C7F2-52C8-9598-C995FDA37ECB","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.apphousekitchen.aldente-pro",
  "crashReporterKey" : "1A2A8BCF-28E7-EB0A-2DBC-1AF779B44DBC",
  "wakeTime" : 3603,
  "bridgeVersion" : {"build":"19P647","train":"6.1"},
  "sleepWakeUUID" : "B84BC010-E7A6-4169-8B75-F30C006D9D2E",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x0000000000000000","rawCodes":[1,0],"type":"EXC_BAD_INSTRUCTION","signal":"SIGILL"},
  "termination" : {"flags":0,"code":4,"namespace":"SIGNAL","indicator":"Illegal instruction: 4","byProc":"exc handler","byPid":621},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":5295,"instructionState":{"instructionStream":{"bytes":[0,233,149,249,255,255,73,139,62,72,141,69,208,232,188,18,2,0,243,15,16,69,208,15,46,69,168,76,139,125,192,76,139,109,200,73,188,17,0,0,0,0,0,0,208,15,135,154,241,255,255,72,139,59,72,141,69,208,232,143,18,2,0,128,125,208,0,15,133,56,236,255,255,233,127,241,255,255,15,11,15,11,15,11,15,11,15,11,15,11,15,11,15,11,15,11,15,11,15,11,15,11,15,11,15,11,15,11,15,11,15,11,15,11,15,11,15,11,15,11,15,11,15,11,15,11,15,11,15,11,15,11,102,46,15,31,132,0,0,0,0,0,65,86,83,80,72,139,7,72,133,192,117,27,73,137,214,72,137,251,191,255,0,0,0,255,214,76,137,247,72,137,198,232,72,17,4,0,72,137,3,72,131,196,8,91,65,94,195,144,72,141],"offset":96}},"threadState":{"r13":{"value":17252858542811997548},"rax":{"value":4303532496},"rflags":{"value":66050},"cpu":{"value":6},"r14":{"value":105553143531256},"rsi":{"value":105553180791552},"r8":{"value":4864},"cr2":{"value":4450390016},"rdx":{"value":4074815565},"r10":{"value":2043},"r9":{"value":64},"r15":{"value":105553180791552},"rbx":{"value":16212958658533785600},"trap":{"value":6},"err":{"value":0},"r11":{"value":256},"rip":{"value":4303057490,"matchesCrashFrame":1},"rbp":{"value":140702045949984},"rsp":{"value":140702045949808},"r12":{"value":16212958658533785600},"rcx":{"value":105553127916160},"flavor":"x86_THREAD_STATE","rdi":{"value":16212958658533785600}},"queue":"com.apple.main-thread","frames":[{"imageOffset":225874,"imageIndex":0},{"imageOffset":150023,"imageIndex":0},{"imageOffset":205502,"imageIndex":0},{"imageOffset":192514,"imageIndex":0},{"imageOffset":11653,"imageIndex":0},{"imageOffset":272356,"imageIndex":0},{"imageOffset":661184,"symbol":"__NSFireTimer","symbolLocation":67,"imageIndex":1},{"imageOffset":628815,"symbol":"__CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__","symbolLocation":20,"imageIndex":2},{"imageOffset":627518,"symbol":"__CFRunLoopDoTimer","symbolLocation":927,"imageIndex":2},{"imageOffset":626333,"symbol":"__CFRunLoopDoTimers","symbolLocation":307,"imageIndex":2},{"imageOffset":521311,"symbol":"__CFRunLoopRun","symbolLocation":1985,"imageIndex":2},{"imageOffset":517597,"symbol":"CFRunLoopRunSpecific","symbolLocation":563,"imageIndex":2},{"imageOffset":206065,"symbol":"RunCurrentEventLoopInMode","symbolLocation":292,"imageIndex":3},{"imageOffset":205383,"symbol":"ReceiveNextEventCommon","symbolLocation":587,"imageIndex":3},{"imageOffset":204773,"symbol":"_BlockUntilNextEventMatchingListInModeWithFilter","symbolLocation":70,"imageIndex":3},{"imageOffset":256844,"symbol":"_DPSNextEvent","symbolLocation":886,"imageIndex":4},{"imageOffset":250296,"symbol":"-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]","symbolLocation":1411,"imageIndex":4},{"imageOffset":193961,"symbol":"-[NSApplication run]","symbolLocation":586,"imageIndex":4},{"imageOffset":13383,"symbol":"NSApplicationMain","symbolLocation":816,"imageIndex":4},{"imageOffset":31036,"imageIndex":0},{"imageOffset":21758,"symbol":"start","symbolLocation":462,"imageIndex":5}]},{"id":5353,"name":"com.apple.NSEventThread","frames":[{"imageOffset":2746,"symbol":"mach_msg_trap","symbolLocation":10,"imageIndex":6},{"imageOffset":3627,"symbol":"mach_msg","symbolLocation":59,"imageIndex":6},{"imageOffset":527090,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":319,"imageIndex":2},{"imageOffset":520651,"symbol":"__CFRunLoopRun","symbolLocation":1325,"imageIndex":2},{"imageOffset":517597,"symbol":"CFRunLoopRunSpecific","symbolLocation":563,"imageIndex":2},{"imageOffset":1756568,"symbol":"_NSEventThread","symbolLocation":132,"imageIndex":4},{"imageOffset":25844,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":7},{"imageOffset":8207,"symbol":"thread_start","symbolLocation":15,"imageIndex":7}]},{"id":5375,"name":"com.apple.NSURLConnectionLoader","frames":[{"imageOffset":2746,"symbol":"mach_msg_trap","symbolLocation":10,"imageIndex":6},{"imageOffset":3627,"symbol":"mach_msg","symbolLocation":59,"imageIndex":6},{"imageOffset":527090,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":319,"imageIndex":2},{"imageOffset":520651,"symbol":"__CFRunLoopRun","symbolLocation":1325,"imageIndex":2},{"imageOffset":517597,"symbol":"CFRunLoopRunSpecific","symbolLocation":563,"imageIndex":2},{"imageOffset":2422158,"imageIndex":8},{"imageOffset":361161,"symbol":"__NSThread__start__","symbolLocation":1025,"imageIndex":1},{"imageOffset":25844,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":7},{"imageOffset":8207,"symbol":"thread_start","symbolLocation":15,"imageIndex":7}]},{"id":221030,"frames":[{"imageOffset":8172,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"id":221742,"frames":[{"imageOffset":8172,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4302831616,
    "CFBundleShortVersionString" : "1.12",
    "CFBundleIdentifier" : "com.apphousekitchen.aldente-pro",
    "size" : 622592,
    "uuid" : "71e21814-0fe5-3158-829f-a523fe462835",
    "path" : "\/Applications\/AlDente.app\/Contents\/MacOS\/AlDente",
    "name" : "AlDente",
    "CFBundleVersion" : "19"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703500750848,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.Foundation",
    "size" : 3911680,
    "uuid" : "4f895069-27e3-3087-a30e-515f5fc9f493",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Versions\/C\/Foundation",
    "name" : "Foundation",
    "CFBundleVersion" : "1856.105"
  },
  {
    "source" : "P",
    "arch" : "x86_64h",
    "base" : 140703485521920,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5255168,
    "uuid" : "eab0e216-2a9e-31ce-9164-fdf3ebcf7bd3",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1856.105"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703632842752,
    "CFBundleShortVersionString" : "2.1.1",
    "CFBundleIdentifier" : "com.apple.HIToolbox",
    "size" : 3112960,
    "uuid" : "535dbc28-4d26-3609-86bb-5c40227b648c",
    "path" : "\/System\/Library\/Frameworks\/Carbon.framework\/Versions\/A\/Frameworks\/HIToolbox.framework\/Versions\/A\/HIToolbox",
    "name" : "HIToolbox"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703530016768,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15265792,
    "uuid" : "d23b9681-3764-3298-a716-fbb511dd5a7c",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2113.20.111"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4547911680,
    "size" : 442368,
    "uuid" : "cef5a27a-d50b-3020-af03-1734b19bc8c5",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703484981248,
    "size" : 225280,
    "uuid" : "5aa1e5be-b5b8-3a02-9885-a8c99e0ca378",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703485206528,
    "size" : 49152,
    "uuid" : "6c7561b4-4b92-3f45-921e-abe669299844",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703563284480,
    "CFBundleShortVersionString" : "1327.0.4",
    "CFBundleIdentifier" : "com.apple.CFNetwork",
    "size" : 4812800,
    "uuid" : "daf237f6-3feb-3773-9751-f8576ea26acb",
    "path" : "\/System\/Library\/Frameworks\/CFNetwork.framework\/Versions\/A\/CFNetwork",
    "name" : "CFNetwork",
    "CFBundleVersion" : "1327.0.4"
  }
],
  "sharedCache" : {
  "base" : 140703481978880,
  "size" : 15216738304,
  "uuid" : "40432a03-88d3-305f-9c0c-e7549e71d927"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.1G resident=0K(0%) swapped_out_or_unallocated=1.1G(100%)\nWritable regions: Total=631.8M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=631.8M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework              2560K       20 \nActivity Tracing                   256K        1 \nCG backing stores                  720K        4 \nCG image                           476K       32 \nCG raster data                     224K        3 \nColorSync                          244K       29 \nCoreAnimation                     1240K      128 \nCoreGraphics                        16K        3 \nCoreUI image data                 2240K       30 \nFoundation                          40K        2 \nIOKit                             7940K        1 \nImage IO                           100K        1 \nKernel Alloc Once                    8K        1 \nMALLOC                           230.9M       80 \nMALLOC guard page                   48K       12 \nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nSQLite page cache                  192K        3 \nSTACK GUARD                       56.0M        5 \nStack                             10.0M        5 \nVM_ALLOCATE                       1120K       21 \n__DATA                            29.7M      507 \n__DATA_CONST                      29.3M      338 \n__DATA_DIRTY                      1645K      208 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       642.1M       14 \n__OBJC_RO                         81.8M        1 \n__OBJC_RW                         3136K        2 \n__TEXT                           484.3M      527 \n__UNICODE                          588K        1 \ndyld private memory               1024K        1 \nlibnetwork                         640K       16 \nmapped file                      395.5M       47 \nshared memory                      776K       17 \n===========                     =======  ======= \nTOTAL                              2.3G     2062 \nTOTAL, minus reserved VM space     1.9G     2062 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    },
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    },
    {
      "rolloutId" : "602ad4dac86151000cf27e46",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "6193d03f2171a2330e561dfc"
      },
      "deploymentId" : 240000290
    },
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000090
    },
    {
      "rolloutId" : "601d9415f79519000ccd4b69",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "61c11dcd2cb6041dc630dc63"
      },
      "deploymentId" : 240000356
    },
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000196
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro15,2, BootROM 1715.60.5.0.0 (iBridge: 19.16.10647.0.0,0), 4 processors, Quad-Core Intel Core i7, 2.7 GHz, 16 GB, SMC 
Graphics: Intel Iris Plus Graphics 655, Intel Iris Plus Graphics 655, Built-In
Display: 2757M, 1920 x 1080 (1080p FHD - Full High Definition), Main, MirrorOff, Online
Memory Module: BANK 0/ChannelA-DIMM0, 8 GB, LPDDR3, 2133 MHz, Micron, MT52L1G32D4PG-093
Memory Module: BANK 2/ChannelB-DIMM0, 8 GB, LPDDR3, 2133 MHz, Micron, MT52L1G32D4PG-093
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x7BF), wl0: Jul 12 2021 19:26:30 version 9.30.464.0.32.5.76 FWID 01-45ccefcd
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB2.0 Hub
USB Device: HD Pro Webcam C920
USB Device: USB Billboard Device
USB Device: USB3.0 Hub
USB Device: T2Bus
USB Device: Touch Bar Backlight
USB Device: Touch Bar Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: Ambient Light Sensor
USB Device: FaceTime HD Camera (Built-in)
USB Device: Apple T2 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 47.5
Thunderbolt Bus: MacBook Pro, Apple Inc., 47.5

**Comment by MatthiasKerbl** [comment]
Hi @The70sWoodsman,

Thank you for sharing this issue.

We are currently redoing the Calibration Mode completely and this should fix this bug. The new Calibration Mode will be released with the next update soon.

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @The70sWoodsman,

We have just released a new version of AlDente which should fix this issue.
You can download the newest version [here](https://github.com/davidwernhart/AlDente/releases) or just do the update within the app.

Cheers,
Matthias
