### ISSUE TITLE
The battery just keeps charging

### ISSUE THREAD

**Issue by ccat903** [davidwernhart/AlDente#54]
The battery just keeps charging, it doesn't stop at 80% as I set it.

![Screenshot 2020-11-20 at 11 28 36 PM](https://user-images.githubusercontent.com/74782924/99817619-21599e00-2b88-11eb-8279-86bc81b7c649.png)

**Comment by JasSingh685** [comment]
Have you tried rebooting your Mac?

**Comment by heartbleeded** [comment]
> Have you tried rebooting your Mac?

Yes. Doesn't work.

**Comment by ccat903** [comment]
It does not work.

**Comment by smoothdvd** [comment]
Which model do you use?

**Comment by JasSingh685** [comment]
By any chance, have you tried draining the battery a little? Say, below 50%, and see if it then stops at the 80%? 

From what I understand, it doesn’t allow for discharge while plugged in

**Comment by ccat903** [comment]
I have a 2019 13' mac book pro, I discharged it to like 70% and then plugged it back in.

**Comment by ccat903** [comment]
Oh.. Looks like it works now... I just had to discharge to lower then 50% and then charge. weird
