### ISSUE TITLE
Support "Shortcuts"

### ISSUE THREAD

**Issue by notDavid** [davidwernhart/AlDente#541]
Hi there,

please consider implementing support for the [Shortcuts](https://support.apple.com/guide/shortcuts/welcome/ios) app, to set the `charge limit`, and possible other settings.
This would make automation possible in many ways, and also solve some of the other feature requests in this repo.

Thank you!

**Comment by MatthiasKerbl** [comment]
Hi @notDavid,

You are right, implementing Shortcuts would be a great addition to AlDente. We have already started looking into Shortcuts but since it is a bigger development effort, it will take time.

Cheers,
Matthias

**Comment by Fir333** [comment]
Would be great if we could minimize al dente to tray :) Got enough of stuffs when i press Command + tab ;) Would be great to miss al dente here <3

**Comment by MatthiasKerbl** [comment]
> Would be great if we could minimize al dente to tray :) Got enough of stuffs when i press Command + tab ;) Would be great to miss al dente here <3

Hi @Fir333,

You just have to deactivate the dock icon in Settings/Appearance/Show Dock Icon.

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @notDavid, did not know that. Thanks for mentioning it.

**Comment by MatthiasKerbl** [comment]
Hi @notDavid,

We released a new version of AlDente Pro a couple of days ago which includes support for Apple Shortcuts. Please keep in mind that this is still a beta feature and bugs may occur. Also, check out the article about this new feature: https://apphousekitchen.com/feature-explanation-shortcuts/

Cheers,
Matthias
