### ISSUE TITLE
[Feature request] Smaller menubar icon

### ISSUE THREAD

**Issue by nheeren** [davidwernhart/AlDente#547]
With the introduction of the notch in the new Macbook Pros, menubar estate has become very scarce. Would it be possible you offered a narrower menubar icon?

**Comment by nheeren** [comment]
Thanks for the feedback! Too bad. I wouldn't want to lose the icon completely. 

In my humble opinion not only the icon is quite large, it also seems to have quite a spacer left and right.  Maybe turn the battery 90 degrees? ;)
<img width="120" alt="Screenshot 2022-01-17 at 20 57 01" src="https://user-images.githubusercontent.com/5136954/149834996-a51b8955-6d8f-45e3-93bf-b99cdade1b7b.png">

**Comment by huyz** [comment]
I did also notice that there is an unusual amount of whitespace to the left and right of the Al Dente icon, unlike the icons of other apps.

**Comment by MatthiasKerbl** [comment]
> Thanks for the feedback! Too bad. I wouldn't want to lose the icon completely.
> 
> In my humble opinion not only the icon is quite large, it also seems to have quite a spacer left and right. Maybe turn the battery 90 degrees? ;) <img alt="Screenshot 2022-01-17 at 20 57 01" width="120" src="https://user-images.githubusercontent.com/5136954/149834996-a51b8955-6d8f-45e3-93bf-b99cdade1b7b.png">

Now I know what you mean. We will look into this, maybe we can reduce the space left and right of the icon.

**Comment by nheeren** [comment]
Maybe you can also consider to display the battery charge / percentage (e.g. as a color bar in the background). This would allow me to ditch the macOS / iStat battery icon instead and also save space ;)

**Comment by huyz** [comment]
@nheeren Already possible:
![image](https://user-images.githubusercontent.com/128394/151712143-88b13c92-cb28-41fd-95b5-3bcaee97234a.png)

**Comment by nheeren** [comment]
Thanks, but activating the battery icon will take even twice the space. I am trying to suggest a more multi-functional single icon, in case the developers don't want to offer a smaller icon.
