### ISSUE TITLE
Doesn't work on Big Sur with MBP 16"

### ISSUE THREAD

**Issue by richardsimko** [davidwernhart/AlDente#55]
I'm trying to troubleshoot this app not working at all on my MBP 16" from 2019. Regardless of what I set the setting to it seems to do nothing. Considering other people are reporting it working on Big Sur I'm presuming there's something it's conflicting with on my system. Is there any logs or something like that I can check?

**Comment by rootedetc** [comment]
Same for MBP 15" running Big Sur.

**Comment by kodifiera99** [comment]
The dev literally states Big Sur is not compatible. Big Sur is a buggy mess, either downgrade, or you won't be able to use the app..

**Comment by richardsimko** [comment]
> The dev literally states Big Sur is not compatible. Big Sur is a buggy mess, either downgrade, or you won't be able to use the app..
It's great that they state that, but last I checked this was an open source project, meaning it's possible for users to improve it and expand compatibility. However the first step would then be to understand what's going wrong and a good place to start would be logs - Hence my question about where they might be.

**Comment by celsoazevedo** [comment]
It's working for me (same laptop running Big Sur), but while before I could just set the limit and it would be applied immediately, on Big Sur I have to set the limit and reboot. It didn't work at first, but on my second try, it did.

I have gatekeeper disabled (for unrelated reasons), I don't know if it has any influence over this though.

Limited to 85%:

<img width="581" alt="Screenshot 2020-12-09 at 14 04 22" src="https://user-images.githubusercontent.com/4492221/101639868-bd5c2400-3a27-11eb-8408-a09d9c84a705.png">

**Comment by richardsimko** [comment]
Interesting, I'll try another reboot to see if that helps!

**Comment by rootedetc** [comment]
I jumped to conclusion, AlDente works after setting max charge and rebooting the machine.

**Comment by richardsimko** [comment]
Yep, another reboot solved it for me as well!
