### ISSUE TITLE
[Feature request] Can you redesign the UI of AIDente Pro?

### ISSUE THREAD

**Issue by fhefh2015** [davidwernhart/AlDente#550]
Can you redesign the UI of AIDente Pro?

It feels like it takes up too much space.

Can you be a little more concise?

<img width="570" alt="CleanShot 2022-01-17 at 13 56 13@2x" src="https://user-images.githubusercontent.com/14891797/149715422-32908b91-5ff2-4fe3-9f13-5176807b96e5.png">

**Comment by MatthiasKerbl** [comment]
> 

Hi @fhefh2015,

Do you mean the menubar icon?
You can completely customise the appearance of the menubar icon in Setting/Appearance.

Cheers,
Matthias

**Comment by fhefh2015** [comment]
@MatthiasKerbl 

This pop-up window(view)
<img width="482" alt="CleanShot 2022-01-17 at 20 17 27@2x" src="https://user-images.githubusercontent.com/14891797/149768172-1b2b1906-73d9-417d-8124-cdd0baa2b409.png">

Can be designed like this, simple and more

https://github.com/MonitorControl/MonitorControl

<img width="252" alt="CleanShot 2022-01-17 at 20 18 53@2x" src="https://user-images.githubusercontent.com/14891797/149768348-923f3695-a3eb-46f3-b957-da97927829ff.png">

**Comment by MatthiasKerbl** [comment]
> @MatthiasKerbl
> 
> This pop-up window(view) <img alt="CleanShot 2022-01-17 at 20 17 27@2x" width="482" src="https://user-images.githubusercontent.com/14891797/149768172-1b2b1906-73d9-417d-8124-cdd0baa2b409.png">
> 
> Can be designed like this, simple and more
> 
> https://github.com/MonitorControl/MonitorControl
> 
> <img alt="CleanShot 2022-01-17 at 20 18 53@2x" width="252" src="https://user-images.githubusercontent.com/14891797/149768348-923f3695-a3eb-46f3-b957-da97927829ff.png">

Hi @fhefh2015,

We are fairly satisfied with the current design. Therefore, I don’t think we will update it soon and concentrate more on improving and adding features. However, thank you for the inputs and we are of course open to doing something in this direction in the future.

Cheers,
Matthias
