### ISSUE TITLE
Al Dente toggling charge mode on/off

### ISSUE THREAD

**Issue by fuzzy-logic** [davidwernhart/AlDente#551]
**Describe the bug**

Al Dente constantly toggling charge mode when meant to be paused for max charge limit. During discharge al dente will also toggle between discharge/charge mode while in addition constantly dimming/undimming the screen (only happens during discharge). 

Dimming / un-dimming occurs at a faster rate (approx every ~3-4s) than the charge/discharge (approx every ~8-10s) rate. This only started happening after upgrade to Al Dente 1.13. Issue occurs on Magsafe or USB-C power.

Have un-ticked the following macos settings:

* Optimize battery charging (battery settings)
* Slightly dim display on battery power (battery settings)
* Automatically adjust screen brightness  (display settings)

Have uninstalled/reinstalled helper and al dente completely.

**To Reproduce**
1. Set a charge limit
2. hover over the al dente icon

**Expected behavior**
Charging is paused, or switch to battery discharge.

**Screenshots**

In this first screen capture you'll see the battery charge up to 93% from 92% 

https://user-images.githubusercontent.com/1352531/149759920-feda0d35-8190-4182-bd67-fbfbd87afc5d.mov

In this screen capture, I have enabled discharge mode, for obvious reasons the screen dimming wont show in screen recording

https://user-images.githubusercontent.com/1352531/149759954-bbd20d0c-55a3-4bdd-bdf7-60feabd77dbb.mov

**MacBook (please complete the following information):**
 - MacBook model MacBookPro18,2, 16 inch M1 Max 2021, 32GB
 - macOS version 21.1
 - AlDente Pro 
 - AlDente Version: 1.13
 - List of all enabled/disabled settings in AlDente:
 - 

**Additional context**
Debug file:
[aldentepro-debug-2022-01-17-11:11:26.pasta.zip](https://github.com/davidwernhart/AlDente/files/7881411/aldentepro-debug-2022-01-17-11.11.26.pasta.zip)

**Comment by gusost** [comment]
I am having the exact same issue.
Looking to downgrade.
I am running two users on my MacBook Air M1
