### ISSUE TITLE
Aldente does not work at all on my Mac

### ISSUE THREAD

**Issue by dogyoonlee** [davidwernhart/AlDente#553]
**Describe the bug**
Charge limit does not work at all on both ClamShell mode and normal mode. 
I set the limit as 75%, but it does not work at all. 
The battery have been charged until 100% regardless of AlDente setting.

**To Reproduce**

1. Just install the AlDente.
2. Does not work.

**Expected behavior**
Charge limit works. 

**Screenshots**
![image](https://user-images.githubusercontent.com/62277785/150070376-9c3f0c5e-91f9-4af7-be0d-e2060bc12d7f.png)
![image](https://user-images.githubusercontent.com/62277785/150070029-0abacfd9-a191-4160-b349-010c122acb2e.png)
![image](https://user-images.githubusercontent.com/62277785/150070043-60d7c86a-8758-4e63-9297-be7543b3a487.png)

**MacBook (please complete the following information):**
 - MacBook Pro 14' 2021, M1 Pro.
 - Momentary 12.1
 - AlDente Free.
 - 1.13 (But 1.12 was not work as same as latest version)
 - charge limit disable.

**Additional context**
Here is my debug file.
[aldentepro-debug-2022-01-19-14:23:44.pasta.zip](https://github.com/davidwernhart/AlDente/files/7894352/aldentepro-debug-2022-01-19-14.23.44.pasta.zip)

**Comment by williamhCode** [comment]
It seems like Aldente stopped working on my Macbook Pro 13' M1 after I updated Aldente to 1.13. I removed and installed 1.12 and it works.

**Comment by jeanqui** [comment]
Same here. Though 1.12 was working for me. (I'm on the pro plan but I dont think that should make a difference)

**Comment by dogyoonlee** [comment]
@williamhCode @jeanqui Thanks!! it works for me too. 
I close this issue!

**Comment by jeanqui** [comment]
Wait should the issue be closed? because it is still an issue with the new update?
