### ISSUE TITLE
AlDente cannot connect after 10 days to check license

### ISSUE THREAD

**Issue by MoDisaster** [davidwernhart/AlDente#566]
Hi!

After using AlDente pro on my old 2018 MacBook Pro with Intel i5 for several months without having any issues, I installed it on my new MacBook Pro 2021 16" with M1 Pro last week.
Today suddenly the AlDente battery icon in the menu bar disappeared and was replaced by the AlDente icon. After checking this I realized an issue with the license. Now I get an error message "No Connection - AlDente needs to connect every 10 days to check if license is valid [...]" (sorry, self-translated from German ;-) )
![image](https://user-images.githubusercontent.com/23238727/150832342-9bcfc0b9-0be4-4c46-8028-0f72626f65bd.png)

Under "Activate license" I can see the correct license.

Any ideas how to tell AlDente that I am obviously online?

Thanks in advance!

Best regards
Stefan

**Comment by MatthiasKerbl** [comment]
Hi @MoDisaster,

Please take a look at the following issue: #544

This should help until we fix it with an update.

Cheers,
Matthias
