### ISSUE TITLE
Not working when 100% (Aldente Free, M1 Air, Monterey)

### ISSUE THREAD

**Issue by lyukidon** [davidwernhart/AlDente#567]
**Describe the bug**

Before 100%( battery <= 99%), aldente works well, but after fully charged (100%), it does not work at all. 

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.
<img width="113" alt="image" src="https://user-images.githubusercontent.com/64675543/151018999-44b72e85-5b12-4999-809b-48db1e4c9a22.png">

**MacBook (please complete the following information):**
 - MacBook model
M1 Air (a2337)
 - macOS version
12.1 Monterey
 - AlDente Pro or AlDente Free?
 Aldente Free
 - AlDente Version?
 1.13
 - List of all enabled/disabled settings in AlDente:
60% limit

**Additional context**

**Comment by MatthiasKerbl** [comment]
Hi @lyukidon,

What exactly do you mean by "Not working when 100%"?
AlDente is meant to limit your charging to less than 100%

Cheers,
Matthias

**Comment by lyukidon** [comment]
Thank You for Reply, sir.

When Macbook turned off while plugged in, it was fully charged. So... After
I used my mac, I wanted just plug-In mode(? not charging mode), so I
thought that It didn't work.

Sorry for not good at English, and Have a good Day!! :)

2022년 1월 26일 (수) 오전 2:11, Matthias Kerbl ***@***.***>님이 작성:

**Comment by MatthiasKerbl** [comment]
Hi @lyukidon,

No worries. :)
You can read more about how AlDente handles powered-off MacBooks and Sleep Mode in our blog:
https://apphousekitchen.com/feature-explanation-stop-charging-when-powered-off-app-closed/
https://apphousekitchen.com/feature-explanation-stop-charging-when-sleeping/

However, these explanations are for AlDente Pro.

Cheers,
Matthias
