### ISSUE TITLE
Screen Saver doesn't Work

### ISSUE THREAD

**Issue by developeralioz** [davidwernhart/AlDente#571]
The screen saver does not work while AIdente is active. How can I solve this problem?

**Comment by MatthiasKerbl** [comment]
Hi @developeralioz,

The screen saver does not work when AlDente Pro has to disable sleep. This happens only in two scenarios:
1. You are using Discharge in clamshell mode.
2. You have Disable Sleep until Charge Limit activated and your MacBook is charging to the charge limit right now.

If you want to have your screen saver in every situation, you should deactivate Disable Sleep until Charge Limit and not use Discharge in clamshell mode.

Cheers,
Matthias
