### ISSUE TITLE
Screen stays on while lid is closed

### ISSUE THREAD

**Issue by layandreas** [davidwernhart/AlDente#573]
**Describe the bug**
The screen stays on even when lid is closed. Problem is solved after exiting AlDente.

**MacBook (please complete the following information):**
 - Macbook Air M1 2020
 - macOS Monterey 12.2
 - AlDente Free
 - AlDente 1.13
 

**Additional context**
It may be related to the sleep / discharging while sleeping issues reported here.   

**Screenshots**
![image](https://user-images.githubusercontent.com/79149948/151423702-febd2c35-f2ce-4fc3-8662-ec0a8a1807aa.png)

![image](https://user-images.githubusercontent.com/79149948/151423605-eb66985d-a625-4783-a4a4-e720307d3349.png)

**Comment by HayriGomer** [comment]
16 M1 Pro have the same issue. Restarting the app fixes it. 
Temp solution: turn off run at start up and launch it manually

**Comment by rafajrichard** [comment]
Can confirm, M1 Pro 14" does not go to sleep, exiting the app fixes it

**Comment by MatthiasKerbl** [comment]
> **Describe the bug** The screen stays on even when lid is closed. Problem is solved after exiting AlDente.
> 
> **MacBook (please complete the following information):**
> 
> * Macbook Air M1 2020
> * macOS Monterey 12.2
> * AlDente Free
> * AlDente 1.13
> 
> **Additional context** It may be related to the sleep / discharging while sleeping issues reported here.
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/79149948/151423702-febd2c35-f2ce-4fc3-8662-ec0a8a1807aa.png)
> 
> ![image](https://user-images.githubusercontent.com/79149948/151423605-eb66985d-a625-4783-a4a4-e720307d3349.png)

Hi @layandreas,

Thanks for reporting, I am currently testing a new beta version with a potential fix for this issue.
It would still be helpful if you could share a debug file of AlDente when this happens. https://apphousekitchen.com/how-to-generate-and-share-a-debug-file/

Cheers,
Matthias

**Comment by layandreas** [comment]
Hi @MatthiasKerbl,
sure I can do that if you provide me with a mail address to send it to (I can't attach it here unfortunately).

**Comment by MatthiasKerbl** [comment]
> Hi @MatthiasKerbl, sure I can do that if you provide me with a mail address to send it to (I can't attach it here unfortunately).

You can send it to news@apphousekitchen.com

**Comment by Alraku** [comment]
Hi, MacBook Pro 13" 2020 M1 same problem. Yesterday I was watching Netflix and before going sleep I checked the battery status - 75%. Today after like 12hours I received an email sound from my laptop - which was strange cause it should be in sleep mode. It occurred that display was on all night and the battery dropped to around 50%.

**Comment by MatthiasKerbl** [comment]
Hi There,

We have just released a new version of AlDente (1.14) which should fix the issues you experienced.
If you still encounter any of the issues after updating, please report back.

Download AlDente 1.14 here: https://github.com/davidwernhart/AlDente/releases

Cheers,
Matthias
