### ISSUE TITLE
Version 1.14 becomes unresponsive when updating helper

### ISSUE THREAD

**Issue by porcherie** [davidwernhart/AlDente#578]
**Describe the bug**
Version 1.14 becomes unresponsive when updating helper
![SCR-20220202-ejl](https://user-images.githubusercontent.com/50797800/152127722-f5c817ef-7ac5-4d75-9f19-712ee820a99b.png)

**To Reproduce**
when app starts it asks to update helper, click on ok button freezes app

**Expected behavior**
app should update helper

**MacBook (please complete the following information):**
 - MacBook Pro 13 M1
 - macOS version 12.2
 - AlDente Pro 
 - 1.14

**Comment by MatthiasKerbl** [comment]
Hi @porcherie,

Thanks for reporting. However, the app freezing when the helper is getting updated is completely normal. After the update of the helper, AlDente should work as intended again.

Cheers,
Matthias
