### ISSUE TITLE
aldente 1.14 update in broken loop

### ISSUE THREAD

**Issue by reagle** [davidwernhart/AlDente#581]
Homebrew delivered 1.14 to me today and upon relaunch it tells me to remove the old helper. I click the remove button, it asks for my password, and it says the removal was successful and to restart. But then I get the same pop-up upon restarting. I suspect that it isn't  removing anything because if I don't type in my password correctly, I get all the same behavior.

* aldente/1.14 (121B)
* OS: macOS 12.2 21D49 arm64

<img width="421" alt="Screen Shot 2022-02-04 at 12 42 10" src="https://user-images.githubusercontent.com/596814/152577299-038fd5e6-4659-4ed4-b306-9fd318c8f34f.png">
.

**Comment by reagle** [comment]
I followed the [manual instructions for uninstalling](https://apphousekitchen.com/how-to-uninstall-aldente-pro/). There was nothing in the /Library, and I deleted the folder in my own `~\Application Support\` but it still thinks something is installed...

**Comment by reagle** [comment]
I had not actually restarted. Doing that and logging in then seems to prompt the correct behavior. Two suggestions: make the direction in the popup in a larger font, and remind user to reboot upon completion if that is in fact needed.

**Comment by MatthiasKerbl** [comment]
> I had not actually restarted. Doing that and logging in then seems to prompt the correct behavior. Two suggestions: make the direction in the popup in a larger font, and remind user to reboot upon completion if that is in fact needed.

Hi @reagle,

I am glad it works now and thank you for the suggestions.

Cheers,
Matthias
