### ISSUE TITLE
Calibration being reset if mac goes to sleep

### ISSUE THREAD

**Issue by avxkim** [davidwernhart/AlDente#582]
**Describe the bug**
When i start the calibration mode, then my mac goes to sleep, calibration mode is cancelled. Is there a way to preserve this mode even after a sleep? Because it's impossible to discharge from 100% to 15% without putting a mac to sleep.

**To Reproduce**
1. Press **Start Calibration**
2. Put your Mac to sleep
3. Resume from sleep
4. Calibration mode is cancelled

**Screenshots**

Settings:

![image](https://user-images.githubusercontent.com/5739191/152591415-8e8a2585-ae70-40f1-bc32-f2cd2efbaee0.png)

**MacBook (please complete the following information):**
 - MacBookPro18,1
 - Monterey 12.2
 - AlDente Pro
 - AlDente Version 1.14
 - List of all enabled/disabled settings in AlDente:
 - On the screenshot above

**Comment by MatthiasKerbl** [comment]
Hi @avxkim,

Thank you for reporting this bug.
We will try to fix it with the next update.

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @avxkim,

We have just released AlDente 1.15 which fixed the issue you mentioned.
You can just do the update in AlDente or download the newest version here: https://github.com/davidwernhart/AlDente/releases

Cheers,
Matthias

**Comment by avxkim** [comment]
@MatthiasKerbl thanks, you're the man! 👍
