### ISSUE TITLE
After paying the order, no activation code is given

### ISSUE THREAD

**Issue by qicheng1995** [davidwernhart/AlDente#586]
Alipay bought the pro version, but did not send the activation code to the mailbox after payment.

Alipay order number: 2022020722001312581420095542

**Comment by MatthiasKerbl** [comment]
Hi @qicheng1995,

Please send me the email address you used to purchase AlDente to news@apphousekitchen.com. This is necessary for me to find your purchase.

Cheers,
Matthias
