### ISSUE TITLE
Paid for pro but did not get the license e-mail

### ISSUE THREAD

**Issue by susteem** [davidwernhart/AlDente#588]
Dear Aldente cs,
I bought the pro license, but unfortunately did not receive the e-mail with the license info. And since i did not the e-mail, there was no other way to reach you than here. 

Could you please help me out

Thanks
Bz.

**Comment by MatthiasKerbl** [comment]
> Dear Aldente cs, I bought the pro license, but unfortunately did not receive the e-mail with the license info. And since i did not the e-mail, there was no other way to reach you than here.
> 
> Could you please help me out
> 
> Thanks Bz.

Hi @susteem,

please send us the email address you used to purchase AlDente Pro to news@apphousekitchen.com

Cheers,
Matthias
