### ISSUE TITLE
Does not discharge at all even after 24 hours?

### ISSUE THREAD

**Issue by Emreler1** [davidwernhart/AlDente#589]
Hi,
I just started to use Aldente Free for my Macbook Air M1 connected to Caldigit USB C Dock which normally keeps it at 100% all the time in clamshell mode. 

I set the charge limit to 55% to give the app a try more than 24 hours ago. But I still have 100% charge. Is this just because clamshell mode? Or is there something else that I should do?
Best
Emre

**Comment by MatthiasKerbl** [comment]
Hi @Emreler1,

Clamshell mode is not supported by AlDente Free. You can try the Discharge feature while your MacBook display is open.

Cheers,
Matthias

**Comment by Emreler1** [comment]
Thanks a lot
Best
Emre
