### ISSUE TITLE
[Feature Request] Allow hiding of menu bar icon

### ISSUE THREAD

**Issue by SheaHolden** [davidwernhart/AlDente#59]
Not an "issue" but it would be nice feature. Allow for the menu bar icon to not be displayed. Once the user sets their desired max charge I imagine it will be rarely changed. 

Maybe make a simple toggle in the settings hide the menu bar icon, and "launching" the app again (opening it normally by clicking on the app icon) makes it re-appear? or something along those lines. I have not created any mac apps before so i am not sure how easy it is to do.

**Comment by TheMazus** [comment]
Hey Shea, a quick workaround for this problem is to simply exit AlDente after you have set the desired battery percentage. The maximum battery percentage will be saved in the system until you open AlDente and change the value again.

**Comment by dr3mro** [comment]
You can simply check it app is running then show setting if not then launch it

**Comment by joshuarobs** [comment]
I hide it with Bartender like all my other icons

**Comment by bigunyak** [comment]
Adding my vote for this small feature as well.
The app indeed doesn't need to be accessed often once desired settings have been configured, and taking space in the menu bar seem unnecessary.

**Comment by bruno-robert** [comment]
> Hey Shea, a quick workaround for this problem is to simply exit AlDente after you have set the desired battery percentage. The maximum battery percentage will be saved in the system until you open AlDente and change the value again.

quitting aldente on macOS Monterey 12.0.1 (21A559) doesn't seem to save the setting.
My battery will stop charging if it's open (in menubar) and continue charging the moment I quit aldente

**Comment by MatthiasKerbl** [comment]
> > Hey Shea, a quick workaround for this problem is to simply exit AlDente after you have set the desired battery percentage. The maximum battery percentage will be saved in the system until you open AlDente and change the value again.
> 
> quitting aldente on macOS Monterey 12.0.1 (21A559) on a M1 Macbook Pro doesn't seem to save the setting. My battery will stop charging if it's open (in menubar) and continue charging the moment I quit aldente

Hi @bruno-robert,

Due to the new hardware of the M1 MacBooks, we use a different pathway to control the charging behavior. Unfortunately, it's not possible anymore to use this workaround.

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi everyone,

We just released a new version of AlDente Pro which has a new option to disable the menu bar icon completely.

Cheers,
Matthias

**Comment by MikixIT** [comment]
"We just released a new version of AlDente Pro which has a new option to disable the menu bar icon completely."
I HAVE TO PAY FOR HIDING AN ICON?

**Comment by AldrinSalazar** [comment]
> Hi everyone,
> 
> We just released a new version of AlDente Pro which has a new option to disable the menu bar icon completely.
> 
> Cheers, Matthias

Paying to hide an icon is so low ... I was considering buying it but i won't give my money to idiots.

**Comment by StianOvrevage** [comment]
It IS possible to hide it in the free version, ref https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/issues/501
