### ISSUE TITLE
I didn't receive the license. Can anyone help me?

### ISSUE THREAD

**Issue by tiaagomiguel** [davidwernhart/AlDente#592]
Hello everyone!

I would like to contact someone responsible for the project, as I did not receive my license key after purchasing

thanks

@MatthiasKerbl @davidwernhart

**Comment by MatthiasKerbl** [comment]
Hi @tiaagomiguel,

Please send me the email address you used to purchase AlDente Pro to news@apphousekitchen.com.
I will look into what went wrong with your purchase.

Cheers,
Matthias
