### ISSUE TITLE
cannot Used in my old MacBook

### ISSUE THREAD

**Issue by manchunfai** [davidwernhart/AlDente#597]
**Describe the bug**
lt doesn't work in my old MacBook even through I reinstall AIDente and its helper.

**To Reproduce**
1. Go to Menu and See error "Helpv12: not found",and the limit still not works.
2. Click on "reinstall Helper"
3. write down my accout, and click 
4. Go to Menu and still See error "Helpv12: not found",and the limit still not works.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/57433586/153157713-8f0a203d-792e-403a-8ce4-be550c0f2e62.png)
![image](https://user-images.githubusercontent.com/57433586/153157931-3e71c828-ed24-4135-bb68-7b7d51b9382a.png)

**MacBook (please complete the following information):**
 - MacBook Pro 13.3 2018
 - MacOS 10.15.7
 - AlDente Free
 - 2.2

**Comment by MatthiasKerbl** [comment]
Hi @manchunfai,

You can try to uninstall AlDente completely manually. Please follow the steps in this guide: https://apphousekitchen.com/how-to-uninstall-aldente-pro/

Afterward, try a fresh reinstall of AlDente.

Another option would be to update to macOS 11 Big Sur or later and use the newest version of AlDente.

Cheers,
Matthias

**Comment by manchunfai** [comment]
你好，谢谢你的来信，明俊晖已收到你的信息。

**Comment by manchunfai** [comment]
I followed your advices and reset my SMC of Mac, but it's pity.
I try another way, and it works.
Follow that:
Open terminal,
And Enter:sudo launchctl enable system/com.davidwernhart.Helper

Just for reference.

**Comment by MatthiasKerbl** [comment]
Thanks for sharing, and I am glad it works now!

**Comment by twiz911** [comment]
> sudo launchctl enable system/com.davidwernhart.Helper

I was stuck in Al Dente 2.2 unable to install the helper, despite following all the tricks in these GitHub issues until I ran that command! Thanks :)

**Comment by manchunfai** [comment]
你好，谢谢你的来信，明俊晖已收到你的信息。
