### ISSUE TITLE
After restarting, the battery has changed from 80 to 77, is there a problem?

### ISSUE THREAD

**Issue by kentzh1** [davidwernhart/AlDente#602]
*I did a battery calibration on February 7th, the computer has been using the AlDente pro, and recently found a battery problem, i has been limiting the battery to 80%, but just after restarting, the battery suddenly changed to 77, which confused me ; I think there is a problem with the software control, restarting should not consume 3% of the battery, from my screenshot you can clearly see the battery gradient change, before I updated 12.2.1, this problem also appeared, when I shut down Or reboot and the 80% battery will change, I hope you can assist me in figuring out what is causing this problem.

*MacBook (please complete the following information):**
 - MacBook model (MacBook Pro2021)
 - macOS version (12.2.1)
 - AlDente Pro
 - AlDente 1.14
 - List of all enabled/disabled settings in AlDente:
 -
<img width="430" alt="WeChat78851251039d3e8e0095b442820317b9" src="https://user-images.githubusercontent.com/67768011/153645049-c3ca317a-fc30-4a35-968e-cbbede27612d.png">
<img width="397" alt="WeChat4ae46e9a847e2d08e9017e4550669d2e" src="https://user-images.githubusercontent.com/67768011/153645109-9a01b75a-acde-42b3-aad8-83181cdaf090.png">
<img width="843" alt="WeChat755a40d4820016f81e307473a48876be" src="https://user-images.githubusercontent.com/67768011/153645427-7d9d7274-2261-4589-9c01-51a427af2383.png">

**Comment by kentzh1** [comment]
Unfortunately, the same problem happened just now, the battery remained at 80 before the restart, and after the restart it became 77, I turned on the sailing mode, the above can not be adjusted, the difference of 5 will sail to 75 , I will close it and test again
<img width="849" alt="WeChat11f30e842024ac180c89567501eb8512" src="https://user-images.githubusercontent.com/67768011/154829719-244f1d9d-9080-46f7-a2b1-516e66d5d8f8.png">
.

**Comment by kentzh1** [comment]
agai
<img width="376" alt="WeChatf4d0b2bd08f17c7a05d785c855e97a09" src="https://user-images.githubusercontent.com/67768011/155162729-911a5c87-f4b1-4a4d-b384-bb0d22e749d2.png">
n

**Comment by MatthiasKerbl** [comment]
Hi @kentzh1,

From my experience, this is completely normal and I experience it sometimes too.

Cheers,
Matthias
