### ISSUE TITLE
This shit Aldente GUI

### ISSUE THREAD

**Issue by UnixCro** [davidwernhart/AlDente#610]
I don't find the program itself bad as it saves my Mac's battery. But what the heck. Why when I open Aldente is it in the dock & at the top of the menu bar at the same time. What if I accidentally quit it with "Force Quit". It can't be such an app can only be in the menu bar at the top. And I want it to run 24/7 and not charge my battery to 100 when it's off. Why is there no LaunchDaemon??!

**Comment by MatthiasKerbl** [comment]
Hi @UnixCro,

Earlier versions of AlDente only had the little icon in the menubar. However, many new users did not find it and complained about that. That’s why we made some changes such as adding the dock icon and opening the popup menu on every start of AlDente. I completely understand that those things are annoying for most users, that’s why you can easily disable them in the appearance settings in AlDente and they will stay disabled afterward.

Hope you understand our decision.

Cheers,
Matthias

**Comment by UnixCro** [comment]
Yes, that's exactly why it's only available in the Pro version .... Who thought up this crap

**Comment by MatthiasKerbl** [comment]
> Yes, that's exactly why it's only available in the Pro version .... Who thought up this crap

Hi @UnixCro,

The two options to disable the dock icon and to disable the popup on startup are available in the free version as well.

Cheers,
Matthias

**Comment by UnixCro** [comment]
And where?
<img width="544" alt="Bildschirmfoto 2022-02-25 um 10 53 03" src="https://user-images.githubusercontent.com/70098046/155694256-71f08b63-0088-4ba1-ab3f-c2bb20a8b220.png">

**Comment by MatthiasKerbl** [comment]
You have to deactivate "Beim Start anzeigen" and "Dock-Symbol anzeigen".

Cheers,
Matthias

**Comment by UnixCro** [comment]
LOL it worked. Sorry Bro for my Mistake.

Have a nice day
