### ISSUE TITLE
Lock Screen Battery Not Same as Unlocked

### ISSUE THREAD

**Issue by SkyBlue1903** [davidwernhart/AlDente#629]
Hey, can someone please tell be between this differences:
On lock screen:
![image](https://user-images.githubusercontent.com/63653579/158168586-eef1139b-7203-4b52-b930-b6e3e4b44323.jpeg)
When unlocked:
![image](https://user-images.githubusercontent.com/63653579/158168268-a6f1f12d-d1aa-4e16-b0ab-3bcec67b7b52.png)
Is AlDente supposed to be working correctly? I set charging limits to 50%. This thing kinda suspicious. Hope for the answer, thanks!

**Comment by andrewcrook** [comment]
I know AlDente doesn’t have control over that screen.
 I believe it maybe the norm.

**Comment by MatthiasKerbl** [comment]
Hi @SkyBlue1903,

this is just an inconsistency in macOS. AlDente is still doing its thing in the background.

Cheers,
Matthias
