### ISSUE TITLE
Big sur 11.1 doesn't work

### ISSUE THREAD

**Issue by ShiOGong** [davidwernhart/AlDente#63]
MacOS Big sur 11.1
MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)
Intel CPU
Version 1.2

**Comment by MuReinhard** [comment]
Version 1.0 is working

**Comment by kamranzafar** [comment]
It actually works on Big Sur if you uncheck "Use MacOS battery scale" in the settings.

**Comment by petter1** [comment]
I try it today with this Mac. It charged today to 100% with AlDente 1.2 and MacOS battery scale enabled. Now I let it discharge while I use my Mac and will then try alDente 1.2 with MacOS battery scale disabled.
![image](https://user-images.githubusercontent.com/13876117/105162548-0e753280-5b13-11eb-822b-f209f02f04e6.png)

**Comment by TheMazus** [comment]
> I try it today with this Mac. It charged today to 100% with AlDente 1.2 and MacOS battery scale enabled. Now I let it discharge while I use my Mac and will then try alDente 1.2 with MacOS battery scale disabled.
> 
> Edit: AlDente did not stop my Mac from charging above 80%
> 
> ![image](https://user-images.githubusercontent.com/13876117/105162548-0e753280-5b13-11eb-822b-f209f02f04e6.png)

Hi @petter1,
have you tried the latest version of AlDente? This one should work for you as well.

Matthias

**Comment by petter1** [comment]
@MatthiasKerbl everything works fine. I only had to restart the app some times back then in order to get it working 😇
