### ISSUE TITLE
Sail does not seem to be working

### ISSUE THREAD

**Issue by rpatrick2282** [davidwernhart/AlDente#631]
I have AlDente installed on two M1 MBP's running 12.3 and I am seeing the same issue with both. The batter will not discharge unless I select discharge from the AlDente menu. Example. I have the charge limit set at 60% with sail setting on 10% enabled. I charge the battery to 100% and it will not drop to the "charge limit". If I then discharge below the charge limit it will charge to the limit but will not "sail" down 10% it just sits at the current charge level.

**Comment by MatthiasKerbl** [comment]
Hi @rpatrick2282,

The Sailing Mode will never discharge your MacBook. It will only not charge your battery should the charge level fall by itself a little bit. Please read our blog article about the exact behavior of the Sailing Mode on our blog here: https://apphousekitchen.com/feature-explanation-sailing-mode/

Cheers,
Matthias
