### ISSUE TITLE
macOS 12.3 Update helper prompt spelling mistake? ninstall = uninstall

### ISSUE THREAD

**Issue by mvaneijgen** [davidwernhart/AlDente#639]
**Describe the bug**
Just updated to macOS 12.3 and got this popup. In the text the word "ninstall", should be "uninstall"? Seems a bit excessive to create a Github issue, but I didn't see any other way and thought you might want to know.

**To Reproduce**
1. Force app to update its helper 

**Screenshots**
![screenshot](https://imgur.com/L35jB0K.jpg)

**MacBook:**
 - AlDente Pro (Setapp) 1.15.2
- macOS Monterey
- Version 12.3
- MacBook Pro (15-inch, 2017)
- Processor 3,1 GHz Quad-Core Intel Core i7
- Memory GB 16 GB 2133 MHz LPDDR3
- Graphics Radeon Pro 560 GB
- Intel HD Graphics 630 1536 MB:

**Comment by MatthiasKerbl** [comment]
Hi @mvaneijgen,

this typo just got fixed with the newest update.

Cheers,
Matthias
