### ISSUE TITLE
After a reboot or wake, battery charges for a few mins 

### ISSUE THREAD

**Issue by Limeybastid** [davidwernhart/AlDente#644]
When I restart or wake my  already plugged in MBP M1 14" it charges for about a minute or two then stops. Each time this occurs, it adds another 1% level to the user set charge limit value. Is this behavior normal? In essence, I had originally set my charge limit to 70%, after a few restarts and wakes from sleep the battery shows 75% charge level.

**Comment by MatthiasKerbl** [comment]
> When I restart or wake my already plugged in MBP M1 14" it charges for about a minute or two then stops. Each time this occurs, it adds another 1% level to the user set charge limit value. Is this behavior normal? In essence, I had originally set my charge limit to 70%, after a few restarts and wakes from sleep the battery shows 75% charge level.

Hi @Limeybastid,

This behavior is completely normal. AlDente is not able to limit charging when your MacBook is turned off. Therefore, during a restart, your MacBook will charge a little bit each time. Unfortunately, so far we have not found any solution for this problem.

Cheers,
Matthias
