### ISSUE TITLE
MacBook ignores charging-limit

### ISSUE THREAD

**Issue by Muri96** [davidwernhart/AlDente#648]
my MacBook is charging to 100% although I set 60%. The slider stays at 60%.
Also the icon jumps from charge to pause - see video:

 - MacBook Pro 2018
 - macOS Monterey12.3.1
 - AlDente Pro
 - AlDente Version 1.15.2

https://user-images.githubusercontent.com/103127120/162011259-736afebe-6ede-45d2-b3b5-bf06338ece26.mov

**Comment by Muri96** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots or screen recordings to help explain your problem.
> 
> **MacBook (please complete the following information):**
> 
> * MacBook model (https://support.apple.com/en-us/HT201608)
> * macOS version (https://support.apple.com/en-us/HT201260)
> * AlDente Pro or AlDente Free?
> * AlDente Version?
> * List of all enabled/disabled settings in AlDente:
> 
> **Additional context** Add any other context about the problem here.

**Comment by MatthiasKerbl** [comment]
Hi @Muri96,

Did you do a macOS update lately?

**Comment by Muri96** [comment]
yes, a view days ago

**Comment by MatthiasKerbl** [comment]
Hi @Muri96,

This is probably the reason for the issues you encounter.

Please try the following to resolve this issue:

1. Shut Down your MacBook completely.
2. Unplug the power supply from the socket.
3. Wait a couple of minutes.
4. Restart your MacBook and plug it in again.

Does it work again?

Cheers,
Matthias
