### ISSUE TITLE
lock device when "Disable Sleep Until Charge Limit" is active

### ISSUE THREAD

**Issue by dbz2k** [davidwernhart/AlDente#660]
**Is your feature request related to a problem? Please describe.**
Locking device when Disable Sleep Until Charge Limit is active.

**Describe the solution you'd like**
An option to pick lock option like automatically lock device when Disable Sleep Until Charge is enabled, and active.

**Describe alternatives you've considered**
I think I could mix this with amphetamine to lock device somehow maybe to lock device?
**Additional context**

**Comment by MatthiasKerbl** [comment]
Hi @dbz2k,

We released AlDente Pro 1.18 a couple of days ago which will now lock your MacBook automatically when Disable Sleep Until Charge Limit is enabled and the lid gets closed.

Cheers,
Matthias
