### ISSUE TITLE
Screen brightness keeps shifting using Discharge 

### ISSUE THREAD

**Issue by tomwolsky** [davidwernhart/AlDente#662]
When I use Discharge in AlDente the screen brightness intermittently gets darker and brighter. I have Display System Preferences  set to automatic brightness. The room brightness isn't changing. The slider in Display moves up and down. The screen dims and brightens. If I shut down AlDente the brightness is constant. 

I expected the screen brightness to remain constant. 

Screen recording is too large. 70 MB. 

2021 M1 Max 14" MacBook Pro
macOS 12.4b2
AlDente Pro
<img width="434" alt="Screen Shot 2022-04-21 at 13 22 00" src="https://user-images.githubusercontent.com/18217685/164527639-1dd0d120-602c-4a09-9ff3-5e08dfdadea7.png">

**Comment by tomwolsky** [comment]
I'm not seeing this in 12.3.1 on the same machine.

**Comment by city17** [comment]
I'm having the same issue that screen brightness dims intermittently since using AlDente Pro. It also always happens when I switch from a user account without AlDente turned on to my main user account which does have AlDente running. 

This is on a Macbook Pro 14 M1 2021. 

I have automatic screen brightness adjustment turned off on both accounts.

Any remedies/suggestions @MatthiasKerbl ?

**Comment by MatthiasKerbl** [comment]
> I'm having the same issue that screen brightness dims intermittently since using AlDente Pro. It also always happens when I switch from a user account without AlDente turned on to my main user account which does have AlDente running.
> 
> This is on a Macbook Pro 14 M1 2021.
> 
> I have automatic screen brightness adjustment turned off on both accounts.
> 
> Any remedies/suggestions @MatthiasKerbl ?

Hi @city17,

Do you have the macOS setting "Slightly dim the display on battery on" turned on?
If yes, try to turn it off.
Furthermore, if you want to have AlDente working on multiple user accounts, check out our tutorial **[here](https://apphousekitchen.com/fast-user-switching-explanation-and-tutorial/)**.

Cheers,
Matthias

**Comment by city17** [comment]
> > I'm having the same issue that screen brightness dims intermittently since using AlDente Pro. It also always happens when I switch from a user account without AlDente turned on to my main user account which does have AlDente running.
> > This is on a Macbook Pro 14 M1 2021.
> > I have automatic screen brightness adjustment turned off on both accounts.
> > Any remedies/suggestions @MatthiasKerbl ?
> 
> Hi @city17,
> 
> Do you have the macOS setting "Slightly dim the display on battery on" turned on? If yes, try to turn it off. Furthermore, if you want to have AlDente working on multiple user accounts, check out our tutorial **[here](https://apphousekitchen.com/fast-user-switching-explanation-and-tutorial/)**.
> 
> Cheers, Matthias

Thanks Matthias, turning that setting off seems to have solved the problem as far as user-switching goes. Will install AlDente on the other user to and hopefully it works all normal then! Thanks!
