### ISSUE TITLE
Does not know to scooch out from under the notch

### ISSUE THREAD

**Issue by madler** [davidwernhart/AlDente#663]
AlDente on the menu bar will happily hide under the notch on an M1 MacBook Pro (14"). See photo:

![aldente-hidden](https://user-images.githubusercontent.com/240717/164945762-55f0cee2-5910-4bd7-99a0-631d9f8ab52c.jpg)

I had to take a photo to show that, since interestingly a screen shot (command-shift-4) does not try to simulate the notch. It shows AlDente on the command bar, even though there are no screen pixels there!

<img width="409" alt="aldente-undernotch" src="https://user-images.githubusercontent.com/240717/164945524-d32bc755-7d07-4f62-b202-1cfeddf03816.png">

1. Buy a 14" M1 MacBook Pro with a notch in the screen.
2. Install AlDente.
3. Have enough menu bar icons to the right of it for AlDente to be under the notch.

I would expect that the menu bar item would scooch to the left to be visible, like other ones. Actually, it looks like there's room to the right of the notch. Either way, I would expect it to not be hidden under the notch.

MacBook Pro 18,4
macOS 12.3.1
AlDente Free 1.16.1
charge limit 80%

**Comment by MatthiasKerbl** [comment]
Hi @madler,

Unfortunately, we are not able to reproduce this issue on our 16" M1 MacBook Pro. For us, the icon appears left of the last icon and right of the notch.

Do you still encounter this issue?
Did you try to reinstall AlDente?

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @madler,

Do you still experience the AlDente icon in the middle of the menu bar with our newest version AlDente 1.19.2?

Cheers,
Matthias

**Comment by madler** [comment]
It seems to behave differently now. Instead of hiding under the notch, the menu bar icon just goes away. It does not scooch over to the other side of the notch. However googling seems to indicate that that is Apple's intended behavior.

What I am doing is turning on and off the Accessibility menu item in System Preferences. When it is off, I see AlDente. When it is on, the AlDente menu bar item is replaced by the Accessibility menu bar ico.

<img width="1512" alt="Screen Shot 2022-11-05 at 10 11 16 PM" src="https://user-images.githubusercontent.com/240717/200155371-2cbe949d-0edd-4262-adcb-b853c6107f69.png">

<img width="1506" alt="Screen Shot 2022-11-05 at 10 06 15 PM" src="https://user-images.githubusercontent.com/240717/200155375-11a27753-a6c9-4702-bffc-702a62acea06.png">

Nothing ends up getting hidden under the notch.

I am running macOS 12.6.1 and AlDente Free 1.19.2.

**Comment by ysomad** [comment]
Getting the same issue with aldente pro 1.22.3
m1 pro 16

on open aldente appears and then dissapears behind the notch

<img width="751" alt="Screenshot 2023-10-20 at 2 15 47 PM" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/49870662/e2ab35a0-89b4-4099-b142-0a3cb9c72160">
<img width="905" alt="Screenshot 2023-10-20 at 2 15 53 PM" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/49870662/6d562800-7a94-4ab2-9b4f-b3d4e6769e88">

venthura 13.5.1
