### ISSUE TITLE
AlDente does not function

### ISSUE THREAD

**Issue by yangyijane** [davidwernhart/AlDente#666]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**MacBook (please complete the following information):**
 - MacBook model (https://support.apple.com/en-us/HT201608)
 - macOS version (https://support.apple.com/en-us/HT201260)
 - AlDente Pro or AlDente Free?
 - AlDente Version?
 - List of all enabled/disabled settings in AlDente:

**Additional context**

**Comment by yangyijane** [comment]
I used it for over a year. It works well. However, it stopped functioning recently. I tried to relaunch it, but it did not work. Please help to

**Comment by MatthiasKerbl** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots or screen recordings to help explain your problem.
> 
> **MacBook (please complete the following information):**
> 
> * MacBook model (https://support.apple.com/en-us/HT201608)
> * macOS version (https://support.apple.com/en-us/HT201260)
> * AlDente Pro or AlDente Free?
> * AlDente Version?
> * List of all enabled/disabled settings in AlDente:
> 
> **Additional context** Add any other context about the problem here.

Hi @yangyijane,

Please fill out all the questions so that I can better understand you issue.

Cheers,
Matthias
