### ISSUE TITLE
Process name of AlDente missing

### ISSUE THREAD

**Issue by marchpane** [davidwernhart/AlDente#673]
**Describe the bug**
When I go in the aktivity manager and look for AlDente I can not see the name of it. Only the logo is visible.

**To Reproduce**
1. Open the activity monitor
2. Search for AlDente

**Expected behavior**
Not only the logo is visible, but also the process name

**Screenshots**

<img width="205" alt="Bildschirmfoto 2022-05-04 um 21 52 40" src="https://user-images.githubusercontent.com/89104892/166815774-5c3a530d-a2f2-4332-9e0d-87729bd02ebf.png">

**MacBook:**
 - M1 Air
 - Monterey 12.3.1
 - AlDente Pro 1.16.1

**Comment by MatthiasKerbl** [comment]
Hi @marchpane,

Thanks for sharing, we are currently investigating this issue.

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @marchpane,

We could fix this issue and have just released a new version AlDente 1.17.1.
https://github.com/davidwernhart/AlDente/releases/tag/1.17.1

Cheers,
Matthias
