### ISSUE TITLE
Cannot install the helper successfully

### ISSUE THREAD

**Issue by fragrusti** [davidwernhart/AlDente#680]
I use AlDente since a while on my M1 Macbook Air. I purchased the Pro Lifetime license since it is a very useful piece of software.

It was working perfectly, suddendly it returned to its original icon (the spaghetti one) and lost all the information and the helper.

Then I tried to reinstall the helper: even if it says that it is installed correctly, nothing happens and the battery bar remains grey.

Moreover i tried to remove and reinstall the helper and aldente itself - nothing. I tired version 1.17 and 1.17.1 nothing changes.

I attach the content of my pasta (pure genious!) debug file (renamed in txt otherwise GH would not let me to attach it) and a screen shot of the greyed battery bar. [aldentepro-debug-2022-05-13-12:44:16.pasta.txt](https://github.com/davidwernhart/AlDente/files/8686454/aldentepro-debug-2022-05-13-12.44.16.pasta.txt)

<img width="434" alt="Schermata 2022-05-13 alle 12 56 19" src="https://user-images.githubusercontent.com/3276708/168269424-72934b9e-f23a-4832-9c96-5ea552f8c0d1.png">

Thank you in advance,
FrAg

**Comment by MatthiasKerbl** [comment]
Hi @fragrusti,

your debug file looks good and the helper communication seems to work fine.
As simple as it might sound, could you try the following:

1. unplug your MacBook from the power supply
2. turn off your MacBook
3. close the display 
4. wait for at least 2 minutes
5. restart your MacBook and plug it in again

Does AlDente work again?

Cheers,
Matthias

**Comment by fragrusti** [comment]
Dear Matthias, 

it worked! Thank you so much. Very appreciated.

Ciao,
FrAg

**Comment by yogithesymbian** [comment]
how to permanent install ? when restart its always need to install again so sometime i forgot then charge until 100% damned

**Comment by wangxiang4** [comment]
> how to permanent install ? when restart its always need to install again so sometime i forgot then charge until 100% damned mbp m1 sequoia

[Stuck at install helper app after macos update](https://github.com/AppHouseKitchen/AlDente-Battery_Care_and_Monitoring/issues/1030#issuecomment-3317143286)
