### ISSUE TITLE
I've purchased license but it didn't come.

### ISSUE THREAD

**Issue by laskdjlaskdj12** [davidwernhart/AlDente#691]
Hi, if you have a question about AlDente, please use the Discussions section of Github: https://github.com/davidwernhart/AlDente/discussions

I've purchase Aldente pro license but it didn't come any license email.

could you check it please?

my email address is ```array.locals_0b@icloud.com```  or ``` laskdjlaskdj12@gmail.com```

**Comment by MatthiasKerbl** [comment]
Hi @laskdjlaskdj12,

I am sorry you did not receive the license code.
I have sent the emails again and you should have already received them.

Cheers,
Matthias
