### ISSUE TITLE
I've purchase Aldente pro license but it didn't come any license email...

### ISSUE THREAD

**Issue by Cloudda** [davidwernhart/AlDente#698]
I've purchase Aldente pro license but it didn't come any license email.

could you check it please?

(please, send me a pm for my email)

**Comment by MatthiasKerbl** [comment]
> I've purchase Aldente pro license but it didn't come any license email.
> 
> could you check it please?
> 
> (please, send me a pm for my email)

Hi @Cloudda,

There are multiple possible reasons why you did not get your license code after the purchase:

- Sometimes it takes up to 30 Minutes for the purchase emails to go through.
- The purchase emails end up in the junk email folder.
- You had a typo in the email address during your purchase.
- Failures of the payment networks/providers.

Please contact the support team of our payment provider Paddle at [assist@paddle.com](mailto:assist@paddle.com) and include the email address you used to purchase AlDente Pro. The Paddle support will try to solve your issue as fast as possible.

Cheers,
Matthias
