### ISSUE TITLE
Discharge stops working properly after long Sleep

### ISSUE THREAD

**Issue by happy-looter** [davidwernhart/AlDente#700]
**Describe the bug**
Discharge stop working after I leave my Macbook to sleep for a while.

**To Reproduce**
1. Put Macbook to sleep
2. Wake it up after a some time (30 minutes or more)
3. Click on Discharge

**Expected behavior**
Discharge button should stay active and battery should stop charging.

**Screenshots**
![Discharge Bug](https://user-images.githubusercontent.com/42674423/173122370-e821f534-ab76-45ea-a152-4746a36963f4.gif)

**MacBook (please complete the following information):**
 - MacBook model: MacBookPro17,1 / MacBook Pro (13-inch, M1, 2020)
 - macOS version 12.4
 - AlDente Free 1.17.1
 - List of all enabled/disabled settings in AlDente:
      - Check Updates Automatically (ON)
      - Launch at Login (ON)
      - Only AlDente Icon (ON)
      - Show on Startup (OFF)
      - Show Dock Icon (OFF)

**Additional context**
Discharge works normally again after restart.

**Comment by MatthiasKerbl** [comment]
Hi @happy-looter,

Is it possible that in your example the current battery percentage is equal to or above the set charge limit in AlDente?

Discharge only discharges your MacBook to the set Charge Limit in AlDente. Therefore, if your current battery percentage is equal to or above the set Charge Limit in AlDente, Discharge does not do anything.

Cheers,
Matthias

**Comment by happy-looter** [comment]
Hi @MatthiasKerbl ,

thank you for your reply. My charge limit is set to 80%, my actual charge is 81%. I would expect that when I click discharge that charging is disabled until my battery is at 20% and that it will then start charging again. Is that an incorrect assumption?

**Comment by MatthiasKerbl** [comment]
> Hi @MatthiasKerbl ,
> 
> thank you for your reply. My charge limit is set to 80%, my actual charge is 81%. I would expect that when I click discharge that charging is disabled until my battery is at 20% and that it will then start charging again. Is that an incorrect assumption?

Hi @happy-looter,

This assumption is incorrect. You can read more about the Discharge feature on our blog here: https://apphousekitchen.com/feature-explanation-discharge/

Cheers,
Matthias

**Comment by happy-looter** [comment]
Hi @MatthiasKerbl ,

ok, it seems I misunderstood the point of discharge. Is there a paid feature that does what I thought discharge would do?

**Comment by MatthiasKerbl** [comment]
> Hi @MatthiasKerbl ,
> 
> ok, it seems I misunderstood the point of discharge. Is there a paid feature that does what I thought discharge would do?

Hi @happy-looter,

You could use Discharge manually to do what you described by switching the Charge Limit between 20 and 80%. The question is, however, why you would want to do that? Since most battery research indicates that leaving the battery at a healthy charge limit of 80% for example and using the power brick as an energy source instead of the battery for the most part is the way to go when you want to keep your battery capacity for as long as possible. This is also the reason why we did not implement a "Pendle/swing"-feature like that. Our paid version AlDente Pro offers even more features and possibilities to keep your battery healthy such as Heat Protection, Sailing Mode, Calibration Mode,...

Cheers,
Matthias

**Comment by happy-looter** [comment]
Hi @MatthiasKerbl ,

I really appreciate your thorough answer! I don’t know anything about battery health, I just know I ruined my last battery by keeping it at 100% all the time. I trust you in what you say so I am happy with the way it works. I will close this thread now, thanks for your support. If I still use AlDente in half a year, I will support you guys with a Pro version ;)
