### ISSUE TITLE
Allow for integration of low power mode / high performance mode, easily toggalable such as like Cooldown

### ISSUE THREAD

**Issue by arooni** [davidwernhart/AlDente#710]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

https://www.producthunt.com/products/cooldown#cooldown-1

except, have it working.  

That app for whatever reason doesn't seem to work on my 2021 Macbook Pro m1 max.  

Would be nice to have a few more features, like "when I'm down to 30% toggle it etc, or have it clearly togglable from the aldente menubar option itself)

**Describe alternatives you've considered**

**Additional context**

**Comment by MatthiasKerbl** [comment]
Hi @arooni,

Good idea and thank you for your input.
We already have a thread for this feature request open: #603 

Cheers,
Matthias
