### ISSUE TITLE
Charged to 100% after Calibration, even if limit was set 

### ISSUE THREAD

**Issue by Volodymyr-13** [davidwernhart/AlDente#712]
**Describe the bug**
Charged to 100% after Calibration, even if limit was set 

**To Reproduce**
1. Start-finish calibration.
2. Notice 81% charge at the end.
3. Close the lid.
4. Open next day - notice 100% battery charge.

**Expected behavior**
Charge limit should work after calibration.

**Screenshots**

<img width="406" alt="Screenshot 1" src="https://user-images.githubusercontent.com/3391456/176851710-5ab5816d-8ab9-45b0-86b3-0df5108b7d04.png">

**MacBook (please complete the following information):**
 - MacBook Pro 14"M1
 - macOS 12.4
 - AlDente Pro ?
 - AlDente 1.17.1?
 - List of all enabled/disabled settings in AlDente:

<img width="432" alt="Screenshot" src="https://user-images.githubusercontent.com/3391456/176851721-81fcbc48-b614-456b-9a05-4f51c5ddc77d.png">

**Comment by jymr92** [comment]
Me, too.

**Comment by andiweli** [comment]
Me too.
Pro License and keeps charging - limit is 80%. But charged up to 86 now even if I press "Discharge button".

**Comment by Volodymyr-13** [comment]
Discharge actually worked for me, only this.. is ok..

**Comment by andiweli** [comment]
Discharge starts discharging for a few seconds, then aborts and continues charging.
I am on 89% now - set the limit to 90% - perhaps it stops again.

**Comment by andiweli** [comment]
Nope... charging happily ... 91% now.
Settings will be overruled.

**Comment by schwedi** [comment]
Me too,
86% and there will always be short phases with the + icon , and it continues to charge
MacBook Pro 2017 15",  macOS Monterrey 12.5
<img width="433" alt="image" src="https://user-images.githubusercontent.com/15823784/183305121-b5e0ca93-162c-4393-b986-28be98f90b7e.png">

**Comment by iamkevindu** [comment]
Same issue here. Al Dente goes back to charging mode even after I click the discharge button.

**Comment by MatthiasKerbl** [comment]
Hi everyone,

We have just released AlDente Pro 1.19.2 which has a fix for the Calibration Mode charging to 100% after the calibration bug.

Cheers,
Matthias
