### ISSUE TITLE
Paypal

### ISSUE THREAD

**Issue by ashutekale** [davidwernhart/AlDente#717]
Please enable Paypal for purchasing as I would not enter my credit card details everywhere.

**Comment by MatthiasKerbl** [comment]
Hi @ashutekale,

Paypal should be enabled and when I try to buy AlDente Pro, I can choose Paypal as well.
Where are you located? Maybe it is not possible to use Paypal in every country.

Cheers,
Matthias

**Comment by ashutekale** [comment]
@MatthiasKerbl India, kindly request you to please enable so I can buy it ASAP.

**Comment by MatthiasKerbl** [comment]
> @MatthiasKerbl India, kindly request you to please enable so I can buy it ASAP. Apple Pay is not available in India.
> 
> <img alt="image" width="568" src="https://user-images.githubusercontent.com/31849838/180135088-676bf58f-d3de-42f9-bcc0-78552effe598.png">

Hi @ashutekale,

You can use a Mastercard or Visacard to pay. Since all of our payments are managed by our payment provider Paddle, I will forward your request to them.

Cheers,
Matthias

**Comment by ashutekale** [comment]
I want to use Paypal please, I do not want to put my card details wherever required. Can you please enable it?

**Comment by MatthiasKerbl** [comment]
> I want to use Paypal please, I do not want to put my card details wherever required. Can you please enable it?

Hi @ashutekale,

I am sorry but I can not do more than tell our payment provider Paddle.com to enable PayPal in India as well. Otherwise, you can try a VPN.

Cheers,
Matthias
