### ISSUE TITLE
Limit charging power on high-power faster chargers

### ISSUE THREAD

**Issue by theonefoster** [davidwernhart/AlDente#719]
**Is your feature request related to a problem? Please describe.**
Not really, but it'd be nice to use an e.g. 65-watt or 100-watt charger but limit the charging to (for example) 20 watts if the full charge power isn't needed. It's better for battery health to charge more slowly, so if I'm charging overnight or otherwise have plenty of time to charge, a slower charge would be preferred.

**Describe the solution you'd like**
An option to cap maximum charge power to a custome level, e.g. "don't accept charge faster than 20 watts". The option should be removable so that if I need to charge quickly I can still fast charge.

**Comment by MatthiasKerbl** [comment]
Hi @theonefoster,

Thank you for your input and we would love to implement a feature like that, however, we have not found a possibility yet to alter the charging speed.
Since we already have a feature request open for this here #426, I will close this issue.

Cheers,
Matthias
