### ISSUE TITLE
Inconsistent charge limit / menu bar indicator

### ISSUE THREAD

**Issue by lazarjov** [davidwernhart/AlDente#720]
**Describe the bug**
With the charge limit set at 80%, the menu bar indicator stops charging at 81% and stays there.

**To Reproduce**
1. Set charge limit to 80%
2. Plug in the MacBook to charge
3. Wait until it reaches 81% and stops charging

**Expected behavior**
The indicator should be the same as the charge limit.

**Screenshots**
![SCR-20220711-mk1](https://user-images.githubusercontent.com/26031133/178350923-46461ffc-bc43-4a43-a454-95c6573f3d6b.png)

**MacBook (please complete the following information):**
 - MacBook Pro (16-inch, 2021)
 - macOS version 12.4 
 - AlDente Pro
 - AlDente Version 1.17.1
 - List of all enabled/disabled settings in AlDente:
 - Sailing Mode: ON
 - Heat Protection: ON
 - Stop charging when sleeping: OFF
 - Stop charging when app closed: OFF
 - Disable Sleep until Charge Limit: OFF
 - Hardware Battery Percentage: OFF

**Additional context**

**Comment by MatthiasKerbl** [comment]
Hi @lazarjov,

2-3% is within the margin of error. This is due to the battery percentage only being a good guess instead of a perfectly precise measurement of the charging state.

Cheers,
Matthias
