### ISSUE TITLE
Pro Serial Number

### ISSUE THREAD

**Issue by dogface19566** [davidwernhart/AlDente#723]
Hello,

It would be nice if on your website you had a contact email address for billing issues. I paid for the Pro addition of AlDente twice (thinking the first payment did not go through, it did), but I never received any email from you confirming my payment so I have not received my serial number. Please let me know what I need to do to my serial number and the email address for Pro support?

**Comment by MatthiasKerbl** [comment]
Hi @dogface19566,

I am sorry you experienced issues when buying AlDente Pro.

Here is a part of our FAQ on our pricing website:

"[I Did Not Get The License Code Or Any Receipt Emails After Buying AlDente Pro!](https://apphousekitchen.com/pricing/)

There are multiple reasons why you did not get your license code after the purchase:

Sometimes it takes up to 30 Minutes for the purchase emails to go through.
The purchase emails end up in the junk email folder.
You had a typo in the email address during your purchase.
Failures of the payment networks/providers.
Please contact the support team of our payment provider Paddle at [assist@paddle.com](mailto:assist@paddle.com) and include the email address you used to purchase AlDente Pro. The Paddle support will try to solve your issue as fast as possible."
