### ISSUE TITLE
Charge limit

### ISSUE THREAD

**Issue by soundfuze** [davidwernhart/AlDente#727]
Hello.
I have a question about charge limit.

I set 60% of charge limit. The instruction under 'Charge Settings' says that charge limit can persist when powered off or in sleep mode. However, when I turn my Macbook off, it won't stop charging when it reaches 60%, but it keeps charging til 100%.

I was wondering if this function is only supported Pro version.

**MacBook (please complete the following information):**
 - Macbook pro Mid 2014
 - Big Sur / 11.6.6
 - AlDente Free
 - 1.17.1
 - Every function disable.

**Comment by MatthiasKerbl** [comment]
> Hello. I have a question about charge limit.
> 
> I set 60% of charge limit. The instruction under 'Charge Settings' says that charge limit can persist when powered off or in sleep mode. However, when I turn my Macbook off, it won't stop charging when it reaches 60%, but it keeps charging til 100%.
> 
> I was wondering if this function is only supported Pro version.
> 
> **MacBook (please complete the following information):**
> 
> * Macbook pro Mid 2014
> * Big Sur / 11.6.6
> * AlDente Free
> * 1.17.1
> * Every function disable.

Hi @soundfuze,

You are right, this functionality is only included in AlDente Pro. https://apphousekitchen.com/pricing/

Cheers,
Matthias
