### ISSUE TITLE
Difference between AlDente an BigSur optimized battery

### ISSUE THREAD

**Issue by F3000** [davidwernhart/AlDente#73]
Which is better when MacBook is 95% of the time at power cord ?

**Comment by alexw9988** [comment]
I have mine plugged in all day and MacOS just kept charging to 100%, because it couldn't really "learn" any charging habit. 
AlDente works great, just make sure you leave "Use MacOS battery scale" option unchecked if you're running Big Sur.

**Comment by F3000** [comment]
Ok . Do you use intel or M1 chip ?

**Comment by alexw9988** [comment]
Intel

**Comment by Drallas** [comment]
What does "Use MacOS battery scale" exactly do?

**Comment by TheMazus** [comment]
Hey Drallas,

Normally, there is an offset of a couple of percentage points between the systems SoC and the shown SoC. The feature "Use MacOS battery scale" tries to decrease this offset. In a nutshell, when this feature is activated the SoC you set in AlDente will be closer to the "real" SoC shown in MacOS.

Best regards,

TheMazus

**Comment by emadpres** [comment]
@alexw9988 Based on what @TheMazus said, it seems we should have `Use MacOS battery scale` checked as it's a good thing. Why did you recommend turning it off?

**Comment by emadpres** [comment]
And by the way, where is the `Use MacOS battery scale` option? I can't find it in `2.1`.

**Comment by TheMazus** [comment]
Hi @emadpres,
we removed the "Use MacOS battery scale" option in AlDente 2.1 since we use a different pathway to get as close to the MacOS battery scale as possible.

Best regards,
Matthias
