### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by aldisw** [davidwernhart/AlDente#731]
When I go to settings to open calibration (which I do once monthly), I now get a screen showing option to uninstall reinstall Helper (which I attempted but the buttons don't seem to be live), and I can't get to calibration. This is a new problem.

MacBook Air M1 
Version 15.5 (17613.2.7.1.8) Monterrey

**Comment by MatthiasKerbl** [comment]
> When I go to settings to open calibration (which I do once monthly), I now get a screen showing option to uninstall reinstall Helper (which I attempted but the buttons don't seem to be live), and I can't get to calibration. This is a new problem.
> 
> MacBook Air M1 Version 15.5 (17613.2.7.1.8) Monterrey

Hi @aldisw,

When you open settings, you have three groups of settings on top (General Settings, Charge Settings, Appearance). If you want to use the Calibration Mode, you just have to go to Charge Settings.

Cheers,
Matthias
