### ISSUE TITLE
Can AlDente supported MacOS Catalina, I'm using Catalina.

### ISSUE THREAD

**Issue by Singer-JJ-Lin** [davidwernhart/AlDente#739]

**Comment by MatthiasKerbl** [comment]
Hi @Singer-JJ-Lin,

You can try the very old version of AlDente Classic 2.2 here: https://github.com/davidwernhart/AlDente/releases/tag/2.2
This should be the last one compatible with Catalina. However, we would definitely recommend updating to the newest version of macOS and AlDente to enjoy the most stable experience and most features.

Cheers,
Matthias

**Comment by spqr1337** [comment]
Thank you, seu lindo! S2
