### ISSUE TITLE
Make menu bar icon shade consistent with other apps

### ISSUE THREAD

**Issue by skidding** [davidwernhart/AlDente#74]
Hey, love the app. Maybe I'm the only one bothered by this, but the AlDente icon sticks out from all the other ones, especially in the inactive screens. It would be nice if it would blend in more design-wise. I might be wrong, but I think the other icons use transparency to represent greys, whereas AlDente uses grey colours with 0 transparency.

Active screen
<img width="676" alt="image" src="https://user-images.githubusercontent.com/250750/104019428-38019600-51c4-11eb-9433-3a26cbe89734.png">

Inactive screen
<img width="659" alt="image" src="https://user-images.githubusercontent.com/250750/104019461-43ed5800-51c4-11eb-8224-05203b086f16.png">

**Comment by joshuarobs** [comment]
This also triggers my ocd a little, but my current workaround for now is using Bartender to hide unnecessary icons
