### ISSUE TITLE
I paid for the Lifetime License 1 hour ago, but I don't receive the E-mail yet, What should I do?

### ISSUE THREAD

**Issue by jamesone2000** [davidwernhart/AlDente#753]
Hello,
       I paid for the Lifetime License 1 hour ago, but I don't receive the E-mail yet, What should I do?Should I wait for the E-mail, or  should   I send another e-mail address? I can't find the support e-mail, so I can only send the support request here. Please help me!
      Thank you!

**Comment by MatthiasKerbl** [comment]
Hi @jamesone2000,

I am sorry you are having trouble with the buying process.
Please take a look at the following steps from our FAQ:

**I Did Not Get The License Code Or Any Receipt Emails After Buying AlDente Pro!**

There are multiple reasons why you did not get your license code after the purchase:

1. Sometimes it takes up to 30 Minutes for the purchase emails to go through.
2. The purchase emails end up in the junk email folder.
3. You had a typo in the email address during your purchase.
4. Failures of the payment networks/providers.

Please contact the support team of our payment provider Paddle at [assist@paddle.com](mailto:assist@paddle.com) and include the email address you used to purchase AlDente Pro. The Paddle support will try to solve your issue as fast as possible.

Cheers,
Matthias
