### ISSUE TITLE
is my book charging or not?

### ISSUE THREAD

**Issue by vonundzuhabsucht** [davidwernhart/AlDente#754]
Hi
I use AL dente and set 50% as charge limit but If I take a look into apple battery it always shows "charge"..
Does ist Charge or not? (plug shows red indicator)

<img width="776" alt="Bildschirmfoto 2022-08-15 um 16 42 41" src="https://user-images.githubusercontent.com/111295222/184664090-9656eed9-c941-4714-865b-e60e9f799334.png">

**Comment by MatthiasKerbl** [comment]
Hi @vonundzuhabsucht,

it does definitely not charge when the battery does not go up.

Cheers,
Matthias
