### ISSUE TITLE
clamshell mode discharge doesn't work on m1 MacBook Pro. been using ardent since 1.01. but since the last few versions the discharge clamshell mode is not working . currently on the latest version

### ISSUE THREAD

**Issue by hardik746** [davidwernhart/AlDente#758]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**MacBook (please complete the following information):**
 - MacBook model (https://support.apple.com/en-us/HT201608)
 - macOS version (https://support.apple.com/en-us/HT201260)
 - AlDente Pro or AlDente Free?
 - AlDente Version?
 - List of all enabled/disabled settings in AlDente:

**Additional context**

**Comment by hardik746** [comment]
Thanks you very much for replying, actually I saw that I had not updated my MacBook . After updating it the functions works as expected. Thank you David

**Comment by MatthiasKerbl** [comment]
> Thanks you very much for replying, actually I saw that I had not updated my MacBook . After updating it the functions works as expected. Thank you David
> […](#)
> On 30 Aug 2022, 7:25 PM +0530, Matthias Kerbl ***@***.***>, wrote: Hi @hardik746, Could you give us more details about the bug? As a start, it would help if you could fill out the following questions: Describe the bug A clear and concise description of what the bug is. To Reproduce Steps to reproduce the behavior: Go to '...' Click on '....' Scroll down to '....' See error Expected behavior A clear and concise description of what you expected to happen. Screenshots If applicable, add screenshots or screen recordings to help explain your problem. MacBook (please complete the following information): MacBook model (https://support.apple.com/en-us/HT201608) macOS version (https://support.apple.com/en-us/HT201260) AlDente Pro or AlDente Free? AlDente Version? List of all enabled/disabled settings in AlDente: Additional context Add any other context about the problem here. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

That's good to hear. :)

Cheers,
Matthias
