### ISSUE TITLE
Schedule charge-up

### ISSUE THREAD

**Issue by Nikita7x** [davidwernhart/AlDente#762]
Ability to make a schedule for charge and discharge. For example, I want AlDente to keep my battery at 65% the whole work day, but by the time I leave my work, I want it to top up my battery to 100%.

**Comment by jenham** [comment]
This would be really nice. I agree.

**Comment by DamonHD** [comment]
May be easy to combine with #445.

Rgds

Damon

**Comment by MatthiasKerbl** [comment]
Hi @Nikita7x,

Thank you for sharing this great idea.
We already have a thread for this feature request here #248. Therefore, I will close this issue but feel free to add your ideas regarding this enhancement at #248.

Cheers,
Matthias
