### ISSUE TITLE
icon app stuck on the dock

### ISSUE THREAD

**Issue by joacomonte** [davidwernhart/AlDente#765]
![image](https://user-images.githubusercontent.com/70350164/189389142-c0937151-ea09-4218-b7a4-36989dd4d116.png)

i cant remove the icon app from the dock with the latest update

**Comment by MatthiasKerbl** [comment]
> ![image](https://user-images.githubusercontent.com/70350164/189389142-c0937151-ea09-4218-b7a4-36989dd4d116.png)
> 
> i cant remove the icon app from the dock with the latest update

Hi @joacomonte,

Just open the AlDente settings, go to Appearance/Other and disable "Show Dock Icon".

Cheers,
Matthias

**Comment by joacomonte** [comment]
omg, you are right, sorry haha

**Comment by joacomonte** [comment]
@MatthiasKerbl omg, you are right, sorry haha
