### ISSUE TITLE
MacBook Air M1 2020 Shutdown Limit Charging

### ISSUE THREAD

**Issue by suokeweiya** [davidwernhart/AlDente#769]
Hello, I want to ask about AIDente Pro. My computer is MacBook Air M1 2020, and the free version of AIDente is currently used. When I plug in the charger and turn it on, I can limit the charging, but the software fails once I turn it off. If I plug it in at this time, it will be fully charged to 100%. I want to ask if AIDente Pro can always charge according to the preset limit when I turn it off and plug it in

**Comment by MatthiasKerbl** [comment]
Hi @suokeweiya,

Please take a look at the following blog posts regarding your questions:

https://apphousekitchen.com/feature-explanation-stop-charging-when-powered-off-app-closed/
https://apphousekitchen.com/feature-explanation-stop-charging-when-sleeping/
https://apphousekitchen.com/feature-explanation-disable-sleep-until-charge-limit/

Cheers,
Matthias
