### ISSUE TITLE
order problem

### ISSUE THREAD

**Issue by wanghanke** [davidwernhart/AlDente#776]
I placed an order for AlDente Pro on the official website, but did not receive the email. Please where can I check the order.

**Comment by MatthiasKerbl** [comment]
Hi @wanghanke,

Please take a look at the FAQ section of our pricing website:

"I Did Not Get The License Code Or Any Receipt Emails After Buying AlDente Pro!

There are multiple reasons why you did not get your license code after the purchase:

1. Sometimes it takes up to 30 Minutes for the purchase emails to go through.
2. The purchase emails end up in the junk email folder.
3. You had a typo in the email address during your purchase.
4. Failures of the payment networks/providers.

Please contact the support team of our payment provider Paddle at [assist@paddle.com](mailto:assist@paddle.com) and include the email address you used to purchase AlDente Pro. The Paddle support will try to solve your issue as fast as possible."

Hope that helps.

Cheers,
Matthias

**Comment by wanghanke** [comment]
thanks
