### ISSUE TITLE
Battery status will not change/reduce when using my MacBook Air M2 2022  with USB-C power.

### ISSUE THREAD

**Issue by atlet6** [davidwernhart/AlDente#779]
I use sailing mode. The current settings are limit 75% with 5 % down to 70 %. 

When using an LG monitor with USB-C  power supply , there will be no changes/reducing from any battery values over the low limit  70% ( I use Hardware Battery Precentage) and the MacBook battery monitor which are som  few precent more,  when I use the MacBook. The MacBook battery monitor says " will not charge"  and I can't see any charging to the battery as it supposed to be during my sessions with the LG Monitor?  But the AlDente battery monitors stays on the same value all the time ( The MacBook monitor also stay on the same value  ) during my 1-2 hours session .

When I unplug the LG Monitor/ USB-C power and start using the MacBook without any power it will start reducing/drop in the battery percentage below the sailing limit, booth in AlDente battery monitor an MacBook battery monitor.  Plugging in the LG monitor again  **below** 70% limit it will charge the MacBook Air to 75 % and stop. Plugging in power with battery % **over** 70% , battery will stay on exactly the same value as long as LG monitor are plugged in.  AlDente monitor/app are active all time. **Could it be sailing mode do not work?** 

I use a brand new MacBook Air M2 2022 with a LG 27UP850-W Monitor. USB-C power from monitor til MacBook Air.
OS version are Monterey 12.6.  I also use AlDente Pro v1.18

**Comment by MatthiasKerbl** [comment]
Hi @atlet6,

As far as I understand it, everything is working as intended.
Please read our feature explanation article about the Sailing Mode on our blog: https://apphousekitchen.com/feature-explanation-sailing-mode/

Cheers,
Matthias
