### ISSUE TITLE
Add a `Get Charge Limit` shortcuts action

### ISSUE THREAD

**Issue by infused-kim** [davidwernhart/AlDente#785]
**Is your feature request related to a problem? Please describe.**
I would like to build a [raycast](https://www.raycast.com) extension that shows the currently set charge limit.

**Describe the solution you'd like**
Add a `Get Charge Limit` shortcuts action that returns the current charge limit as a percentage value.

**Describe alternatives you've considered**
I tried all the existing actions, but none of them do what I want. The `Get Percentage` action returns the current charge level and now the limit.

**Additional context**
<img width="547" alt="Screen Shot 2022-10-11 at 09 58 59" src="https://user-images.githubusercontent.com/7404004/195127076-52ddb6db-db3f-4ac2-b17b-bd734c986e3d.png">

**Comment by MatthiasKerbl** [comment]
Hi @infused-kim,

That's a good idea and we will implement it with one of the future updates.

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @infused-kim,

We have just released AlDente 1.19 which includes Get Charge Limit shortcuts action.
Hope you like it.

Cheers,
Matthias

**Comment by infused-kim** [comment]
Amazing. It's working perfectly.

Btw, the blog post that is linked in the update note about automatic discharging doesn't seem to exist.

**Comment by MatthiasKerbl** [comment]
I am glad you like it.
That's weird, it is working for me here: https://github.com/davidwernhart/AlDente/releases
