### ISSUE TITLE
Can't change to clamshell mode

### ISSUE THREAD

**Issue by fandiluo** [davidwernhart/AlDente#800]
**Describe the bug**
After upgrading macOS Ventura version
Can't change to clamshell mode

**To Reproduce**
1. Click Discharge

**Expected behavior**
Change to clamshell mode

**Screenshots**
![Screenshot 2022-10-25 at 10 37 42 AM](https://user-images.githubusercontent.com/9468958/197669205-02e0ce75-c5ca-4f0a-b055-d12bd83b1c59.png)

**MacBook (please complete the following information):**
 - MacBook model MacBook Pro 16-inch 2019
 - macOS version Ventura 13.0
 - AlDente Free
 - AlDente Version 1.19.1
 - List of all enabled/disabled settings in AlDente: Free Version

**Comment by MatthiasKerbl** [comment]
Hi @fandiluo,

Discharge during clamshell mode is only supported in AlDente Pro.

Cheers,
Matthias

**Comment by fandiluo** [comment]
Hi @MatthiasKerbl 

But I haven't updated macOS (Ventura) when I can click to discharge.
"discharge", I thought this was a free feature, I don't know how I used to use
![Screenshot 2022-10-25 at 4 04 32 PM](https://user-images.githubusercontent.com/9468958/197718272-2801a38d-bb09-4572-af04-645f5e019574.png)

If this is really not a bug, I will consider buying it!

Thanks!

**Comment by fandiluo** [comment]
Addendum.
I came home and used another mac (12.6) and it functioned fine

**Comment by MatthiasKerbl** [comment]
Hi @fandiluo,

I don't know if I understood your question correctly.

In general, Discharge is a feature that's also available in AlDente Free. However, if you want to use the Discharge feature while your MacBook is in clamshell mode, then you need AlDente Pro.

Cheers,
Matthias

**Comment by fandiluo** [comment]
Hi @MatthiasKerbl  

I'll try to explain again
AlDente Free discharge works in 12.6
AlDente Free discharge does not work in 13.0 and shows that you have to upgrade to Pro to use it
If you have macOS 13, I hope you can use the free version to reproduce 
Thank you very much!
