### ISSUE TITLE
For change email address

### ISSUE THREAD

**Issue by Marcus0605** [davidwernhart/AlDente#814]
Hello,

I want to change my activation email, because I want to delete my email account soon. Just be safe, I hope change my activation to a new email address.
I have sent mail to Support <support@apphousekitchen.com>. Please take time to handle it.
thank you.

Regards,
Marcus.

**Comment by MatthiasKerbl** [comment]
Hi @Marcus0605,

If you have sent an email to our Premium support, we will take care of it there as quickly as possible.

Cheers,
Matthias
