### ISSUE TITLE
Latest release is not "latest" in GitHub

### ISSUE THREAD

**Issue by lpla** [davidwernhart/AlDente#820]
**Describe the bug**
Release 1.19.2 is not marked as the latest release in GitHub releases section, but 1.19.1.

**To Reproduce**
1. Go to https://github.com/davidwernhart/AlDente/releases
2. Check that the label "Latest" is on release 1.19.1 instead of 1.19.2.

**Expected behavior**
Release 1.19.2 should be marked as latest, helping automatic systems like "homebrew-cask" livecheck to update its reference. 

**Additional context**
See Homebrew Cask repository pull request for specific logs: https://github.com/Homebrew/homebrew-cask/pull/134900

**Comment by MatthiasKerbl** [comment]
Hi @lpla,

Thanks for pointing out this mistake.
I have already fixed it.

Cheers,
Matthias
