### ISSUE TITLE
Not going to sleep when lid closed

### ISSUE THREAD

**Issue by MaybeThisIsRu** [davidwernhart/AlDente#846]
**Describe the bug**

Laptop is plugged in. When closing the lid, it does not go to sleep anymore.

**To Reproduce**

1. Set charge limit to 80%
2. Charge to 80%
3. Let it hold
4. Close the lid
5. Laptop is not sleeping as it does not boot from sleep like it does.

**Expected behavior**

Laptop goes to sleep when the lid is closed.

**Screenshots**

<img width="439" alt="image" src="https://user-images.githubusercontent.com/3974019/205961271-ae9e8f91-03b4-4a4c-a107-637ac34d519b.png">

<img width="440" alt="image" src="https://user-images.githubusercontent.com/3974019/205961491-4bcc491e-d736-4814-b251-2ff1197ed40c.png">

<img width="446" alt="image" src="https://user-images.githubusercontent.com/3974019/205961513-8e237a9c-9898-4beb-be1f-023eb2665ace.png">

<img width="445" alt="image" src="https://user-images.githubusercontent.com/3974019/205961523-af5b7d3a-de95-45aa-9efc-b8df9fe78ea2.png">

**MacBook (please complete the following information):**

 - MacBook model: MacBook Air, M1, 2020
 - macOS version: Ventura 13.0.1
 - AlDente Pro or AlDente Free? Pro
 - AlDente Version? 1.19.2
 - List of all enabled/disabled settings in AlDente: see screenshots above

**Additional context**
Sleep menu item is NOT greyed out and works fine as a workaround if I use it. However I want closing the lid to trigger sleep as normal.

**Comment by MatthiasKerbl** [comment]
Hi @MaybeThisIsRu,

Looking through your AlDente settings, AlDente should not prohibit sleep.
Are you 100% sure that your MacBook does not go into sleep? You can check that by playing a YouTube video for example. If it stops when you close the lid, your MacBook goes into sleep.
Do you have any macOS settings that prevent your MacBook from going into sleep, such as "Prevent automatic sleeping on power adapter when the display is off"?

Cheers,
Matthias
