### ISSUE TITLE
Working on MacBook Air "Core i3" 1.1 13" (Scissor, 2020) 1.1 GHz Core i3 (I3-1000NG4)

### ISSUE THREAD

**Issue by CompilerStyler** [davidwernhart/AlDente#86]
Confirm this works on the below system: 
MacBook Air "Core i3" 1.1 13" (Scissor, 2020) 1.1 GHz Core i3 (I3-1000NG4)
Running Big Sur 11.1

**Comment by TheMazus** [comment]
Glad it works and thanks for sharing. I'll add your system to the tested models.
