### ISSUE TITLE
103% charge issue where AlDente shows correct battery level (not 3% offset)

### ISSUE THREAD

**Issue by CompilerStyler** [davidwernhart/AlDente#87]
When I set AlDente to 80% I get exactly 80% charge per the MacOS battery indicator. This worries me because AlDente slides to 103% due to the 3% offset issue - does this create a hazard on systems that no longer require the offset (e.g. the laptop will try to actually overcharge itself)

System: 
MacBook Air "Core i3" 1.1 13" (Scissor, 2020) 1.1 GHz Core i3 (I3-1000NG4)
Big Sur 11.1

**Comment by TheMazus** [comment]
Hey CompilerStyler,
this issue should only appear after the first restart, afterward, it should stay at 100% as well. 
Even if you leave it at 103% it doesn't overcharge, so no worries.

**Comment by CompilerStyler** [comment]
Ah I see that now - thank you for checking!
