### ISSUE TITLE
AlDente doesn't Start - FIXED

### ISSUE THREAD

**Issue by Daniel14513** [davidwernhart/AlDente#915]
After installing the DMG, i can't Open AlDente, Nothing happens.(Right Click, Open)

There is no ALDente icon in the menu bar, as if the program does not start.

 - MacBook model: MacBook Pro 14 M1 Pro Base Model (https://support.apple.com/en-us/HT201608)
 - macOS version lastest MacOS Ventura Version / Clean install (https://support.apple.com/en-us/HT201260)
 - AlDente Pro or AlDente Free? Free Version
 - AlDente Version? Lastest
 - List of all enabled/disabled settings in AlDente: -

**Additional context**
-

**Comment by taylor325** [comment]
Hello [Daniel14513](https://github.com/Daniel14513)
I have a same problem here.
I have a temporaly solution: You need uninstall guide from [here](https://apphousekitchen.com/how-to-uninstall-aldente-pro/)
After complete uninstall you need reinstall AlDente Free or Pro.
After reinstall you need reboot and please go to mac system settings, general, login items.
You need remove AlDente from Login items and please close AlDente.
![Screenshot 2023-03-13 at 19 20 29](https://user-images.githubusercontent.com/52882397/224794177-7d477523-20b2-433f-ad59-f0a1d5a661ce.png)
Open AlDente and you see this notification: 
![Screenshot 2023-03-13 at 19 23 06](https://user-images.githubusercontent.com/52882397/224794733-f7a61ad5-a3fa-480f-9751-9d7395deb776.png)
Please reboot again and enjoy AlDente! 😎

**Comment by Daniel14513** [comment]
I have done the following: have now installed 1.19.1 and after that update to the latest version. now it works for me. (also the automatic login) but now ALDente stays in lower program site, when I close the program, the program closes completely, also in the upper menu bar. Can I run the program in the background?

**Comment by taylor325** [comment]
> I have done the following: have now installed 1.19.1 and after that update to the latest version. now it works for me. (also the automatic login) but now ALDente stays in lower program site, when I close the program, the program closes completely, also in the upper menu bar. Can I run the program in the background?

Of course. You need installed helper and enabled login item!
![Screenshot 2023-03-13 at 19 43 45](https://user-images.githubusercontent.com/52882397/224799499-a11a2b93-98af-45b1-a92a-d852b0d6feb8.png)

**Comment by Daniel14513** [comment]
But it also remains active in the menu bar (below)

**Comment by taylor325** [comment]
> But it also remains active in the menu bar (below)
You need this settings:
![Screenshot 2023-03-13 at 19 50 44](https://user-images.githubusercontent.com/52882397/224800830-f617a427-f187-4d1d-9710-018d466da0a6.png)

**Comment by taylor325** [comment]
> But it also remains active in the menu bar (below)
You need this settings: 
![Screenshot 2023-03-13 at 19 50 44](https://user-images.githubusercontent.com/52882397/224809348-e554d267-78be-4d54-a153-fb4b544bc372.png)

**Comment by Daniel14513** [comment]
I have activated so, however I have the free version. The app still remains at the bottom of the menu bar:
<img width="234" alt="Bildschirm­foto 2023-03-13 um 20 24 34" src="https://user-images.githubusercontent.com/127743644/224811458-c605c86c-5253-444a-8c57-43419048327a.png">

**Comment by taylor325** [comment]
> I have activated so, however I have the free version. The app still remains at the bottom of the menu bar: <img alt="Bildschirm­foto 2023-03-13 um 20 24 34" width="234" src="https://user-images.githubusercontent.com/127743644/224811458-c605c86c-5253-444a-8c57-43419048327a.png">
> 
> btw: thanks for your help!

You need fully uninstall and reinstall.
Check [this](https://github.com/davidwernhart/AlDente-Charge-Limiter/issues/915#issuecomment-1466687105) comment
I tested and worked here.

**Comment by MatthiasKerbl** [comment]
Hi everyone,

Thanks for sharing your experience with this bug. We are still investigating and will let you know when we find something.

**Comment by MatthiasKerbl** [comment]
> I have activated so, however I have the free version. The app still remains at the bottom of the menu bar: <img alt="Bildschirm­foto 2023-03-13 um 20 24 34" width="234" src="https://user-images.githubusercontent.com/127743644/224811458-c605c86c-5253-444a-8c57-43419048327a.png">
> 
> btw: thanks for your help!

Hi @Daniel14513,

You can disable the dock icon in AlDente and only let it run in the background.
Go to Settings/Appearance and disable "Show Dock Icon" at the bottom.

Cheers,
Matthias

**Comment by Daniel14513** [comment]
That works, thanks for the reply! 👍

**Comment by MatthiasKerbl** [comment]
Hi everyone,

We have just released AlDente 1.21.3 which resolves the issue you encountered. You can download it on GitHub here: https://github.com/davidwernhart/AlDente-Charge-Limiter/releases/tag/1.21.3
Sorry for the inconvenience.

Cheers,
Matthias
