### ISSUE TITLE
Better icon with status

### ISSUE THREAD

**Issue by pedrocatalao** [davidwernhart/AlDente#92]
- Icon design more consistent with the rest of the system icons
- Indication if battery charging is limited or not
- Simple way to enable/disable the limit (e.g. right click)

Related: https://github.com/davidwernhart/AlDente/issues/74

**Comment by nicho1asdev** [comment]
You can see if the charging is limited on the stock battery icon in the status bar. If it has a cable, it's limited, and if it has a thunderbolt, it's charging.

**Comment by pedrocatalao** [comment]
@nicho1asdev that's true but if this story is accepted and picked it makes sense to adjust the icon to also show the app status without having to look at another icon.

**Comment by TheMazus** [comment]
Hi pedrocatalao, your ideas sound great. I will definitely put it on our list to implement them.

**Comment by CharlieBrown12** [comment]
Program is absolutely great.

1. One more ask for a nicer status bar icon...
How about replicating the Mac battery icon? With the status charging or not.
In that case "original" battery icon can be disabled in System Preferences.

2. Disable Get Pro button until its really implemented.
I would donate to remove it (which I tried today) just to see that its "fake".

Many, many thanks for this app..

**Comment by stefandesu** [comment]
> 1. How about simply _replicating the Mac battery icon_?
>    With the status charging or not.
>    In that case "original" battery icon can be disabled in System Preferences.

I love this idea, would really appreciate this!

**Comment by vassudanagunta** [comment]
Also it doesn't look like a plate of pasta at that size unless you look really close. More like a donut with a stick hovering over it. Or a plate with a streak on it.

I'd recommend a different name anyway, if you're hoping to get popular. A name that either evokes what it does (like [Caffeine](https://caffeine.en.softonic.com/mac) and [Amphetamine](https://apps.apple.com/us/app/amphetamine/id937984704?mt=12))  or that is catchy on its own. Though that's how I like my pasta, the term doesn't appeal to me on its own :)

If you're really attached to the name, you still need something other than a plate of pasta.

IMHO :P

**Comment by MatthiasKerbl** [comment]
Hi @vassudanagunta,
thanks for the suggestions we will think about them.

Matthias

**Comment by Madhawa97** [comment]
<img width="516" alt="Screenshot 2021-04-02 at 09 05 44" src="https://user-images.githubusercontent.com/70215958/113377676-9d63be00-9392-11eb-9de2-a6b091820d8f.png">
making it to match with the colour of other icons would be great for the time being.

**Comment by MatthiasKerbl** [comment]
> * Icon design more consistent with the rest of the system icons
> * Indication if battery charging is limited or not
> * Simple way to enable/disable the limit (e.g. right click)
> 
> Related: #74

Hi @pedrocatalao,
we implemented your suggestions in AlDente Pro.
You can check it out here: https://apphousekitchen.com/

I hope you like it.
Matthias
